Repository codice/ddf, pull requests merged in 2018-12, with the labels that each got.

#4068 DDF-4333 Convert existing threat models to Threat Dragon format
  ThreatDragonModels/AdminUI/AdminUI.json
  ThreatDragonModels/Catalog/Catalog.json
  ThreatDragonModels/CatalogUI/CatalogUI.json
  ThreatDragonModels/FTPEndpoint/FTPEndpoint.json
  ThreatDragonModels/Kernel/Kernel.json
  ThreatDragonModels/README.md
  ThreatDragonModels/Registry/Registry.json
  ThreatDragonModels/Security/Security.json
  ThreatDragonModels/Solr/Solr.json
  ThreatDragonModels/SpatialApplication/SpatialApplication.json
  ThreatDragonModels/StandaloneSolr/StandaloneSolr.json
Labels: :book: Documentation

#4087 DDF-4366 Make the default active element upon opening a menu the selected item if there is one
  ui/packages/catalog-ui-search/src/main/webapp/react-component/menu/menu.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/menu/menu.spec.js
Labels: 👤 UI, 📈 Improvement

#4081 [2.13.x] DDF-4355 Sanitize Text Preview Action
  catalog/transformer/catalog-transformer-preview/pom.xml
  catalog/transformer/catalog-transformer-preview/src/main/java/org/codice/ddf/transformer/preview/PreviewMetacardTransformer.java
  features/cxf/src/main/feature/feature.xml
  pom.xml
Labels: 🏬 Release Branch

#4076 DDF-2824 Add missing comma in validators doc
  distribution/docs/src/main/resources/content/_developing/_devComponents/global-attribute-validators.adoc
Labels: :book: Documentation

#4043 DDF-4291 updated installing and configuring docs for certificate mgmt
  distribution/docs/src/main/resources/content/_managing/_installing/file-system-access.adoc
  distribution/docs/src/main/resources/content/_managing/_installing/hardware-reqs.adoc
  distribution/docs/src/main/resources/content/_managing/_installing/high-availability-initial-setup-exceptions.adoc
  distribution/docs/src/main/resources/content/_managing/_installing/high-availability-initial-setup.adoc
  distribution/docs/src/main/resources/content/_managing/_installing/initial-startup.adoc
  distribution/docs/src/main/resources/content/_managing/_installing/install-prereqs.adoc
  distribution/docs/src/main/resources/content/_managing/_installing/install-with-zip.adoc
  distribution/docs/src/main/resources/content/_managing/_installing/installing-intro.adoc
  distribution/docs/src/main/resources/content/_managing/_installing/java-reqs.adoc
  distribution/docs/src/main/resources/content/_managing/_securing/disallowing-login-wo-certs.adoc
  distribution/docs/src/main/resources/content/_managing/_securing/managing-certificates.adoc
  distribution/docs/src/main/resources/content/_managing/_securing/managing-crl.adoc
  distribution/docs/src/main/resources/content/_managing/_securing/managing-keystores.adoc
  distribution/docs/src/main/resources/templates/build/managing.ftl
Labels: :book: Documentation

#4009 DDF-4306 Adds Faceting support to Intrigue
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/QueryMetacardTypeImpl.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/CqlQueryResponse.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/CqlRequest.java
  ui/packages/catalog-ui-search/package.json
  ui/packages/catalog-ui-search/src/main/webapp/component/location-new/location-new.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/transmute/index.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js
  ui/packages/catalog-ui-search/src/main/webapp/plugins/query.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/auto-complete/auto-complete.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/auto-complete/auto-complete.spec.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/dropdown/dropdown.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/dropdown/dropdown.less
  ui/packages/catalog-ui-search/src/main/webapp/react-component/dropdown/dropdown.spec.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/location/keyword.spec.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/menu/menu.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/menu/menu.spec.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/react-component.less
  ui/packages/catalog-ui-search/tsconfig.json
Labels: ✨New Feature, 👤 UI

#4101 DDF-4369 Updated formatting in the Enabling Fallback Audit Logging documentation
  distribution/ddf-common/src/main/resources/etc/log4j2.xml
  distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.logging.cfg
  distribution/ddf-common/src/main/resources/security/configurations.policy
  distribution/docs/src/main/resources/content/_managing/_securing/auditing.adoc
Labels: :book: Documentation

#4100 DDF-3762 Updates color scheme
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/theme-container/theme-container.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/user-settings/user-settings.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/workspaces-templates/workspaces-templates.tsx
  ui/packages/catalog-ui-search/src/main/webapp/styles/vars.less
Labels: 👤 UI, 📈 Improvement

#4008 DDF-4141 Fix the table view so it exports the correct number of results in the correct order
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/table-export/table-export.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/table-export/table-export.tsx
Labels: 👞Bug Fix, 👤 UI

#4110 DDF-4385 Fixing Dropdown error
  ui/packages/catalog-ui-search/src/main/webapp/react-component/menu/menu.js
Labels: 👞Bug Fix, 👤 UI

#4113 DDF-4359 Update date input field placeholder text to use ISO 8601 format
  ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.less
  ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/input/date/input-date.view.js
Labels: 👤 UI, 📈 Improvement

#4035 DDF-4316 Configurable keyword i18n
  catalog/ui/catalog-ui-search/pom.xml
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java
  catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/config/ConfigurationApplicationTest.java
  catalog/ui/catalog-ui-search/src/test/resources/IntrigueBundle.properties
  catalog/ui/search-ui-app/pom.xml
  catalog/ui/search-ui-app/src/main/resources/etc/IntrigueBundle.properties
  catalog/ui/search-ui-app/src/main/resources/features.xml
  distribution/ddf-common/src/main/resources-filtered/etc/application-definitions/platform.json
  distribution/ddf-common/src/main/resources/security/default.policy
  features/admin/src/main/feature/feature.xml
  features/apps/src/main/feature/feature.xml
  platform/landing-page/pom.xml
  platform/landing-page/src/main/java/org/codice/ddf/landing/LandingPage.java
  platform/landing-page/src/main/resources/LandingPageBundle.properties
  platform/landing-page/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  platform/landing-page/src/main/resources/index.handlebars
  platform/landing-page/src/test/java/org/codice/ddf/landing/LandingPageTest.java
  platform/landing-page/src/test/resources/LandingPageBundle.properties
  platform/landing-page/src/test/resources/NoDataSourceKeywordBundle.properties
  platform/pom.xml
  platform/resource-bundle-locator/pom.xml
  platform/resource-bundle-locator/src/main/java/ddf/platform/resource/bundle/locator/ResourceBundleLocator.java
  platform/resource-bundle-locator/src/main/java/ddf/platform/resource/bundle/locator/ResourceBundleLocatorImpl.java
  platform/resource-bundle-locator/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  platform/resource-bundle-locator/src/test/java/ddf/platform/resource/bundle/locator/ResourceBundleLocatorImplTest.java
  platform/resource-bundle-locator/src/test/resources/TestFrenchResourceBundle_fr.properties
  platform/resource-bundle-locator/src/test/resources/TestResourceBundle.properties
  ui/packages/catalog-ui-search/package.json
  ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/query-src/dropdown.query-src.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/query-src/dropdown.query-src.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/navigation-middle/navigation-middle.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/navigator/navigator.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/navigator/navigator.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-src/query-src.view.js
  ui/packages/catalog-ui-search/src/main/webapp/js/ApplicationSetup.js
  ui/packages/catalog-ui-search/src/main/webapp/js/extensions/marionette.ItemView.attachElContent.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js
  ui/packages/catalog-ui-search/src/main/webapp/js/router/routes.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/router-container/router-container.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/sources-summary/sources-summary.tsx
  ui/yarn.lock
Labels: ✨New Feature, 👤 UI

#4038 DDF-4336: Refactored metacard interactions view
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-interactions/metacard-interactions.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-interactions/metacard-interactions.view.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-interactions/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/metacard-interactions/index.tsx
Labels: 🌊Impacts Downstream, 👤 UI, 🔨Refactor

#4122 [2.13.x]DDF-4389 Disable ECP when not using HTTPS
  platform/security/idp/security-idp-client/pom.xml
  platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/IdpHandler.java
  platform/security/idp/security-idp-client/src/test/java/org/codice/ddf/security/idp/client/IdpHandlerTest.java
  platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/client/impl/SecureCxfClientFactoryImpl.java
  platform/security/rest/security-rest-cxfwrapper/src/test/java/org/codice/ddf/cxf/SecureCxfClientFactoryTest.java
  platform/security/rest/security-rest-cxfwrapper/src/test/resources/SAMLAssertion.xml
Labels: 🏬 Release Branch, 👞Bug Fix

#4123 [2.13.x] DDF-4391 DivisibleBy query does not work on multivalued fields
  catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java
  catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrFilterDelegateTest.java
  catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/provider/SolrProviderQuery.java
Labels: 🏬 Release Branch, 👞Bug Fix

#4092 DDF-4367 Fix search results merging in Intrigue
  ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResponse.js
Labels: 👞Bug Fix, 👤 UI

#4064 DDF-4350 Add internal/system hostname and port to the installer
  platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdmin.java
  platform/admin/core/admin-core-impl/src/test/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdminTest.java
  ui/packages/ui/src/main/webapp/js/models/installer/Configuration.js
  ui/packages/ui/src/main/webapp/js/views/installer/Configuration.view.js
  ui/packages/ui/src/main/webapp/less/installer/style.less
Labels: 🏬 Release Branch, 👞Bug Fix, 📈 Improvement

#4097 DDF-4375 Added classes to realign navigation buttons
  ui/packages/ui/src/main/webapp/templates/installer/finish.handlebars
Labels: 👤 UI

#4129 DDF-4394 Localized polling sources error message
  catalog/ui/search-ui-app/src/main/resources/etc/IntrigueBundle.properties
  ui/packages/catalog-ui-search/src/main/webapp/js/ApplicationSetup.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js
Labels: 👤 UI

#4114 DDF-4386: Missing metacard definition handling and feedback
  ui/packages/catalog-ui-search/src/main/webapp/component/builder/builder.less
  ui/packages/catalog-ui-search/src/main/webapp/component/builder/builder.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/property/property.collection.view.js
Labels: 👤 UI

#4108 DDF-4383 Make Preview, History, Associations, Quality, Archive, and Overwrite Inspector tabs in Intrigue optional.
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java
  catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.xml
  catalog/ui/search-ui-app/src/main/resources/etc/org.codice.ddf.catalog.ui.config
  distribution/docs/src/main/resources/content/_reference/_tables/catalog.ui.config.adoc
  ui/packages/catalog-ui-search/src/main/webapp/component/tabs/metacard/tabs-metacard.less
  ui/packages/catalog-ui-search/src/main/webapp/component/tabs/metacard/tabs-metacard.view.js
  ui/packages/catalog-ui-search/src/main/webapp/js/properties.js
Labels: 👤 UI

#4118 DDF-4381 Fixing sorting order of recently used workspaces
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/workspaces-items-container/workspaces-items-container.tsx
Labels: 👤 UI

#4149 DDF-4316: Fix race condition where landing page bundle starts before availability header is availabile
  distribution/ddf-common/src/main/resources/etc/i18n/LandingPageBundle/LandingPageBundle.properties
  features/admin/src/main/feature/feature.xml
  platform/landing-page/pom.xml
Labels: 👞Bug Fix

#4141 DDF-4403 Remove PowerMock to support Java11
  catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/federation/base/AbstractFederationStrategy.java
  catalog/core/catalog-core-camelcomponent/pom.xml
  catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/metacardtransformer/MetacardTransformerProducer.java
  catalog/core/catalog-core-camelcomponent/src/test/java/ddf/camel/component/catalog/inputtransformer/InputTransformerProducerTest.java
  catalog/core/catalog-core-camelcomponent/src/test/java/ddf/camel/component/catalog/metacardtransformer/MetacardTransformerProducerTest.java
  catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/TransformersCommandTest.java
  catalog/core/catalog-core-federationstrategy/pom.xml
  catalog/core/catalog-core-federationstrategy/src/main/java/ddf/catalog/federation/impl/SortedFederationStrategy.java
  catalog/core/catalog-core-federationstrategy/src/test/java/ddf/catalog/federation/impl/FederationStrategyTest.java
  catalog/core/catalog-core-standardframework/pom.xml
  catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/ReliableResourceDownloader.java
  catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/resource/download/ReliableResourceDownloaderTest.java
  catalog/core/catalog-core-validationparser/pom.xml
  catalog/core/catalog-core-validationparser/src/main/java/ddf/catalog/validation/impl/ValidationParser.java
  catalog/core/catalog-core-validationparser/src/test/groovy/ddf/catalog/validation/impl/ValidationParserSpec.groovy
  catalog/core/pom.xml
  catalog/plugin/catalog-plugin-security-audit/pom.xml
  catalog/plugin/catalog-plugin-security-audit/src/main/java/org/codice/ddf/catalog/plugin/security/audit/SecurityAuditPlugin.java
  catalog/plugin/catalog-plugin-security-audit/src/test/java/org/codice/ddf/catalog/plugin/security/audit/SecurityAuditPluginTest.java
  platform/admin/core/admin-core-migration-commands/pom.xml
  platform/security/common/pom.xml
  platform/security/common/src/main/java/org/codice/ddf/security/common/Security.java
  platform/security/common/src/test/java/org/codice/ddf/security/common/SecurityTest.java
  platform/security/core/security-core-impl/pom.xml
  platform/security/core/security-core-services/pom.xml
  platform/security/pep/security-pep-interceptor/pom.xml
  platform/security/pep/security-pep-interceptor/src/main/java/ddf/security/pep/interceptor/PEPAuthorizingInterceptor.java
  platform/security/pep/security-pep-interceptor/src/test/java/ddf/security/pep/interceptor/PepInterceptorActionsTest.java
  platform/security/pep/security-pep-interceptor/src/test/java/ddf/security/pep/interceptor/PepInterceptorInvalidSubjectTest.java
  platform/security/pep/security-pep-interceptor/src/test/java/ddf/security/pep/interceptor/PepInterceptorNullAssertionTest.java
  platform/security/pep/security-pep-interceptor/src/test/java/ddf/security/pep/interceptor/PepInterceptorNullAssertionTokenTest.java
  platform/security/pep/security-pep-interceptor/src/test/java/ddf/security/pep/interceptor/PepInterceptorValidSubjectTest.java
  platform/security/pom.xml
  platform/security/sts/security-sts-ldapclaimshandler/pom.xml
  platform/security/sts/security-sts-ldapclaimshandler/src/main/java/ddf/security/sts/claimsHandler/AttributeMapLoader.java
  platform/security/sts/security-sts-ldapclaimshandler/src/main/java/ddf/security/sts/claimsHandler/ClaimsHandlerManager.java
  platform/security/sts/security-sts-ldapclaimshandler/src/main/java/ddf/security/sts/claimsHandler/LdapClaimsHandler.java
  platform/security/sts/security-sts-ldapclaimshandler/src/main/java/ddf/security/sts/claimsHandler/RoleClaimsHandler.java
  platform/security/sts/security-sts-ldapclaimshandler/src/test/java/ddf/security/sts/claimsHandler/AttributeMapLoaderTest.java
  platform/security/sts/security-sts-ldapclaimshandler/src/test/java/ddf/security/sts/claimsHandler/LdapClaimsHandlerTest.java
  platform/security/sts/security-sts-ldapclaimshandler/src/test/java/ddf/security/sts/claimsHandler/RoleClaimsHandlerTest.java
  platform/security/sts/security-sts-ldaplogin/pom.xml
  platform/security/sts/security-sts-ldaplogin/src/test/java/ddf/ldap/ldaplogin/SslLdapLoginModuleTest.java
  pom.xml
Labels: ☕ J11 Upgrade, 📈 Improvement

#4151 DDF-4235 Fixed styling for system result forms
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.view.js
Labels: 👤 UI, 📈 Improvement

#4137 DDF-4400 refactored max query notification
  ui/packages/catalog-ui-search/src/main/webapp/component/confirmation/confirmation.less
  ui/packages/catalog-ui-search/src/main/webapp/component/confirmation/query/confirmation.query.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/confirmation/query/confirmation.query.less
  ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/query-select/dropdown.query-select.hbs
Labels: 👤 UI

#4159 DDF-4411 Making search form settings persist after refresh
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form-tab-container.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.view.js
Labels: 👞Bug Fix, 👤 UI

#4160 DDF-4133 fix backup command
  catalog/core/catalog-core-solrcommands/pom.xml
  catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java
  catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/HttpWrapper.java
  catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/ResponseWrapper.java
  catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/SolrCommands.java
  catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/SolrHttpWrapper.java
  catalog/core/catalog-core-solrcommands/src/test/java/org/codice/ddf/commands/solr/BackupCommandTest.java
  platform/solr/solr-factory-impl/pom.xml
  platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/HttpClientBuilder.java
  platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/HttpSolrClientFactory.java
  platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/SolrClientFactoryImpl.java
  platform/solr/solr-factory-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  platform/solr/solr-factory-impl/src/test/java/org/codice/solr/factory/impl/SolrClientFactoryImplTest.java
  platform/solr/solr-password/src/main/java/ddf/platform/solr/security/SolrPasswordUpdate.java
  platform/solr/solr-password/src/main/java/ddf/platform/solr/security/SolrPasswordUpdateImpl.java
  platform/solr/solr-password/src/test/groovy/SolrPasswordUpdateSpec.groovy
Labels: 👞Bug Fix

#4082 [2.13.x] DDF-{4365, 4370, 4372, 4374} Minor bugfixes/improvements
  catalog/core/catalog-core-eventcommands/pom.xml
  catalog/core/catalog-core-eventcommands/src/main/java/org/codice/ddf/catalog/pubsub/command/ListCommand.java
  catalog/core/catalog-core-eventcommands/src/test/java/org/codice/ddf/catalog/pubsub/command/ListCommandTest.java
  distribution/ddf-common/src/main/resources/security/default.policy
  platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/paos/PaosInInterceptor.java
  ui/packages/catalog-admin-module-sources/src/main/webapp/js/model/Source.js
  ui/packages/catalog-admin-module-sources/src/main/webapp/js/model/Status.js
Labels: 🏬 Release Branch, 👤 UI, 📈 Improvement

#4152 [2.13.x] DDF-4409 Fixing CSS to keep text breaking out of popovers
  ui/packages/registry-admin-remote-ui/src/main/webapp/less/styles.less
Labels: 👞Bug Fix, 👤 UI
