Repository codice/ddf, pull requests merged in 2018-11, with the labels that each got.

#3976 DDF-4289 Fix relative time searches
  ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/multivalue/multivalue.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/relative-time/relative-time.view.js
Labels: UI

#3971 [2.13.x] DDF-4285 Validate certs before saving system properties
  ui/packages/ui/src/main/webapp/js/views/installer/Configuration.view.js
Labels: 👤 UI

#3965 DDF-4283 remove search form interaction menu when accessing the search form via the workspace
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form-selector/search-form-selector.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/forms-sharing/search-form-sharing-tab-container.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/forms-sharing/search-form-sharing.collection.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form-tab-container.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.collection.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/tabs/search-form/tabs.search-form.view.js
Labels: 👤 UI, 🔨Refactor

#3990 DDF-4298 Improve UI CI Incremental Build
  distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
  distribution/test/itests/test-itests-ddf/pom.xml
Labels: 🔨Refactor

#3934 DDF-4263 Adds password component, fixes slideout bug
  ui/packages/catalog-ui-search/src/main/webapp/component/input/password/input-password.tsx
  ui/packages/catalog-ui-search/src/main/webapp/component/input/password/input-password.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/property/property.js
  ui/packages/catalog-ui-search/src/main/webapp/component/slideout/slideout.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/value/value.view.js
  ui/packages/catalog-ui-search/src/main/webapp/dev/component/guide/guide.view.js
  ui/packages/catalog-ui-search/src/main/webapp/dev/component/password/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/dev/component/password/password.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/input-wrappers/base/base.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/input-wrappers/password/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/input-wrappers/password/password.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/user/user.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/navigation-left/navigation-left.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/navigation-right/navigation-right.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/user/user.tsx
Labels: ✨New Feature, 👤 UI

#4000 DDF-4305 updated docs for editing metadata attributes
  distribution/docs/src/main/resources/content/_running/editing-attributes.adoc
Labels: :book: Documentation

#4005 DDF-4314 Adding new security policy to allow geonames ingest
  distribution/ddf-common/src/main/resources/security/default.policy
Labels: 📈 Improvement

#4022 DDF-4106 Fixes dropdown interop
  ui/packages/catalog-ui-search/src/main/webapp/behaviors/dropdown.behavior.utility.js
Labels: 👞Bug Fix, 👤 UI

#4002 [2.13.x]DDF-4310 Make the Default Layout config editable
  ui/packages/catalog-admin-module-layout/src/main/webapp/default-layout/index.js
  ui/packages/catalog-admin-module-layout/src/main/webapp/default-layout/reducer.js
Labels: ✨New Feature, 🏬 Release Branch, 👤 UI

#4012 [2.13.x]DDF-4227 Upgrade to Karaf 4.2.1
  catalog/opensearch/catalog-opensearch-endpoint/pom.xml
  catalog/opensearch/catalog-opensearch-endpoint/src/main/resources/META-INF/MANIFEST.MF
  distribution/ddf-common/pom.xml
  distribution/ddf-common/src/main/resources-filtered/etc/custom.system.properties
  distribution/ddf-common/src/main/resources-filtered/etc/startup.properties
  distribution/ddf-common/src/main/resources/bin/setenv-windows-wrapper.conf
  distribution/ddf-common/src/main/resources/bin/start
  distribution/ddf-common/src/main/resources/common-bin.xml
  distribution/ddf-common/src/main/resources/etc/org.apache.karaf.features.xml
  distribution/ddf-common/src/main/resources/security/default.policy
  distribution/docs/src/main/resources/content/_dependencyList/ddf-dependency-list.adoc
  distribution/docs/src/main/resources/content/_running/ddf-service.adoc
  distribution/kernel/pom.xml
  distribution/test/itests/README.md
  distribution/test/itests/test-itests-common/pom.xml
  distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
  features/pom.xml
  platform/io/platform-io-impl/pom.xml
  platform/migration/platform-migration/pom.xml
  platform/osgi/platform-osgi-configadmin/pom.xml
  platform/osgi/platform-osgi-configadmin/src/main/java/org/apache/felix/cm/impl/ConfigurationManager.java
  platform/osgi/platform-osgi-configadmin/src/main/java/org/codice/felix/cm/file/Activator.java
  platform/util/platform-util/pom.xml
  pom.xml
Labels: ✨New Feature, 🏬 Release Branch

#4024 DDF-4310 Make the Default Layout config editable
  ui/packages/catalog-admin-module-layout/src/main/webapp/default-layout/index.js
  ui/packages/catalog-admin-module-layout/src/main/webapp/default-layout/reducer.js
Labels: ✨New Feature, 🏬 Release Branch, 👤 UI

#4015 [2.13.x]DDF-4322 Fix the HA installation profile
  catalog/catalog-app/src/main/resources/features.xml
  catalog/spatial/spatial-app/src/main/resources/features.xml
  distribution/ddf-common/src/main/resources/etc/profiles/ha.json
Labels: 🏬 Release Branch, 👞Bug Fix

#4017 DDF-4324 Fixed Multipolygon Check in Gazetteer Box
  ui/packages/catalog-ui-search/src/main/webapp/react-component/location/gazetteer.js
Labels: 👞Bug Fix, 👤 UI

#3991 DDF-3584 Updates UI README.md
  ui/README.md
  ui/package.json
Labels: :book: Documentation

#3980 DDF-4293 Fixed race conditions with SimpleDateFormatter
  catalog/spatial/kml/spatial-kml-transformer/src/main/java/org/codice/ddf/spatial/kml/transformer/DescriptionTemplateHelper.java
  platform/metrics/platform-metrics-reporting/src/main/java/ddf/metrics/reporting/internal/rest/MetricsEndpoint.java
Labels: 👞Bug Fix

#4013 DDF-4321 Search forms can be saved with no title
  ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js
Labels: 👞Bug Fix, 👤 UI

#3987 DDF-4297 Fix camel S3 connection with changes in Camel 2.22
  catalog/plugin/catalog-plugin-metacardbackup-s3storage/pom.xml
  catalog/plugin/catalog-plugin-metacardbackup-s3storage/src/main/java/org/codice/ddf/catalog/plugin/metacard/backup/storage/s3storage/MetacardS3StorageRoute.java
  catalog/plugin/catalog-plugin-metacardbackup-s3storage/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/plugin/catalog-plugin-metacardbackup-s3storage/src/main/resources/OSGI-INF/metatype/metatype.xml
  catalog/plugin/catalog-plugin-metacardbackup-s3storage/src/test/java/org/codice/ddf/catalog/plugin/metacard/backup/storage/s3storage/MetacardBackupS3StorageTest.java
Labels: 👞Bug Fix

#3984 DDF-4291 updated installing and configuring docs for certificate mgmt
  distribution/docs/src/main/resources/content/_configuring/disallowing-login-wo-certs.adoc
  distribution/docs/src/main/resources/content/_configuring/managing-certificates.adoc
  distribution/docs/src/main/resources/content/_configuring/managing-crl.adoc
  distribution/docs/src/main/resources/content/_configuring/managing-keystores.adoc
  distribution/docs/src/main/resources/content/_installing/file-system-access.adoc
  distribution/docs/src/main/resources/content/_installing/hardware-reqs.adoc
  distribution/docs/src/main/resources/content/_installing/high-availability-initial-setup-exceptions.adoc
  distribution/docs/src/main/resources/content/_installing/high-availability-initial-setup.adoc
  distribution/docs/src/main/resources/content/_installing/initial-startup.adoc
  distribution/docs/src/main/resources/content/_installing/install-prereqs.adoc
  distribution/docs/src/main/resources/content/_installing/install-with-zip.adoc
  distribution/docs/src/main/resources/content/_installing/installing-intro.adoc
  distribution/docs/src/main/resources/content/_installing/java-reqs.adoc
  distribution/docs/src/main/resources/templates/build/managing.ftl
Labels: :book: Documentation

#3994 DDF-4280 updated docs for metacard groomer (#3973)
  distribution/docs/src/main/resources/content/_architectures/_plugins/metacard-groomer.adoc
  distribution/docs/src/main/resources/templates/build/plugins.ftl
Labels: :book: Documentation

#4026 DDF-4321 Adds backend validation for search forms with missing or empty titles
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/TemplateTransformer.java
  catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/forms/TemplateTransformerTest.java
Labels: 👞Bug Fix

#4036 DDF-4106 Updates new dropdown to take bottom or top into account
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/dropdown/dropdown.tsx
Labels: 👞Bug Fix, 👤 UI

#3985 DDF-4292 Allowing Intrigue's Coordinate Display to be Configureable
  ui/packages/catalog-ui-search/src/main/webapp/component/map-info/map-info.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/map-info/map-info.view.js
Labels: 👤 UI

#4016 [2.13.x] DDF-4319 Add catalog source descriptions to the Admin UI when configuring/editing sources
  catalog/confluence/catalog-confluence-source/src/main/resources/OSGI-INF/metatype/metatype.xml
  catalog/opensearch/catalog-opensearch-source/src/main/resources/OSGI-INF/metatype/metatype.xml
  catalog/spatial/csw/spatial-csw-source/src/main/resources/OSGI-INF/metatype/metatype.xml
  catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/main/resources/OSGI-INF/metatype/metatype.xml
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/resources/OSGI-INF/metatype/metatype.xml
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/resources/OSGI-INF/metatype/metatype.xml
  platform/admin/core/admin-core-api/src/main/java/org/codice/ddf/admin/core/api/Service.java
  platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/ConfigurationAdminImpl.java
  ui/packages/catalog-admin-module-sources/src/main/webapp/js/view/ModalSource.view.js
  ui/packages/catalog-admin-module-sources/src/main/webapp/templates/sourceModal.handlebars
Labels: 🏬 Release Branch, 👤 UI, 📈 Improvement

#4007 DDF-4317 As a user, I want to copy MGRS and UTM/UPS coordinates from the map to the clipboard
  ui/packages/catalog-ui-search/src/main/webapp/behaviors/dropdown.behavior.utility.js
  ui/packages/catalog-ui-search/src/main/webapp/component/map-context-menu/map-context-menu.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/map-context-menu/map-context-menu.less
  ui/packages/catalog-ui-search/src/main/webapp/component/map-context-menu/map-context-menu.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.model.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/button-behavior/button-behavior.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/copy-coordinates/copy-coordinates.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/copy-coordinates/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/dropdown/dropdown.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/menu-action/menu-action.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/menu-item/menu-item.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/navigation-behavior/navigation-behavior.tsx
Labels: ✨New Feature, 👤 UI

#4049 DDF-4340 Add additional context to query-settings component
  ui/packages/catalog-ui-search/src/main/webapp/component/search-settings/search-settings.view.js
Labels: ✨New Feature, 👤 UI

#4004 DDF-4315 Incorporating Buffer/Units Into Keyword Location
  ui/packages/catalog-ui-search/src/main/webapp/react-component/location/keyword.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/location/multipoly.js
Labels: ✨New Feature, 👤 UI

#4014 DDF-4318 As a user, I want map coordinate display settings for MGRS and UTM/UPS formats
  ui/packages/catalog-ui-search/src/main/webapp/component/map-info/map-info.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/map-info/map-info.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/map-settings/map-settings.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/cesium.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.hbs
Labels: ✨New Feature, 👤 UI

#4051 [2.13.x]DDF-4178 updated cxf, camel, http, and shiro
  catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ExportCommand.java
  catalog/core/catalog-core-directorymonitor/pom.xml
  catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorIT.java
  catalog/pom.xml
  catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/GetRecordsResponseConverterTest.java
  catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/IdentityNodeInitializationTest.java
  catalog/transformer/catalog-transformer-common/pom.xml
  catalog/transformer/catalog-transformer-rtf/src/test/java/ddf/catalog/transformer/output/rtf/RtfQueryResponseAndMetacardTransformerTest.java
  distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java
  features/camel/src/main/feature/feature.xml
  features/pom.xml
  features/security/src/main/feature/feature.xml
  features/test-utilities/src/main/feature/feature.xml
  platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/migratable/JsonFeatureTest.java
  pom.xml
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/user/user.tsx
Labels: ⬆️ Dependency Upgrade, 🌊Impacts Downstream, 🏬 Release Branch

#3885 DDF-4123 Update doc security-rest-intro with jetty authenticator
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-rest-intro.adoc
Labels: :book: Documentation

#4003 DDF-4311 Remove UI component, add url functionality to the CLI, and u…
  catalog/spatial/geocoding/pom.xml
  catalog/spatial/geocoding/spatial-geocoding-admin-module/README.md
  catalog/spatial/geocoding/spatial-geocoding-admin-module/pom.xml
  catalog/spatial/geocoding/spatial-geocoding-admin-module/src/main/java/org/codice/ddf/spatial/admin/module/GeocodingModulePlugin.java
  catalog/spatial/geocoding/spatial-geocoding-admin-module/src/main/java/org/codice/ddf/spatial/admin/module/service/Geocoding.java
  catalog/spatial/geocoding/spatial-geocoding-admin-module/src/main/java/org/codice/ddf/spatial/admin/module/service/GeocodingMBean.java
  catalog/spatial/geocoding/spatial-geocoding-admin-module/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/spatial/geocoding/spatial-geocoding-admin-module/src/test/java/org/codice/ddf/spatial/admin/module/GeocodingMbeanTest.java
  catalog/spatial/geocoding/spatial-geocoding-extract/pom.xml
  catalog/spatial/geocoding/spatial-geocoding-extract/src/main/java/org/codice/ddf/spatial/geocoding/extract/GeoNamesFileExtractor.java
  catalog/spatial/geocoding/spatial-geocoding-extract/src/test/java/org/codice/ddf/spatial/geocoding/extract/GeoNamesFileExtractorTest.java
  catalog/spatial/geocoding/spatial-geocoding-offline-catalog/src/main/java/org/codice/ddf/spatial/geocoding/index/GeoNamesCatalogIndexer.java
  catalog/spatial/geocoding/spatial-geocoding-offline-catalog/src/main/java/org/codice/ddf/spatial/geocoding/index/IndexInitializer.java
  catalog/spatial/spatial-app/pom.xml
  catalog/spatial/spatial-app/src/main/resources/features.xml
  catalog/spatial/spatial-commands/src/main/java/org/codice/ddf/commands/spatial/gazetteer/GazetteerUpdateCommand.java
  distribution/ddf-common/src/main/resources/security/default.policy
  distribution/docs/src/main/resources/content/_reference/_appReferences/mg-spatial.adoc
  ui/packages/spatial-geocoding-admin-module/Gruntfile.js
  ui/packages/spatial-geocoding-admin-module/package.json
  ui/packages/spatial-geocoding-admin-module/src/main/resources/index.html
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/css/DroidSans.woff
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/css/DroidSansBold.woff
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/css/fonts.css
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/css/index.css
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/js/HandlebarsHelpers.js
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/js/application.js
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/js/ich.js
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/js/model/Ingest.js
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/js/module.js
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/js/view/Ingest.view.js
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/js/view/IngestUploadList.view.js
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/js/view/IngestUploadListItem.view.js
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/main.js
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/templates/ingestNewFileRow.handlebars
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/templates/ingestPage.handlebars
  ui/packages/spatial-geocoding-admin-module/src/test/tests.js
  ui/pom.xml
Labels: 👤 UI

#4044 [2.13.x] DDF-4337: Disable Hazelcast Port 5701 by Default
  distribution/ddf-common/src/main/resources/etc/hazelcast.xml
Labels: 🏬 Release Branch

#3999 DDF-4307 fix 'All Sources' behavior in sources drop down
  ui/packages/catalog-ui-search/src/main/webapp/component/query-src/query-src.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/query-src/query-src.less
  ui/packages/catalog-ui-search/src/main/webapp/component/query-src/query-src.view.js
Labels: 👞Bug Fix, 👤 UI

#4033 DDF-4294 Added confirmation/error message when saving a new Result Form
  ui/packages/catalog-ui-search/src/main/webapp/component/announcement/actions.js
  ui/packages/catalog-ui-search/src/main/webapp/component/announcement/announcements.jsx
  ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.collection.less
  ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js
Labels: ✨New Feature, 👤 UI

#3933 DDF-4268 Switches ui test runner to headless chrome
  ui/packages/ace/lib/test.js
  ui/packages/ace/package.json
  ui/yarn.lock
Labels: 👤 UI, 🛡️On Hold

#4042 [2.13.x] DDF-4297 Fix camel S3 connection with changes in Camel 2.22
  catalog/plugin/catalog-plugin-metacardbackup-s3storage/pom.xml
  catalog/plugin/catalog-plugin-metacardbackup-s3storage/src/main/java/org/codice/ddf/catalog/plugin/metacard/backup/storage/s3storage/MetacardS3StorageRoute.java
  catalog/plugin/catalog-plugin-metacardbackup-s3storage/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/plugin/catalog-plugin-metacardbackup-s3storage/src/main/resources/OSGI-INF/metatype/metatype.xml
  catalog/plugin/catalog-plugin-metacardbackup-s3storage/src/test/java/org/codice/ddf/catalog/plugin/metacard/backup/storage/s3storage/MetacardBackupS3StorageTest.java
Labels: 🏬 Release Branch

#4052 DDF-3811 Pulled embedded query metacards out of their workspace metacard
  catalog/ui/catalog-ui-search/pom.xml
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/QueryMetacardImpl.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/QueryMetacardTypeImpl.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/WorkspaceAttributes.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/WorkspaceMetacardImpl.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/transformer/impl/AssociatedQueryMetacardsHandler.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/transformer/impl/EmbeddedQueryMetacardsHandler.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/transformer/impl/QueryIdsParser.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/monitor/api/WorkspaceService.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/monitor/impl/WorkspaceServiceImpl.java
  catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/metacard/workspace/WorkspaceMetacardImplTest.java
  catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/metacard/workspace/transformer/impl/AssociatedQueryMetacardsHandlerTest.java
  catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/query/monitor/impl/WorkspaceServiceImplTest.java
  distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalogSearchUi.java
  ui/packages/catalog-ui-search/src/main/webapp/component/content/content.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-interactions/query-interactions.view.js
  ui/packages/catalog-ui-search/src/main/webapp/js/extensions/backbone.partialAssociatedModel.js
  ui/packages/catalog-ui-search/src/main/webapp/js/extensions/backbone.partialAssociatedModel.spec.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/Workspace.js
  ui/packages/catalog-ui-search/src/main/webapp/js/properties.js
  ui/packages/catalog-ui-search/src/main/webapp/plugins/properties.js
Labels: 👤 UI, 🔨Refactor

#4020 DDF-4325 Allow the user to set their home location for 2D and 3D maps
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/map.cesium.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/User.js
Labels: ✨New Feature, 👤 UI

#4032 DDF-4334 Add Support for Federated Sources in Table Export
  catalog/ui/catalog-ui-search/pom.xml
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/CqlRequest.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/util/EndpointUtil.java
  catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/query/cql/CqlRequestTest.java
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/table-export/table-export.tsx
Labels: ✨New Feature, 👤 UI

#4006 [2.13.x] DDF-4300 UI fix for advanced queries when anyText input is blank
  ui/packages/catalog-ui-search/src/main/webapp/component/filter-builder/filter-builder.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/input/input.less
  ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js
Labels: 🏬 Release Branch, 👞Bug Fix, 👤 UI

#4056 DDF-4345 updated documentation for filtering errors and warnings
  distribution/docs/src/main/resources/content/_configuring/hiding-errors-by-role.adoc
  distribution/docs/src/main/resources/content/_introduction/documentation-notes.adoc
Labels: :book: Documentation, 🏬 Release Branch

#4066 [2.13.x] DDF-4352 fix GzipFilter add async-supported=true
  catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-schema-webapp/src/main/resources/WEB-INF/web.xml
  catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/ui/search-ui/search-redirect/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/ui/search-ui/simple/src/main/webapp/WEB-INF/web.xml
  platform/admin/core/admin-core-jolokia/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  platform/admin/modules/admin-modules-docs/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  platform/security/idp/security-idp-server/src/main/webapp/WEB-INF/web.xml
  platform/security/servlet/security-servlet-logout/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  platform/security/servlet/security-servlet-whoami/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  platform/solr/platform-solr-server-standalone/src/main/webapp/WEB-INF/web.xml
  ui/packages/ace/lib/package.js
  ui/packages/security-idp-server/src/main/webapp/WEB-INF/web.xml
  ui/src/main/resources/WEB-INF/web.xml
Labels: 🏬 Release Branch, 👞Bug Fix

#4071 DDF-4347 Allow Confluence to query anonymous content
  catalog/confluence/catalog-confluence-source/src/main/java/org/codice/ddf/confluence/source/ConfluenceInputTransformer.java
  catalog/confluence/catalog-confluence-source/src/test/java/org/codice/ddf/confluence/source/ConfluenceInputTransformerTest.java
  catalog/confluence/catalog-confluence-source/src/test/resources/anonymous_user_response.json
Labels: 📈 Improvement

#4072 DDF-4352 fix GzipFilter issue add async-support=true param
  catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/ui/search-ui/search-redirect/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/ui/search-ui/simple/src/main/webapp/WEB-INF/web.xml
  platform/admin/core/admin-core-jolokia/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  platform/admin/modules/admin-modules-docs/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  platform/security/idp/security-idp-server/src/main/webapp/WEB-INF/web.xml
  platform/security/servlet/security-servlet-logout/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  platform/security/servlet/security-servlet-whoami/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  ui/packages/ace/lib/package.js
  ui/packages/security-idp-server/src/main/webapp/WEB-INF/web.xml
  ui/src/main/resources/WEB-INF/web.xml
Labels: 👞Bug Fix

#3995 DDF-4301 anyGeo BBox - upper-left northing field not cleared when switching shape tabs
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js
Labels: 👞Bug Fix, 👤 UI

#4058 [2.13.x] DDF-4311 Remove gazetteer UI component, and allow URLs in the CLI
  catalog/spatial/geocoding/pom.xml
  catalog/spatial/geocoding/spatial-geocoding-admin-module/README.md
  catalog/spatial/geocoding/spatial-geocoding-admin-module/pom.xml
  catalog/spatial/geocoding/spatial-geocoding-admin-module/src/main/java/org/codice/ddf/spatial/admin/module/GeocodingModulePlugin.java
  catalog/spatial/geocoding/spatial-geocoding-admin-module/src/main/java/org/codice/ddf/spatial/admin/module/service/Geocoding.java
  catalog/spatial/geocoding/spatial-geocoding-admin-module/src/main/java/org/codice/ddf/spatial/admin/module/service/GeocodingMBean.java
  catalog/spatial/geocoding/spatial-geocoding-admin-module/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/spatial/geocoding/spatial-geocoding-admin-module/src/test/java/org/codice/ddf/spatial/admin/module/GeocodingMbeanTest.java
  catalog/spatial/geocoding/spatial-geocoding-extract/pom.xml
  catalog/spatial/geocoding/spatial-geocoding-extract/src/main/java/org/codice/ddf/spatial/geocoding/extract/GeoNamesFileExtractor.java
  catalog/spatial/geocoding/spatial-geocoding-extract/src/test/java/org/codice/ddf/spatial/geocoding/extract/GeoNamesFileExtractorTest.java
  catalog/spatial/geocoding/spatial-geocoding-offline-catalog/src/main/java/org/codice/ddf/spatial/geocoding/index/GeoNamesCatalogIndexer.java
  catalog/spatial/geocoding/spatial-geocoding-offline-catalog/src/main/java/org/codice/ddf/spatial/geocoding/index/IndexInitializer.java
  catalog/spatial/spatial-app/pom.xml
  catalog/spatial/spatial-app/src/main/resources/features.xml
  catalog/spatial/spatial-commands/src/main/java/org/codice/ddf/commands/spatial/gazetteer/GazetteerUpdateCommand.java
  distribution/ddf-common/src/main/resources/security/default.policy
  distribution/docs/src/main/resources/content/_appReferences/mg-spatial.adoc
  platform/security/pdp/security-pdp-authzrealm/pom.xml
  pom.xml
  ui/packages/spatial-geocoding-admin-module/Gruntfile.js
  ui/packages/spatial-geocoding-admin-module/package.json
  ui/packages/spatial-geocoding-admin-module/src/main/resources/index.html
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/css/DroidSans.woff
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/css/DroidSansBold.woff
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/css/fonts.css
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/css/index.css
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/js/HandlebarsHelpers.js
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/js/application.js
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/js/ich.js
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/js/model/Ingest.js
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/js/module.js
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/js/view/Ingest.view.js
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/js/view/IngestUploadList.view.js
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/js/view/IngestUploadListItem.view.js
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/main.js
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/templates/ingestNewFileRow.handlebars
  ui/packages/spatial-geocoding-admin-module/src/main/webapp/templates/ingestPage.handlebars
  ui/packages/spatial-geocoding-admin-module/src/test/tests.js
  ui/pom.xml
Labels: 🏬 Release Branch, 👤 UI

#4010 DDF-3955 DDF itest configuration cleanup
  distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/catalog/CatalogTestCommons.java
  distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/config/ConfigureTestCommons.java
  distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
  distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalogValidation.java
  distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFanout.java
  distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSecurityAuditPlugin.java
  distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSpatial.java
  distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSecurity.java
Labels: 🌊Impacts Downstream, 🔨Refactor

#4067 DDF-4345 updated documentation for filtering errors and warnings
  distribution/docs/src/main/resources/content/_introduction/documentation-notes.adoc
  distribution/docs/src/main/resources/content/_managing/_configuring/hiding-errors-by-role.adoc
Labels: :book: Documentation

#4069 [2.13.x] DDF-4349 Make documentation table elements scroll at max-width
  distribution/docs/src/main/resources/content/scripts.html
Labels: :book: Documentation, 🏬 Release Branch, 👞Bug Fix, 👤 UI

#4070 DDF-4300 UI fix for advanced queries when anyText input is blank
  ui/packages/catalog-ui-search/src/main/webapp/component/filter-builder/filter-builder.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js
Labels: 👤 UI, 📈 Improvement

#4073 [2.13.x] DDF-4223 Updated AC debugger to the latest version
  distribution/ddf-common/src/main/resources/security/default.policy
  pom.xml
Labels: 🏬 Release Branch

#4055 DDF-4343 Simplify CI workspace name and perform post-build cleanup
  Jenkinsfile
Labels: 👷‍♀️Build, 📈 Improvement

#4053 DDF-4338 added icon to visually identify external links in docs
  distribution/docs/src/main/resources/content/_appReferences/mg-broker-app.adoc
  distribution/docs/src/main/resources/content/_appReferences/mg-geowebcache.adoc
  distribution/docs/src/main/resources/content/_appReferences/mg-platform.adoc
  distribution/docs/src/main/resources/content/_architectures/filter-intro.adoc
  distribution/docs/src/main/resources/content/_configuring/connecting-to-external-idp.adoc
  distribution/docs/src/main/resources/content/_configuring/decanter-services.adoc
  distribution/docs/src/main/resources/content/_coreConcepts/attribute-stores.adoc
  distribution/docs/src/main/resources/content/_coreConcepts/authentication-standards.adoc
  distribution/docs/src/main/resources/content/_coreConcepts/cryptography-standards.adoc
  distribution/docs/src/main/resources/content/_coreConcepts/data-standards.adoc
  distribution/docs/src/main/resources/content/_coreConcepts/map-standards.adoc
  distribution/docs/src/main/resources/content/_coreConcepts/security-sso-endpoints.adoc
  distribution/docs/src/main/resources/content/_coreConcepts/service-standards.adoc
  distribution/docs/src/main/resources/content/_coreConcepts/sso-standards.adoc
  distribution/docs/src/main/resources/content/_coreConcepts/transport-protocols.adoc
  distribution/docs/src/main/resources/content/_data/json-definition-intro.adoc
  distribution/docs/src/main/resources/content/_devComponents/assuring-bundles-and-apps.adoc
  distribution/docs/src/main/resources/content/_devComponents/custom-endpoints.adoc
  distribution/docs/src/main/resources/content/_devComponents/custom-filters.adoc
  distribution/docs/src/main/resources/content/_devComponents/custom-resource-readers.adoc
  distribution/docs/src/main/resources/content/_devComponents/custom-sources.adoc
  distribution/docs/src/main/resources/content/_devComponents/editing-docs.adoc
  distribution/docs/src/main/resources/content/_devComponents/filter-delegates.adoc
  distribution/docs/src/main/resources/content/_devGuidelines/contributing-intro.adoc
  distribution/docs/src/main/resources/content/_devGuidelines/osgi-basics.adoc
  distribution/docs/src/main/resources/content/_endpoints/catalog-rest-endpoint.adoc
  distribution/docs/src/main/resources/content/_endpoints/cometd-endpoint.adoc
  distribution/docs/src/main/resources/content/_endpoints/compression-services.adoc
  distribution/docs/src/main/resources/content/_endpoints/csw-endpoint.adoc
  distribution/docs/src/main/resources/content/_endpoints/ftp-endpoint.adoc
  distribution/docs/src/main/resources/content/_endpoints/kml-endpoint.adoc
  distribution/docs/src/main/resources/content/_endpoints/opensearch-endpoint.adoc
  distribution/docs/src/main/resources/content/_installing/high-availability-initial-setup-exceptions.adoc
  distribution/docs/src/main/resources/content/_installing/java-reqs.adoc
  distribution/docs/src/main/resources/content/_introduction/applications.adoc
  distribution/docs/src/main/resources/content/_introduction/developing-intro.adoc
  distribution/docs/src/main/resources/content/_introduction/documentation-notes.adoc
  distribution/docs/src/main/resources/content/_introduction/introduction.adoc
  distribution/docs/src/main/resources/content/_metadataAttributes/associations-attributes-table.adoc
  distribution/docs/src/main/resources/content/_metadataAttributes/core-attributes-table.adoc
  distribution/docs/src/main/resources/content/_metadataAttributes/media-attributes-table.adoc
  distribution/docs/src/main/resources/content/_quickstart/quickstart-ingesting.adoc
  distribution/docs/src/main/resources/content/_quickstart/quickstart-installing.adoc
  distribution/docs/src/main/resources/content/_running/available-console-commands.adoc
  distribution/docs/src/main/resources/content/_running/cql-syntax.adoc
  distribution/docs/src/main/resources/content/_running/ddf-service.adoc
  distribution/docs/src/main/resources/content/_running/external-ingest.adoc
  distribution/docs/src/main/resources/content/_running/monitoring.adoc
  distribution/docs/src/main/resources/content/_running/troubleshooting.adoc
  distribution/docs/src/main/resources/content/_securing/auditing.adoc
  distribution/docs/src/main/resources/content/_securityFramework/security-encryption-intro.adoc
  distribution/docs/src/main/resources/content/_securityFramework/security-ldap-embedded-server.adoc
  distribution/docs/src/main/resources/content/_securityServices/security-idp-intro.adoc
  distribution/docs/src/main/resources/content/_sources/gmd-csw-source.adoc
  distribution/docs/src/main/resources/content/_tables/catalog.ui.config.adoc
  distribution/docs/src/main/resources/content/_transformers/atom-queryresp-xformer.adoc
  distribution/docs/src/main/resources/content/_transformers/kml-style-mapper.adoc
  distribution/docs/src/main/resources/content/config.adoc
  distribution/docs/src/main/resources/images/external-link.png
Labels: :book: Documentation, 📈 Improvement

#4054 DDF-4342 Add 'Between' temporal option to the advanced search builder
  ui/packages/catalog-ui-search/src/main/webapp/component/between-time/between-time.less
  ui/packages/catalog-ui-search/src/main/webapp/component/between-time/between-time.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/filter-comparator/filter-comparator.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-time/query-time.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/query-time/query-time.view.js
  ui/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.js
  ui/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.spec.js
  ui/packages/catalog-ui-search/src/main/webapp/js/filter.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/input-wrappers/date/date.tsx
Labels: ✨New Feature, 👤 UI

#4078 DDF-4362: Adds configurable, hyphenated uuid generation in web ui
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java
  catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/config/ConfigurationApplicationTest.java
  platform/util/platform-util-uuidgenerator/util-uuidgenerator-api/src/main/java/org/codice/ddf/platform/util/uuidgenerator/UuidGenerator.java
  platform/util/platform-util-uuidgenerator/util-uuidgenerator-impl/src/main/java/org/codice/ddf/platform/util/uuidgenerator/impl/UuidGeneratorImpl.java
  platform/util/platform-util-uuidgenerator/util-uuidgenerator-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  platform/util/platform-util-uuidgenerator/util-uuidgenerator-impl/src/main/resources/OSGI-INF/metatype/metatype.xml
  platform/util/platform-util-uuidgenerator/util-uuidgenerator-impl/src/test/java/org/codice/ddf/platform/util/uuidgenerator/impl/UuidGeneratorImplTest.java
  ui/packages/catalog-ui-search/src/main/webapp/js/Common.js
  ui/packages/catalog-ui-search/src/main/webapp/js/Common.spec.js
  ui/packages/catalog-ui-search/src/main/webapp/js/properties.js
Labels: 👤 UI

#4075 DDF-4357 Select the first item in menus when opened
  ui/packages/catalog-ui-search/src/main/webapp/react-component/menu/menu.js
Labels: 👤 UI, 📈 Improvement
