Repository codice/ddf, pull requests merged in 2019-05, with the labels that each got.

#4646 DDF-4644 Add support for temporal queries to WFS 1.1.0 source
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/pom.xml
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegate.java
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegateTest.java
Labels: ✨New Feature

#4649 DDF-4648 Update WFS 1.1 bounding box to be GML 3.1.1 compliant
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegate.java
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegateTest.java
Labels: 📈 Improvement

#4651 DDF-4650 Add matchCase support to WFS 1.1 filter delegate
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegate.java
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegateTest.java
Labels: ✨New Feature, 📈 Improvement

#4784 [2.13.x] DDF-2824 fixed external link icon typo
  distribution/docs/src/main/resources/content/_installing/install-with-zip.adoc
  distribution/docs/src/main/resources/content/_introduction/integrating-intro.adoc
  distribution/docs/src/main/resources/content/_quickstart/quickstart-installing.adoc
Labels: :book: Documentation, 🏬 Release Branch, 👞Bug Fix

#4783 [2.13.x] DDF-4782 updated quick start installation instructions
  distribution/docs/src/main/resources/content/_quickstart/quickstart-installing.adoc
Labels: :book: Documentation, docs-content, 🏬 Release Branch, 👞Bug Fix

#4654 DDF-4652 Add coordinate order handling to HandlebarsWfsFeatureTransfo…
  catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/pom.xml
  catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/src/main/java/org/codice/ddf/spatial/ogc/wfs/transformer/handlebars/CoordinateOrderTransformer.java
  catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/src/main/java/org/codice/ddf/spatial/ogc/wfs/transformer/handlebars/HandlebarsWfsFeatureTransformer.java
  catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/src/main/resources/OSGI-INF/metatype/metatype.xml
  catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/src/test/java/org/codice/ddf/spatial/ogc/wfs/transformer/handlebars/HandlebarsWfsFeatureTransformerTest.java
  catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/src/test/resources/FeatureMemberPolygon.xml
Labels: 📈 Improvement

#4776 DDF-4668 Fix Server Side Paging Indices
  ui/packages/catalog-ui-search/src/main/webapp/component/paging/paging.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.less
  ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResponse.js
Labels: 👞Bug Fix, 👤 UI

#4777 DDF-04410, MapSettings components unit tests with network calls mocking.
  ui/packages/catalog-ui-search/package.json
  ui/packages/catalog-ui-search/src/main/webapp/js/ApplicationStart.js
  ui/packages/catalog-ui-search/src/main/webapp/js/OpenLayersGeometryUtils.spec.js
  ui/packages/catalog-ui-search/src/main/webapp/js/properties.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/map-settings/map-settings.spec.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/map-settings/map-settings.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/map-settings/map-settings.spec.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/map-settings/map-settings.tsx
  ui/packages/catalog-ui-search/src/main/webapp/test/mock-api/config.json
  ui/packages/catalog-ui-search/src/main/webapp/test/mock-api/datatype.json
  ui/packages/catalog-ui-search/src/main/webapp/test/mock-api/enumerations.json
  ui/packages/catalog-ui-search/src/main/webapp/test/mock-api/index.js
  ui/packages/catalog-ui-search/src/main/webapp/test/mock-api/metacardtype.json
  ui/packages/catalog-ui-search/src/main/webapp/test/mock-api/mock-jquery.js
  ui/packages/catalog-ui-search/src/main/webapp/test/mock-api/mock-properties.js
  ui/packages/catalog-ui-search/src/main/webapp/test/mock-api/platform.json
  ui/packages/catalog-ui-search/src/main/webapp/test/mock-api/sources.json
  ui/yarn.lock
Labels: 👤 UI

#4778 DDF-04774 Session timeout dialog goes into negatives
  ui/packages/catalog-ui-search/src/main/webapp/component/component.less
  ui/packages/catalog-ui-search/src/main/webapp/component/session-timeout/session-timeout.less
  ui/packages/catalog-ui-search/src/main/webapp/component/session-timeout/session-timeout.view.js
  ui/packages/catalog-ui-search/src/main/webapp/js/SessionTimeout.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/session-timeout/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/session-timeout/session-timeout.tsx
Labels: 👞Bug Fix, 👤 UI

#4664 DDF-4659 Make HandlebarsWfsFeatureTransformer handle XML attributes
  catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/pom.xml
  catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/src/main/java/org/codice/ddf/spatial/ogc/wfs/transformer/handlebars/HandlebarsWfsFeatureTransformer.java
  catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/src/main/resources/OSGI-INF/metatype/metatype.xml
  catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/src/test/java/org/codice/ddf/spatial/ogc/wfs/transformer/handlebars/HandlebarsWfsFeatureTransformerTest.java
  catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/src/test/resources/FeatureMember.xml
Labels: 📈 Improvement

#4803 DDF-04410 Ensures UI properties are initialized before first usage
  ui/packages/catalog-ui-search/src/main/webapp/js/ApplicationStart.js
  ui/packages/catalog-ui-search/src/main/webapp/js/Entry.tsx
Labels: 👤 UI

#4799 DDF-4798 Add indications that user is actively trying to login
  ui/packages/security-idp-server/src/main/resources/templates/login.handlebars
  ui/packages/security-idp-server/src/main/webapp/js/view/Login.view.js
Labels: 👤 UI

#4677 DDF-4675 - Add type extend support definitions
  .github/CODEOWNERS
  catalog/catalog-app/pom.xml
  catalog/catalog-app/src/main/resources/features.xml
  catalog/core/catalog-core-definitionparser/pom.xml
  catalog/core/catalog-core-definitionparser/src/main/java/ddf/catalog/definition/impl/DefinitionParser.java
  catalog/core/catalog-core-definitionparser/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/core/catalog-core-definitionparser/src/test/groovy/ddf/catalog/definition/impl/DefinitionParserSpec.groovy
  catalog/core/pom.xml
  distribution/ddf-common/src/main/resources/etc/profiles/ha.json
  distribution/docs/src/main/resources/content/_developing/_devComponents/metacard-type.adoc
Labels: 📈 Improvement

#4764 DDF-04318 (with bug fix) Check that the user is logged in for every Intrigue WebSocket request
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/ws/JsonRpc.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/ws/SecureWebSocketServlet.java
  ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResponse.js
Labels: 👤 UI

#4793 DDF-4782 updated quick start installation instructions
  distribution/docs/src/main/resources/content/_quickstart/quickstart-installing.adoc
Labels: :book: Documentation, docs-content, 👞Bug Fix

#4835 DDF-04834 Make Geos load in search form editor
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js
Labels: 👤 UI

#4819 DDF-04817,04823 Update search form in workspaces when default search form is changed or edited
  ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js
Labels: 👤 UI

#4787 DDF-4763 Give Google like results in the results view when a query is fixed by spellchecked
  catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java
  catalog/core/catalog-core-tagsfilterplugin/src/main/java/org/codice/ddf/catalog/plugin/tagsfilter/TagsFilterQueryPlugin.java
  catalog/core/catalog-core-tagsfilterplugin/src/test/java/org/codice/ddf/catalog/plugin/tagsfilter/TagsFilterQueryPluginTest.java
  catalog/plugin/catalog-plugin-metacard-validation/src/main/java/ddf/catalog/metacard/validation/MetacardValidityFilterPlugin.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/CqlQueryResponse.java
  ui/packages/catalog-ui-search/src/main/webapp/component/result-item/result-item.collection.tsx
  ui/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.view.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResponse.js
Labels: 👤 UI

#4809 DDF-4808 fix A new list is not created from the drop down when the action is selected
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/list-create/list-create.js
Labels: 👤 UI

#4849 DDF-04804: Provide an extension point for visualizations in Intrigue
  ui/packages/catalog-ui-search/package.json
  ui/packages/catalog-ui-search/src/main/webapp/component/golden-layout/golden-layout.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/visualization.view.js
  ui/packages/catalog-ui-search/src/main/webapp/extension-points/extension-points.tsx
  ui/packages/catalog-ui-search/src/main/webapp/extension-points/visualizations/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/js/Entry.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/visualization-selector/visualization-selector.js
Labels: 👤 UI

#4843 DDF-04842 Migrate menu.tsx to styled and parameterize dropdown.js anchor component
  ui/packages/catalog-ui-search/src/main/webapp/react-component/dropdown/dropdown.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/menu/menu.less
  ui/packages/catalog-ui-search/src/main/webapp/react-component/menu/menu.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/react-component.less
Labels: 👤 UI

#4775 DDF-04374 removed kml endpoint docs from integrator docs.
  distribution/docs/src/main/resources/content/_integrating/_endpoints/kml-endpoint.adoc
  distribution/docs/src/main/resources/content/_integrating/_endpoints/other-endpoints-intro.adoc
Labels: :book: Documentation, Integrator Docs Rewrite, docs-content

#4854 DDF-4845 Adding a Did you mean re-query option in Results Panel
  catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/CqlQueryResponse.java
  ui/packages/catalog-ui-search/src/main/webapp/component/result-item/result-item.collection.tsx
  ui/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.view.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResponse.js
Labels: 👤 UI

#4886 Update Pull Request Template to remove Ethan Manns
  .github/PULL_REQUEST_TEMPLATE
Labels: Meta
