Repository codice/ddf, pull requests merged in 2019-02, with the labels that each got.

#4278 DDF-4485 Adhoc workspace title is the search query text
  ui/packages/catalog-ui-search/src/main/webapp/js/model/Workspace.collection.js
Labels: 👤 UI

#4103 [2.13.x] DDF-4378 Making store:list options consistent across --help and -t
  platform/persistence/platform-persistence-commands/src/main/java/org/codice/ddf/persistence/commands/AbstractStoreCommand.java
Labels: Needs Rebase

#4298 DDF-04297 Refactoring location dropdown
  ui/packages/catalog-ui-search/src/main/webapp/react-component/location/location.js
Labels: 👤 UI, 📈 Improvement

#4312 DDF-04288 Fix MenuItem overlap in the Intrigue location dropdown
  ui/packages/catalog-ui-search/src/main/webapp/react-component/menu/menu.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/menu/menu.less
Labels: 👞Bug Fix, 👤 UI

#4311 DDF-04295 Reorder documentation for URL Resource Reader to match CDMs layout
  distribution/docs/src/main/resources/content/_architectures/_resources/url-resource-reader.adoc
Labels: :book: Documentation

#4265 DDF-04262 Add the ability to set a default list
  ui/packages/catalog-ui-search/src/main/webapp/component/list-interactions/list-interactions.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/list-interactions/list-interactions.less
  ui/packages/catalog-ui-search/src/main/webapp/component/list-interactions/list-interactions.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/list-item/list-item.collection.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/list-item/list-item.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/list-item/list-item.less
  ui/packages/catalog-ui-search/src/main/webapp/component/list-item/list-item.view.js
Labels: ✨New Feature, 👤 UI

#4252 DDF-4460 Display name for metacard and query response transformers in UI
  catalog/spatial/csw/spatial-csw-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/spatial/kml/spatial-kml-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/transformer/catalog-transformer-csv-queryresponse/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/transformer/catalog-transformer-geojson-metacard/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/transformer/catalog-transformer-geojson-queryresponse/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/transformer/catalog-transformer-html/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/transformer/catalog-transformer-metadata/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/transformer/catalog-transformer-overlay/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/transformer/catalog-transformer-preview/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/transformer/catalog-transformer-propertyjson-metacard/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/transformer/catalog-transformer-resource/src/main/resources/OSGI-INF/blueprint/metacardTransformer.xml
  catalog/transformer/catalog-transformer-rtf/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/transformer/catalog-transformer-service-atom/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/transformer/catalog-transformer-thumbnail/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/transformer/catalog-transformer-xml/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/transformer/catalog-transformer-zip/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/ui/catalog-ui-search/pom.xml
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/QueryApplication.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/CqlQueryResponse.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/CqlResult.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/DisplayableAction.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/transformer/TransformerDescriptorApplication.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/transformer/TransformerDescriptors.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/util/EndpointUtil.java
  catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/transformer/TransformerDescriptorsTest.java
  catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/util/EndpointUtilTest.java
  distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalogSearchUi.java
  ui/packages/catalog-ui-search/src/main/webapp/dev/component/card-guide/card-guide.view.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/MetacardAction.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/table-export/table-export.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/export/export.tsx
Labels: 👤 UI

#4243 DDF-4474 Made right navigation bar extensible
  ui/packages/catalog-ui-search/src/main/webapp/plugins/navigation-right.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/navigation-right/navigation-right.tsx
Labels: 👤 UI, 📈 Improvement

#4247 DDF-4475 Add additional extensibility to result item
  ui/packages/catalog-ui-search/src/main/webapp/component/result-item/result-item.less
  ui/packages/catalog-ui-search/src/main/webapp/component/result-item/result-item.view.js
Labels: 👤 UI, 📈 Improvement

#4322 DDF-04320 Force Camel's quartz component to use newer version of c3p0
  features/camel/src/main/feature/feature.xml
  features/pom.xml
  platform/admin/core/admin-core-insecuredefaults/pom.xml
Labels: ⬆️ Dependency Upgrade

#4326 DDF-04282 moved eventing content from integrating to architecture docs
  distribution/docs/src/main/resources/content/_architectures/_eventing/eventing-intro.adoc
  distribution/docs/src/main/resources/content/_integrating/_eventing/subscriptions.adoc
  distribution/docs/src/main/resources/content/_managing/_installing/firewall-config.adoc
  distribution/docs/src/main/resources/content/_managing/_installing/ie11-configuration.adoc
  distribution/docs/src/main/resources/content/_managing/_installing/installing-from-admin-console.adoc
  distribution/docs/src/main/resources/content/_managing/_installing/installing-from-the-command-line.adoc
  distribution/docs/src/main/resources/templates/build/developing.ftl
  distribution/docs/src/main/resources/templates/build/eventing.ftl
  distribution/docs/src/main/resources/templates/build/integrating.ftl
Labels: :book: Documentation

#4233 DDF-4447 Patching metacards directly over HTTP should consider the context of sharing attribute changes
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/AccessControlAccessPlugin.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/AccessControlPreIngestPlugin.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/AccessControlUtil.java
  catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/AccessControlAccessPluginTest.java
  catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/AccessControlPolicyPluginTest.java
  catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/AccessControlUtilTest.java
  catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/AclTestSupport.java
  catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/AclTestSupportTest.java
Labels: 👞Bug Fix

#4302 DDF-04301 Add support for preQueryPlugin to be async
  ui/packages/catalog-ui-search/src/main/webapp/js/QueryPolling.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js
Labels: 👤 UI

#4327 DDF-04288 Removes title from menu.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/menu/menu.js
Labels: 👞Bug Fix, 👤 UI

#4271 DDF-04261 Optimize MetacardTypeImpl getAttributeDescriptor
  catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/MetacardTypeImpl.java
  catalog/core/catalog-core-attributeregistry/pom.xml
  catalog/spatial/kml/spatial-kml-transformer/src/test/java/org/codice/ddf/spatial/kml/transformer/MockMetacardType.java
  catalog/spatial/registry/registry-common/src/main/java/org/codice/ddf/registry/common/metacard/RegistryObjectMetacardType.java
  catalog/spatial/wfs/spatial-wfs-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/common/FeatureMetacardType.java
  catalog/transformer/catalog-transformer-common/src/main/java/ddf/catalog/transformer/common/tika/Mp4MetacardType.java
Labels: 🌊Impacts Downstream, 📈 Improvement

#4319 [2.13.x] DDF-04316 Add better logging for failed automatic logout
  platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/LogoutRequestService.java
  ui/packages/security-servlet-logout/src/main/resources/logout-response.html
Labels: :lock: Security, 🏬 Release Branch, 👞Bug Fix

#4341 [2.13.x] DDF-4472 Overriding blueprint aries version to fix an implementation default bug
  distribution/ddf-common/src/main/resources/etc/org.apache.karaf.features.xml
Labels: 🏬 Release Branch

#4235 DDF-4450 Patching metacards directly over HTTP results in an NPE when the metacard to be patched does not exist
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java
  catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/metacard/MetacardApplicationTest.java
Labels: 👞Bug Fix

#4237 DDF-4471 Disabling sources sometimes causes them to disappear from the sources tab in the Admin UI
  catalog/spatial/registry/registry-source-configuration-handler/src/main/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandler.java
  platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/ConfigurationAdminImpl.java
  platform/admin/core/admin-core-impl/src/test/java/org/codice/ddf/admin/core/impl/ConfigurationAdminImplTest.java
Labels: 👞Bug Fix

#4337 DDF-04336 Migrate result-sort to React
  ui/packages/catalog-ui-search/src/main/webapp/component/component.less
  ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/result-sort/dropdown.result-sort.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/result-sort/result-sort.less
  ui/packages/catalog-ui-search/src/main/webapp/component/result-sort/result-sort.view.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/result-sort/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/result-sort/result-sort.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/result-sort/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/result-sort/result-sort.tsx
Labels: 👤 UI, 📈 Improvement

#4352 [2.13.x]DDF-04351 Suppress Karaf's XXE vulnerability
  dependency-check-maven-config.xml
Labels: ⬆️ Dependency Upgrade

#4325 [2.13.x]DDF-04318 Check that the user is logged in for every Intrigue WebSocket request
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/QueryApplication.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/ws/JsonRpc.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/ws/SecureWebSocketServlet.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/ws/WebSocketAuthenticationException.java
  ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResponse.js
Labels: :lock: Security, 🏬 Release Branch, 👞Bug Fix

#4340 DDF-04338 Adds space around the map actions / buttons
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.less
Labels: 👤 UI, 📈 Improvement

#4329 DDF-04282 refactored security services docs
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/external-ws-s-sts-support.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/federated-identity.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/guest-interceptor.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/realms.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-core-api.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-core-commons.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-core-implementation.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-core-intro.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-encryption-api.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-encryption-commands.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-encryption-impl.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-encryption-intro.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-expansion-service.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-filtering.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-framework-intro.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-idp-intro.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-ldap-embedded-server.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-ldap-intro.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-manager.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-pdp-authz-realm.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-pdp-intro.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-pep-interceptor.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-pep-intro.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-rest-intro.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-soap-intro.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-sts-claims-handler.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-token-service.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-wss-intro.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/sts-client-config.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/sts-intro.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/sts-ldap-claims-handler.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/sts-ldap-login.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/sts-server.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/sts-service.adoc
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/subject.adoc
  distribution/docs/src/main/resources/content/_integrating/_securityServices/expansion-service.adoc
  distribution/docs/src/main/resources/content/_managing/_configuring/encryption-service.adoc
  distribution/docs/src/main/resources/content/_managing/_configuring/hardening-solr.adoc
  distribution/docs/src/main/resources/content/_managing/_configuring/ldap-server.adoc
  distribution/docs/src/main/resources/jbake.properties
  distribution/docs/src/main/resources/templates/build/integrating.ftl
  distribution/docs/src/main/resources/templates/build/security-framework.ftl
  distribution/docs/src/main/resources/templates/build/security-services.ftl
Labels: :book: Documentation

#4359 [2.13.x]DDF-4472 Fix aries.proxy startup issue
  distribution/kernel/pom.xml
Labels: 🏬 Release Branch, 👞Bug Fix

#4369 DDF-04367 Add documentation on shell command whitelist
  distribution/docs/src/main/resources/content/_managing/_configuring/environment-hardening.adoc
Labels: :book: Documentation, :lock: Security

#4362 DDF-04361 Empty the query extensions region when no extension is returned
  ui/packages/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.view.js
Labels: 👤 UI, 📈 Improvement

#4221 DDF-4451 3D Map Attempts to Fetch Hidden Layers on Initialization
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/map.cesium.js
  ui/packages/catalog-ui-search/src/main/webapp/js/controllers/cesium.layer-ordering.js
  ui/packages/catalog-ui-search/src/main/webapp/js/controllers/cesium.layer-ordering.spec.js
  ui/packages/catalog-ui-search/src/main/webapp/js/controllers/cesium.layerCollection.controller.js
Labels: 👤 UI, 📈 Improvement

#4254 DDF-4478 Improves filtering logic for dropdowns
  ui/packages/catalog-ui-search/src/main/webapp/component/select/filterHelper.js
  ui/packages/catalog-ui-search/src/main/webapp/component/select/filterHelper.spec.js
  ui/packages/catalog-ui-search/src/main/webapp/component/select/select.collection.view.js
Labels: 👤 UI, 📈 Improvement

#4314 DDF-04313 Renaming inconsistent WMTS references
  ui/packages/catalog-ui-search/src/main/webapp/js/controllers/ol.layerCollection.controller.js
Labels: 👤 UI, 📈 Improvement

#4250 [2.13.x] DDF-4472 Replacing the DescribableServiceMap with Java8 Streams /filters
  catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/DescribableServiceMap.java
  catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/MapConverter.java
  catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/FrameworkProperties.java
  catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/OperationsCatalogStoreSupport.java
  catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java
  catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/ResourceOperations.java
  catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/SourceOperations.java
  catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/frameworkprops.xml
  catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/sources.xml
  catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/OperationsCatalogStoreSupportSpec.groovy
  catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/QueryOperationsSpec.groovy
  catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/ResourceOperationsSpec.groovy
  catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/SourceOperationsSpec.groovy
  catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/CatalogFrameworkImplTest.java
  catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/FanoutCatalogFrameworkTest.java
Labels: 🏬 Release Branch, 👞Bug Fix

#4368 DDF-04318 Check that the user is logged in for every Intrigue WebSocket request
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/QueryApplication.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/ws/JsonRpc.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/ws/SecureWebSocketServlet.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/ws/WebSocketAuthenticationException.java
  ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResponse.js
Labels: :lock: Security, 👞Bug Fix

#4373 DDF-04372 Migrates webpack to use `MiniCssExtractPlugin`
  ui/packages/ace/lib/webpack.config.js
  ui/packages/ace/package.json
  ui/yarn.lock
Labels: 🌊Impacts Downstream, 👤 UI

#4309 DDF-04307 Migrating home and save home buttons to react
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.less
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/button/split-button/index.spec.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/button/split-button/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/button/split-button/zoomToHome.tsx
  ui/packages/catalog-ui-search/src/main/webapp/styles/mixins.less
Labels: 👤 UI

#4376 DDF-04375 Updates login page to autofocus
  ui/packages/security-idp-server/src/main/webapp/js/view/Login.view.js
Labels: 👤 UI

#4380 DDF-04379 Correct Typo in Documentation
  distribution/docs/src/main/resources/content/_managing/_running/solr-service.adoc
Labels: :book: Documentation

#4350 DDF-04349 Various CSW ingest and query performance updates
  catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/filter/impl/SortByImpl.java
  catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/operation/impl/QueryImpl.java
  catalog/rest/catalog-rest-impl/src/main/java/org/codice/ddf/rest/impl/action/MetacardTransformerActionProvider.java
  catalog/rest/catalog-rest-impl/src/test/java/org/codice/ddf/rest/impl/action/MetacardTransformerActionProviderTest.java
  libs/common-system/src/main/java/org/codice/ddf/configuration/SystemBaseUrl.java
Labels: 📈 Improvement

#4377 [2.13.x] DDF-04370 Fixed quartz2 feature dependency for DefaultUsersDeletionScheduler
  features/admin/src/main/feature/feature.xml
  features/camel/src/main/feature/feature.xml
Labels: ⬆️ Dependency Upgrade, 🏬 Release Branch

#4386 [2.13.x] DDF-04385 Fixing a bug where DDF fails to start if the user has an empty m2
  distribution/ddf-common/src/main/resources/common-bin.xml
Labels: 🏬 Release Branch, 👞Bug Fix

#4400 DDF-04399 Filtering out hidden attributes from Result Form
  ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.view.js
Labels: 👞Bug Fix, 👤 UI

#4405 DDF-04367 Add documentation on shell command whitelist (#4369)
  distribution/docs/src/main/resources/content/_configuring/environment-hardening.adoc
Labels: :book: Documentation

#4393 DDF-4472 Fixing a bug where DDF fails to start if the user has an empty M2
  distribution/ddf-common/src/main/resources/common-bin.xml
Labels: 👞Bug Fix

#4347 DDF-04346 - Preserving Original Query Structure For Advanced Queries
  ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.spec.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.view.js
  ui/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-interactions/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/location/keyword.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/location/location.js
Labels: 👤 UI, 📈 Improvement

#4396 DDF-4449 re-apply fix for intermittent save button appearing in search forms
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.collection.view.js
Labels: 👞Bug Fix, 👤 UI

#4391 DDF-04389 Fixes search options slideout not saving
  ui/packages/catalog-ui-search/src/main/webapp/component/slideout/slideout.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/slideout/slideout.view.js
Labels: 👞Bug Fix, 👤 UI

#4223 [2.13.x] DDF-4424 Updating the CDM File Directory (in-place) to update the observer state only on a successful ingest to the catalog framework
  catalog/catalog-app/src/main/resources/features.xml
  catalog/core/catalog-core-directorymonitor/pom.xml
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AbstractDurableFileConsumer.java
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AsyncFileAlterationListener.java
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AsyncFileAlterationObserver.java
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AsyncFileEntry.java
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileAlterationListener.java
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileSystemFileConsumer.java
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableWebDavFileConsumer.java
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/FileSystemPersistenceProvider.java
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/JsonPersistantStore.java
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ObjectPersistentStore.java
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/synchronizations/CompletionSynchronization.java
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/synchronizations/LoggingSynchronization.java
  catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/AsyncFileAlterationObserverTest.java
Labels: 🏬 Release Branch

#4382 DDF-04331 reformatted endpoints section of integrator docs
  distribution/docs/src/main/resources/content/_developing/_devComponents/custom-endpoints.adoc
  distribution/docs/src/main/resources/content/_integrating/_endpoints/_endpoint-template.adoc
  distribution/docs/src/main/resources/content/_integrating/_endpoints/application-endpoint.adoc
  distribution/docs/src/main/resources/content/_integrating/_endpoints/catalog-rest-endpoint.adoc
  distribution/docs/src/main/resources/content/_integrating/_endpoints/content-endpoints-intro.adoc
  distribution/docs/src/main/resources/content/_integrating/_endpoints/crud-endpoints-intro.adoc
  distribution/docs/src/main/resources/content/_integrating/_endpoints/csw-endpoint.adoc
  distribution/docs/src/main/resources/content/_integrating/_endpoints/endpoint-intro.adoc
  distribution/docs/src/main/resources/content/_integrating/_endpoints/endpoint-utilities-intro.adoc
  distribution/docs/src/main/resources/content/_integrating/_endpoints/endpoints-intro.adoc
  distribution/docs/src/main/resources/content/_integrating/_endpoints/ftp-endpoint.adoc
  distribution/docs/src/main/resources/content/_integrating/_endpoints/ingest-endpoints-intro.adoc
  distribution/docs/src/main/resources/content/_integrating/_endpoints/kml-endpoint.adoc
  distribution/docs/src/main/resources/content/_integrating/_endpoints/metrics-endpoint.adoc
  distribution/docs/src/main/resources/content/_integrating/_endpoints/opensearch-endpoint.adoc
  distribution/docs/src/main/resources/content/_integrating/_endpoints/other-endpoints-intro.adoc
  distribution/docs/src/main/resources/content/_integrating/_endpoints/pub-sub-endpoints-intro.adoc
  distribution/docs/src/main/resources/content/_integrating/_endpoints/query-endpoints-intro.adoc
  distribution/docs/src/main/resources/content/_integrating/_endpoints/wps-endpoint.adoc
  distribution/docs/src/main/resources/content/_integrating/integrating-intro.adoc
  distribution/docs/src/main/resources/content/_managing/_configuring/compression-services.adoc
  distribution/docs/src/main/resources/content/_managing/_configuring/configuring-catalog-rest-endpoint.adoc
  distribution/docs/src/main/resources/content/_managing/_configuring/configuring-csw-endpoint.adoc
  distribution/docs/src/main/resources/content/_managing/_configuring/configuring-endpoints.adoc
  distribution/docs/src/main/resources/content/_managing/_configuring/configuring-ftp-endpoint.adoc
  distribution/docs/src/main/resources/content/_managing/_configuring/configuring-kml-endpoint.adoc
  distribution/docs/src/main/resources/content/_managing/_configuring/configuring-opensearch-endpoint.adoc
  distribution/docs/src/main/resources/content/_managing/_configuring/configuring-wps-endpoint.adoc
  distribution/docs/src/main/resources/content/_managing/_running/other-ingest.adoc
  distribution/docs/src/main/resources/templates/build/configuring.ftl
  distribution/docs/src/main/resources/templates/build/endpoints.ftl
Labels: :book: Documentation, Integrator Docs Rewrite, docs-content

#4364 DDF-04363 Fixed off-by-one error for negative decimal coordinates in tooltip
  ui/packages/catalog-ui-search/src/main/webapp/component/map-info/map-info.view.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/left-pad/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/left-pad/left-pad.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/left-pad/leftpad.spec.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/wrap-num/wrap-num.spec.js
Labels: 👞Bug Fix, 👤 UI

#4281 DDF-4481 Add the IS EMPTY operator in search queries
  distribution/docs/src/main/resources/content/_using/using-catalog-search-ui.adoc
  ui/packages/catalog-ui-search/src/main/webapp/component/filter-comparator/filter-comparator.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/filter/comparators.tsx
  ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.less
  ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.less
  ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js
  ui/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.js
  ui/packages/catalog-ui-search/src/main/webapp/js/cql.js
Labels: 👤 UI

#4240 DDF-4465 Export metacards to a compressed file in a specified format
  catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/DumpCommand.java
  catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/DumpCommandTest.java
  catalog/transformer/catalog-transformer-zip/pom.xml
  catalog/transformer/catalog-transformer-zip/src/main/java/org/codice/ddf/catalog/transformer/zip/ZipCompression.java
  catalog/transformer/catalog-transformer-zip/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/transformer/catalog-transformer-zip/src/test/java/org/codice/ddf/catalog/transformer/zip/ZipCompressionTest.java
  catalog/transformer/catalog-transformer-zip/src/test/resources/export.html
Labels: ✨New Feature

#4339 [2.13.x] DDF-04275 Replace keyczar with tink
  distribution/ddf-common/pom.xml
  distribution/ddf-common/src/main/resources-filtered/etc/custom.properties
  distribution/ddf-common/src/main/resources-filtered/etc/custom.system.properties
  distribution/ddf-common/src/main/resources/security/default.policy
  distribution/docs/src/main/resources/content/_dependencyList/ddf-dependency-list.adoc
  distribution/docs/src/main/resources/content/_securityFramework/security-encryption-intro.adoc
  distribution/kernel/pom.xml
  platform/osgi/platform-osgi-configadmin/pom.xml
  platform/osgi/platform-osgi-configadmin/src/main/java/org/codice/felix/cm/file/EncryptingPersistenceManager.java
  platform/osgi/platform-osgi-configadmin/src/test/java/org/codice/felix/cm/file/EncryptingPersistenceManagerTest.java
  platform/security/encryption/platform-security-encryption-api/pom.xml
  platform/security/encryption/platform-security-encryption-commands/src/test/java/ddf/security/command/EncryptCommandTest.java
  platform/security/encryption/platform-security-encryption-crypter/pom.xml
  platform/security/encryption/platform-security-encryption-crypter/src/main/java/ddf/security/encryption/crypter/Crypter.java
  platform/security/encryption/platform-security-encryption-crypter/src/test/java/ddf/security/encryption/crypter/CrypterTest.java
  platform/security/encryption/platform-security-encryption-impl/pom.xml
  platform/security/encryption/platform-security-encryption-impl/src/main/java/ddf/security/encryption/impl/EncryptionServiceImpl.java
  platform/security/encryption/platform-security-encryption-impl/src/test/java/ddf/security/encryption/impl/EncryptionServiceImplTest.java
  platform/security/encryption/pom.xml
  platform/security/platform-security-core-api/src/main/java/ddf/security/SecurityConstants.java
  pom.xml
Labels: :lock: Security, 🏬 Release Branch

#4270 DDF-04264 updates lodash and plotly to newer versions
  ui/packages/admin-metrics-ui/package.json
  ui/packages/admin-security-certificate-ui/package.json
  ui/packages/catalog-admin-module-sources/package.json
  ui/packages/catalog-ui-search/package.json
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/histogram/histogram.view.js
  ui/packages/geowebcache-admin-plugin/package.json
  ui/packages/registry-admin-local-ui/package.json
  ui/packages/registry-admin-remote-ui/package.json
  ui/packages/resourcemanagement-querymonitor-ui/package.json
  ui/packages/resourcemanagement-usage-ui/package.json
  ui/packages/security-handler-guest/package.json
  ui/packages/security-idp-server/package.json
  ui/packages/ui/package.json
  ui/yarn.lock
Labels: ⬆️ Dependency Upgrade, 👤 UI

#4356 DDF-04355 Add allow-same-origin to source-app iframe
  catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/metatype/metatype.xml
  ui/packages/catalog-ui-search/src/main/webapp/component/source-app/source-app.hbs
Labels: 👞Bug Fix, 👤 UI

#4412 DDF-04411 Fixes this.region undefined issue in MRC
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/marionette-region-container/marionette-region-container.spec.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/marionette-region-container/marionette-region-container.tsx
Labels: 👞Bug Fix, 👤 UI

#4438 DDF-04370 Fixed quartz2 feature dependency for DefaultUsersDeletionScheduler
  features/admin/src/main/feature/feature.xml
  features/camel/src/main/feature/feature.xml
Labels: 👞Bug Fix

#4378 DDF-04343 As a user, I would like to enter Degrees, Minutes, Seconds coordinates into the gazetteer search box so I can pan to a certain location quickly
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/QueryApplication.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/suggestion/DmsCoordinateProcessor.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/suggestion/LatLon.java
  catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/query/suggestion/DmsCoordinateProcessorTest.java
Labels: 👤 UI
