Repository codice/ddf, pull requests merged in 2019-06, with the labels that each got.

#4831 DDF-4828 fix Incorrect buffer for Polygons
  ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.base.line.js
  ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.polygon.js
  ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.polygon.js
Labels: 👤 UI

#4788 DDF-4467 rework of lat/lon validation
  ui/packages/catalog-ui-search/src/main/webapp/component/location-new/inputs/masked-text-field.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-new/utils/dms-utils.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/location/base.line.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/location/location.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/location/point-radius.js
Labels: 👤 UI

#4906 DDF-4903 Fix render loop caused by poller in dropdown.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/dropdown/dropdown.js
Labels: 👤 UI

#4918 DDF-4917 Version bump for JS-beautify
  ui/packages/catalog-ui-search/package.json
  ui/yarn.lock
Labels: 👤 UI

#4913 DDF-4864 Fix queries on attributes in the suggestion whitelist
  ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js
Labels: 👤 UI

#4853 DDF-4850 Fix issue where dropdown input will prevent the user from using the wildcard (*) operator
  ui/packages/catalog-ui-search/src/main/webapp/component/select/filterHelper.js
  ui/packages/catalog-ui-search/src/main/webapp/component/select/filterHelper.spec.js
Labels: 👤 UI

#4919 DDF-04746 enable eslint rule `no-var` for catalog-ui-search
  ui/packages/catalog-ui-search/.eslintrc.js
  ui/packages/catalog-ui-search/src/main/webapp/component/associations-graph/associations-graph.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/list-editor/list-editor.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-new/utils/dd-utils.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-new/utils/dms-utils.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-new/utils/usng-utils.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-new/utils/wkt-utils.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js
  ui/packages/catalog-ui-search/src/main/webapp/component/property/property.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-altitude/query-altitude.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-time/query-time.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/histogram/histogram.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/DrawingUtility.js
  ui/packages/catalog-ui-search/src/main/webapp/js/Autocomplete.js
  ui/packages/catalog-ui-search/src/main/webapp/js/cql.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResult.collection.js
  ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.bbox.js
  ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.circle.js
  ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.line.js
  ui/packages/catalog-ui-search/src/main/webapp/lib/cesium-drawhelper/DrawHelper.js
Labels: 👤 UI

#4916 [2.15.x] DDF-0000 Add user require to search form editor
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js
Labels: 👤 UI

#4904 DDF-4901 Provide an extension point for query forms in Intrigue
  ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-adhoc/query-adhoc.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-editor/query-editor.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-interactions/search-interactions.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/search-interactions/search-interactions.view.js
  ui/packages/catalog-ui-search/src/main/webapp/extension-points/extension-points.tsx
  ui/packages/catalog-ui-search/src/main/webapp/extension-points/query-forms/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/js/Entry.tsx
Labels: 👤 UI

#4915 DDF-04824 Bumps usng.js version in catalog-ui-search
  ui/packages/catalog-ui-search/package.json
  ui/yarn.lock
Labels: 👤 UI

#4945 DDF-04944 Adding zoom controls to map
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/openlayers.less
Labels: 👤 UI

#4956 DDF-2824 updated documentation links in README
  README.md
Labels: :book: Documentation, Meta, docs-content, 👞Bug Fix

#4781 DDF-04374 updated docs for ftp endpoint
  distribution/docs/src/main/resources/content/_integrating/_endpoints/ftp-endpoint.adoc
  distribution/docs/src/main/resources/content/_integrating/_endpoints/opensearch-endpoint.adoc
Labels: :book: Documentation, Integrator Docs Rewrite, docs-content

#4947 DDF-4946 Fix Preview Tab
  catalog/transformer/catalog-transformer-preview/src/main/java/org/codice/ddf/transformer/preview/actions/PreviewActionProvider.java
  catalog/transformer/catalog-transformer-preview/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-preview/metacard-preview.view.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResult.js
Labels: 👤 UI

#4959 DDF-4958 Fix React Dropdown Closing
  ui/packages/catalog-ui-search/src/main/webapp/react-component/dropdown/dropdown.js
Labels: 👤 UI

#4974 DDF-4792 Improve table visualization css
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/table-viz.view.js
Labels: 👤 UI

#4931 DDF-04930 URI-encode the result's source and ID in the export URL
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/results-export/results-export.tsx
Labels: 👞Bug Fix, 👤 UI

#5008 DDF-5007 Remove Export Action
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/multi-select-actions/multi-select-actions.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/multi-select-actions/multi-select-actions.tsx
Labels: 👤 UI

#4898 DDF-4897 Results export view cannot find source id
  ui/packages/catalog-ui-search/src/main/webapp/component/query-interactions/query-interactions.view.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-interactions/export-interaction.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/results-export/results-export.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/cql/cql.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/export/export.tsx
Labels: 👤 UI

#5020 DDF-05019 Updated navigation right user section for spacing.
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/navigation-right/navigation-right.tsx
Labels: 👤 UI

#5026 Removes dead code in paging.view
  ui/packages/catalog-ui-search/src/main/webapp/component/paging/paging.view.js
Labels: 👤 UI

#5023 DDF-5022 Fix dropdown calculated max height
  ui/packages/catalog-ui-search/src/main/webapp/behaviors/dropdown.behavior.utility.js
Labels: 👤 UI

#5006 DDF-04998 Limit Filter Attribute Depth on Search Form Reloading
  ui/packages/catalog-ui-search/src/main/webapp/component/filter-builder/filter-serialization.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js
  ui/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.js
  ui/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.spec.js
Labels: 👤 UI

#5044 DDF-2824 Fix Path for RESTful Delete Endpoint
  distribution/docs/src/main/resources/content/_integrating/_endpoints/catalog-rest-endpoint.adoc
Labels: :book: Documentation, docs-content
