Repository codice/ddf, pull requests merged in 2019-01, with the labels that each got.

#4093 DDF-4356 Workspace Query Data Migration
  catalog/catalog-app/pom.xml
  catalog/catalog-app/src/main/resources/features.xml
  catalog/migrate/migration-api/pom.xml
  catalog/migrate/migration-api/src/main/java/ddf/catalog/migrate/migration/api/DataMigratable.java
  catalog/migrate/migration-api/src/main/java/ddf/catalog/migrate/migration/api/ServiceNotFoundException.java
  catalog/migrate/migration-command/pom.xml
  catalog/migrate/migration-command/src/main/java/ddf/catalog/migrate/migration/command/MigrateCommand.java
  catalog/migrate/migration-command/src/test/java/ddf/catalog/migrate/migration/command/MigrateCommandTest.java
  catalog/migrate/pom.xml
  catalog/migrate/workspace-query-separation/pom.xml
  catalog/migrate/workspace-query-separation/src/main/java/ddf/catalog/migrate/migration/workspace/query/separation/WorkspaceQueryMigration.java
  catalog/migrate/workspace-query-separation/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/migrate/workspace-query-separation/src/test/java/ddf/catalog/migrate/migration/workspace/query/separation/WorkspaceQueryMigrationTest.java
  catalog/migrate/workspace-query-separation/src/test/resources/query.xml
  catalog/pom.xml
  distribution/ddf-common/src/main/resources/security/default.policy
  distribution/docs/src/main/resources/content/_managing/_running/available-console-commands.adoc
  distribution/docs/src/main/resources/content/_managing/_running/migrate-commands.adoc
Labels: 📈 Improvement

#4172 DDF-4424 Updated Metacard Validity Filter Plugin docs
  distribution/docs/src/main/resources/content/_configuring/hiding-errors-by-role.adoc
Labels: :book: Documentation

#4153 DDF-4409 Fixing CSS to keep text breaking out of popovers
  ui/packages/registry-admin-remote-ui/src/main/webapp/less/styles.less
Labels: 👞Bug Fix, 👤 UI

#4164 DDF-4415 Initializes upload editor to not show validation issues on load
  ui/packages/catalog-ui-search/src/main/webapp/component/ingest-editor/ingest-editor.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/property/property.collection.view.js
Labels: 👤 UI

#4182 DDF-4431 Updates results rendering to be debounced
  ui/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.less
  ui/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.view.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResponse.js
Labels: 👤 UI

#4176 DDF-4424 Updated Metacard Validity Filter Plugin docs (#4172)
  distribution/docs/src/main/resources/content/_managing/_configuring/hiding-errors-by-role.adoc
Labels: :book: Documentation

#4186 [2.13.x] DDF-4434 Changed the ID attribute on a LogoutRequest to comply with the SAML Specification
  platform/security/core/security-core-services/src/main/java/ddf/security/samlp/impl/LogoutMessageImpl.java
Labels: 🏬 Release Branch, 👞Bug Fix

#4185 DDF-4415 Initializes upload editor to not show validation issues on load
  ui/packages/catalog-ui-search/src/main/webapp/component/ingest-editor/ingest-editor.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/property/property.collection.view.js
Labels: 👤 UI

#4120 DDF-4218 Fix solr:backup and add solr:restore command
  catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/DumpCommand.java
  catalog/core/catalog-core-solrcommands/pom.xml
  catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java
  catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/RestoreCommand.java
  catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/SolrCommands.java
  catalog/core/catalog-core-solrcommands/src/test/java/org/codice/ddf/commands/solr/BackupCommandTest.java
  catalog/core/catalog-core-solrcommands/src/test/java/org/codice/ddf/commands/solr/RestoreCommandTest.java
  catalog/core/catalog-core-solrcommands/src/test/java/org/codice/ddf/commands/solr/SolrCommandTest.java
  distribution/docs/src/main/resources/content/_managing/_running/available-console-commands.adoc
  distribution/docs/src/main/resources/content/_managing/_running/solr-commands.adoc
  platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/HttpSolrClientFactory.java
  platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/SolrCloudClientFactory.java
  platform/solr/solr-factory-impl/src/test/groovy/org/codice/solr/factory/impl/HttpSolrClientFactorySpec.groovy
Labels: ✨New Feature, 👞Bug Fix

#4181 DDF-4429 Reminder when deleting shared workspaces
  ui/packages/catalog-ui-search/src/main/webapp/js/store.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/sharing/sharing.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/workspace-interactions/workspace-interactions.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/workspace-interactions/workspace-interactions.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/security/security.tsx
Labels: 👤 UI

#4178 DDF-4428 Fix USNG/MGRS point-radius input box
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js
Labels: 👞Bug Fix, 👤 UI

#4193 DDF-4437 Bumps usng.js version to the latest
  ui/packages/catalog-ui-search/package.json
  ui/yarn.lock
Labels: ⬆️ Dependency Upgrade, 👤 UI

#4174 DDF-4420 Fixed rendering of large number of attributes on result forms
  ui/packages/catalog-ui-search/src/main/webapp/component/lightbox/result/lightbox.result.less
  ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form-tab-container.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.collection.js
  ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.less
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form-interactions/search-form-interactions.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.js
Labels: 👞Bug Fix, 👤 UI

#4211 DDF-4449 Advanced Search - Intermittent Search button disappears from the template
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.view.js
Labels: 👞Bug Fix, 👤 UI

#4224 [2.13.x] DDF-4067 Tabs in Intrigue are hidden after adding an attribute
  ui/packages/catalog-ui-search/src/main/webapp/component/golden-layout/golden-layout.less
Labels: 👞Bug Fix, 👤 UI

#4231 DDF-4067 Tabs in Intrigue are hidden after adding an attribute
  ui/packages/catalog-ui-search/src/main/webapp/component/golden-layout/golden-layout.less
Labels: 👞Bug Fix, 👤 UI

#4184 DDF-4432 Enforce CRLF for .cmd files
  .gitattributes
  distribution/ddf-common/src/main/resources/etc/certs/CertNew.cmd
  distribution/solr-distro/src/main/resources/bin/solr.cmd
Labels: 👞Bug Fix, 👷‍♀️Build

#4228 DDF-4464 blue imp dependency
  ui/packages/admin-metrics-ui/src/main/resources/index.html
  ui/packages/admin-metrics-ui/src/main/webapp/main.js
  ui/packages/admin-security-certificate-ui/src/main/resources/index.html
  ui/packages/admin-security-certificate-ui/src/main/webapp/main.js
  ui/pom.xml
Labels: ⬆️ Dependency Upgrade, 👤 UI

#4219 DDF-4455 Adds a link to the system root context from the Intrigue navigation slideout
  ui/packages/catalog-ui-search/src/main/webapp/component/navigator/navigator.view.js
Labels: 👤 UI

#4187 DDF-4435 upgraded UI dependencies
  ui/packages/ace/package.json
  ui/packages/catalog-ui-search/package.json
  ui/yarn.lock
Labels: ⬆️ Dependency Upgrade, 👤 UI

#4238 DDF-4432 CRLF for solr.cmd
  distribution/solr-distro/src/main/resources/bin/solr.cmd
Labels: 👞Bug Fix, 👷‍♀️Build

#4179 DDF-4430 updated the IdP to allow it to renew expired assertions
  platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java
  platform/security/idp/security-idp-server/src/test/java/org/codice/ddf/security/idp/server/IdpEndpointTest.java
  platform/security/sts/security-sts-realm/src/main/java/ddf/security/realm/sts/AbstractStsRealm.java
Labels: 📈 Improvement

#4171 DDF-4423 Upload Editor Reads 100% Before All Files Uploaded
  ui/packages/catalog-ui-search/src/main/webapp/js/model/UploadBatch.js
Labels: 👤 UI, 📈 Improvement

#4213 DDF-4448 Normalized longitude in Map view
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.model.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/wrap-num/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/wrap-num/wrap-num.tsx
Labels: 👤 UI

#4180 DDF-4426 Upgrade to Karaf 4.2.2
  catalog/ui/search-ui-app/pom.xml
  catalog/ui/search-ui-app/src/main/resources/features.xml
  distribution/ddf-common/src/main/resources-filtered/etc/custom.properties
  distribution/ddf-common/src/main/resources-filtered/etc/org.apache.karaf.features.xml
  distribution/ddf-common/src/main/resources-filtered/etc/startup.properties
  distribution/ddf-common/src/main/resources/common-bin.xml
  distribution/ddf-common/src/main/resources/etc/jre.properties
  distribution/ddf-common/src/main/resources/etc/log4j2.xml
  distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.logging.cfg
  distribution/docs/src/main/resources/content/_architectures/_catalogFrameworks/catalog-framework-intro.adoc
  distribution/docs/src/main/resources/content/_managing/_running/ddf-service.adoc
  distribution/docs/src/main/resources/content/_managing/_running/monitoring.adoc
  distribution/docs/src/main/resources/content/_managing/_securing/auditing.adoc
  distribution/docs/src/main/resources/content/_reference/_dependencyList/ddf-dependency-list.adoc
  distribution/kernel/pom.xml
  distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
  distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSecurityAuditPlugin.java
  features/karaf/src/main/feature/feature.xml
  features/kernel/src/main/feature/feature.xml
  features/security/pom.xml
  features/security/src/main/feature/feature.xml
  features/utilities/src/main/feature/feature.xml
  platform/io/platform-io-impl/pom.xml
  platform/osgi/platform-osgi-configadmin/src/main/java/org/codice/felix/cm/file/ConfigurationContextImpl.java
  platform/osgi/platform-osgi-configadmin/src/test/java/org/codice/felix/cm/file/ConfigurationContextImplTest.java
  pom.xml
Labels: ☕ J11 Upgrade, ⬆️ Dependency Upgrade, 🌊Impacts Downstream

#4208 DDF-4341 Enable list actions to be called with fetch
  ui/packages/catalog-ui-search/src/main/webapp/component/list-interactions/list-interactions.view.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/table-export/table-export.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/save-file/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/save-file/save-file.tsx
Labels: 👤 UI

#4204 DDF-4444 Fix for Relative Search – the units drop down selection changes from…
  ui/packages/catalog-ui-search/src/main/webapp/component/relative-time/relative-time.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/relative-time/serial.js
  ui/packages/catalog-ui-search/src/main/webapp/component/relative-time/serial.spec.js
Labels: 👞Bug Fix, 👤 UI

#4229 DDF-4467 Validating lat/lon coords
  ui/packages/catalog-ui-search/src/main/webapp/component/location-new/inputs/masked-text-field.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-new/utils/dms-utils.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/location/base.line.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/location/location.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/text-field/text-field.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/text-field/text-field.spec.js
Labels: 👤 UI, 📈 Improvement

#4167 DDF-4418 As a user I would like lat/lon values to only have at most 6 points to the right of the decimal so that my locations are easier to read
  ui/packages/catalog-ui-search/src/main/webapp/component/location-new/geo-components/lat-long-dd.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-new/geo-components/wkt.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-new/location-new.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-new/utils/index.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-new/utils/wkt-utils.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js
  ui/packages/catalog-ui-search/src/main/webapp/js/DistanceUtils.js
  ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.bbox.js
  ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.circle.js
  ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.line.js
  ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.polygon.js
  ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.bbox.js
  ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.circle.js
  ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.line.js
  ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.polygon.js
Labels: 👤 UI

#4177 DDF-4413 Migrate dropdown.map-settings.view.js to React
  ui/packages/catalog-ui-search/src/main/webapp/component/component.less
  ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/map-settings/dropdown.map-settings.less
  ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/map-settings/dropdown.map-settings.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/map-settings/map-settings.less
  ui/packages/catalog-ui-search/src/main/webapp/component/map-settings/map-settings.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/map-settings/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/map-settings/map-settings.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/map-settings/example-coordinates.spec.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/map-settings/example-coordinates.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/map-settings/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/map-settings/map-settings.tsx
Labels: 👤 UI

#4169 DDF-4421: Pom-fix does not process feature files with the name "feature.xml"
  catalog/core/catalog-core-api/pom.xml
  catalog/core/catalog-core-api/src/main/resources/test-feature.xml
  features/admin/pom.xml
  features/apps/pom.xml
  features/install-profiles/pom.xml
  features/install-profiles/src/main/feature/feature.xml
  features/security/pom.xml
  features/solr/pom.xml
  features/test-utilities/pom.xml
  libs/libs-pomfix/lib/fix.js
  libs/libs-pomfix/lib/util.js
  platform/mime/core/platform-mime-core-api/pom.xml
  platform/mime/core/platform-mime-core-api/src/main/resources/test-feature.xml
  platform/util/platform-util-uuidgenerator/util-uuidgenerator-api/pom.xml
  platform/util/platform-util-uuidgenerator/util-uuidgenerator-api/src/main/resources/test-feature.xml
Labels: 👷‍♀️Build

#4202 DDF-4429 Fixed shared workspace deletion reminder
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/sharing/sharing.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/workspace-interactions/workspace-interactions.tsx
Labels: 👤 UI

#4227 DDF-4463 Simplify search forms selection with a dropdown
  ui/packages/catalog-ui-search/src/main/webapp/component/component.less
  ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/search-form-selector/dropdown.search-form-selector.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.collection.js
  ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.collection.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-forms.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form-list/search-form-list.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form-selector/search-form-selector.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form-selector/search-form-selector.less
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form-selector/search-form-selector.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/forms-sharing/search-form-sharing-collection-instance.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/forms-sharing/search-form-sharing-tab-container.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/forms-sharing/search-form-sharing.collection.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/forms-sharing/search-form-sharing.collection.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/forms-system/search-form-system-collection-instance.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/forms-system/search-form-system-tab-container.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/forms-system/search-form-system.collection.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/forms-system/search-form-system.collection.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form-collection-instance.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form-tab-container.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.collection.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.collection.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.less
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-interactions/search-interactions.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/search-interactions/search-interactions.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/tabs/search-form/tabs.search-form.view.js
Labels: 👤 UI, 📈 Improvement
