Repository codice/ddf, pull requests merged in 2019-09, with the labels that each got.

#5264 [2.17.x] DDF-5263 Fix improper SLF4J usages
  distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/callables/GetConfigurationProperties.java
  platform/admin/admin-configuration-configupdater/src/main/java/org/codice/ddf/admin/configuration/ConfigurationUpdater.java
  platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ExportMigrationConfigurationAdminContext.java
  platform/security/core/security-core-impl/src/main/java/ddf/security/assertion/jwt/impl/SecurityAssertionJwt.java
  platform/security/encryption/platform-security-encryption-crypter/src/main/java/ddf/security/encryption/crypter/Crypter.java
  platform/security/encryption/platform-security-encryption-impl/src/main/java/ddf/security/encryption/impl/EncryptionServiceImpl.java
Labels: 👞Bug Fix

#5287 DDF-5291 fix goldenlayout titles: minimise maximise should be in US En…
  ui/packages/catalog-ui-search/src/main/webapp/component/golden-layout/golden-layout.view.js
Labels: 👤 UI, 📈 Improvement

#5261 DDF-5260 Updates editing restrictions to take into account write access
  ui/package.json
  ui/packages/catalog-ui-search/src/main/webapp/component/details-interactions/details-interactions.less
  ui/packages/catalog-ui-search/src/main/webapp/component/details-interactions/details-interactions.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/editor/editor.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/editor/editor.less
  ui/packages/catalog-ui-search/src/main/webapp/component/editor/editor.view.jsx
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-associations/metacard-associations.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-associations/metacard-associations.less
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-associations/metacard-associations.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/tabs/metacard/tabs-metacard.less
  ui/packages/catalog-ui-search/src/main/webapp/component/tabs/metacard/tabs-metacard.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/tabs/metacards/tabs-metacards.less
  ui/packages/catalog-ui-search/src/main/webapp/component/tabs/metacards/tabs-metacards.view.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/MetacardProperties.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResult.collection.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResult.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/User.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/Workspace.js
  ui/packages/catalog-ui-search/src/main/webapp/js/properties.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/metacard-history/container.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/metacard-history/presentation.tsx
  ui/packages/catalog-ui-search/src/main/webapp/test/mock-api/mock-properties.js
Labels: 👤 UI, 📈 Improvement

#5169 DDF-5168 Upgrade CXF to 3.2.9
  catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorIT.java
  distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
  distribution/test/itests/test-itests-ddf/pom.xml
  distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestEmbeddedSolr.java
  distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java
  features/cxf/src/main/feature/feature.xml
  features/pom.xml
  platform/security/platform-security-core-api/pom.xml
  platform/sync-installer/sync-installer-impl/src/main/java/org/codice/ddf/sync/installer/impl/SynchronizedInstallerImpl.java
  platform/sync-installer/sync-installer-impl/src/test/groovy/org/codice/ddf/sync/installer/impl/SynchronizedInstallerImplSpec.groovy
  pom.xml
Labels: ⬆️ Dependency Upgrade

#5358 DDF-5357 Fixes memory leak in theme
  ui/packages/catalog-ui-search/src/main/webapp/react-component/theme/theme.tsx
Labels: 👞Bug Fix, 👤 UI

#5350 DDF-5349 added Configure SSO instructions to admin docs
  distribution/docs/src/main/resources/content/_managing/_installing/configure-single-sign-on.adoc
Labels: :book: Documentation, docs-content, 👞Bug Fix

#5368 DDF-5367 Update DefinitionParser to use Apache commons io
  catalog/core/catalog-core-definitionparser/src/main/java/ddf/catalog/definition/impl/DefinitionParser.java
  catalog/core/catalog-core-definitionparser/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  distribution/ddf-common/src/main/resources/etc/org.apache.felix.fileinstall-definitions.cfg
  distribution/ddf-common/src/main/resources/security/default.policy
Labels: 👞Bug Fix, 📈 Improvement
