Repository codice/ddf, pull requests merged in 2019-10, with the labels that each got.

#5353 DDF-5347 Add per source latency metric
  catalog/core/catalog-core-sourcemetricsplugin/src/main/java/ddf/catalog/metrics/source/SourceMetricsImpl.java
  catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java
  catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SortedQueryMonitor.java
  catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/TimedSource.java
  catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/CachingFederationStrategyTest.java
Labels: 📈 Improvement

#5366 DDF-5033 added glossary to user docs
  distribution/docs/src/main/resources/content/_integrating/_endpoints/opensearch-endpoint.adoc
  distribution/docs/src/main/resources/content/_using/accessing-intrigue.adoc
  distribution/docs/src/main/resources/content/_using/attribute-editor.adoc
  distribution/docs/src/main/resources/content/_using/create-a-search.adoc
  distribution/docs/src/main/resources/content/_using/editing-searches.adoc
  distribution/docs/src/main/resources/content/_using/lists.adoc
  distribution/docs/src/main/resources/content/_using/map-tools.adoc
  distribution/docs/src/main/resources/content/_using/result-forms.adoc
  distribution/docs/src/main/resources/content/_using/search-forms.adoc
  distribution/docs/src/main/resources/content/_using/sources-ui.adoc
  distribution/docs/src/main/resources/content/_using/using-intrigue-intro.adoc
  distribution/docs/src/main/resources/content/_using/viewing-results.adoc
  distribution/docs/src/main/resources/content/_using/workspaces.adoc
  distribution/docs/src/main/resources/templates/documentation.ftl
  distribution/docs/src/main/resources/templates/using.ftl
Labels: :book: Documentation, 📈 Improvement

#5397 DDF-4759 updated script to automate product site
  Documentation-versions.html
  index.html
  js/script.js
Labels: :book: Documentation, Meta, docs-automation, 🏬 Release Branch, 👷‍♀️Build, 📈 Improvement

#5407 DDF-04759 updated gh-pages script for site index
  js/script.js
Labels: :book: Documentation, docs-automation, 🏬 Release Branch, 👞Bug Fix

#5307 DDF-05306 Updates MGRS bounding box to use two points vs a single block
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/location/bounding-box.js
Labels: 👤 UI

#5400 DDF-5398 Update keyword to be more configurable
  ui/packages/catalog-ui-search/src/main/webapp/react-component/location/keyword.js
Labels: 👤 UI

#5433 [2.18.x] DDF-5432 Fix point-radius lat/lon input validation
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js
  ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.circle.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/location/point-radius.js
Labels: 👞Bug Fix, 👤 UI

#5434 [2.19.x] DDF-5432 Fix point-radius lat/lon input validation
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js
  ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.circle.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/location/point-radius.js
Labels: 👞Bug Fix, 👤 UI

#5435 DDF-5432 Fix point-radius lat/lon input validation
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js
  ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.circle.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/location/point-radius.js
Labels: 👞Bug Fix, 👤 UI

#5478 [MASTER] DDF-5477 Makes methods that invoke privileged code final.
  platform/admin/admin-configuration-configupdater/src/main/java/org/codice/ddf/admin/configuration/ConfigurationUpdater.java
  platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/HttpClientBuilder.java
Labels: :lock: Security

#5475 [MASTER] DDF-5474 Escapes user-input jsonp parameter on GeoCoderEndpoint.getLocation calls
  catalog/spatial/geocoding/spatial-geocoding-endpoint/pom.xml
  catalog/spatial/geocoding/spatial-geocoding-endpoint/src/main/java/org/codice/ddf/spatial/geocoder/endpoint/GeoCoderEndpoint.java
Labels: :lock: Security

#5480 [MASTER] DDF-5479 Ensure correct locale is used when calling toLowerCase before comparison
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/transformer/TransformerDescriptorApplication.java
Labels: :lock: Security

#5483 [2.19.x] DDF-5474 Escapes user-input jsonp parameter on GeoCoderEndpoint.getLocation calls
  catalog/spatial/geocoding/spatial-geocoding-endpoint/pom.xml
  catalog/spatial/geocoding/spatial-geocoding-endpoint/src/main/java/org/codice/ddf/spatial/geocoder/endpoint/GeoCoderEndpoint.java
Labels: :lock: Security

#5484 [2.19.x] DDF-5477 Makes methods that invoke privileged code final. (#5478)
  platform/admin/admin-configuration-configupdater/src/main/java/org/codice/ddf/admin/configuration/ConfigurationUpdater.java
  platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/HttpClientBuilder.java
Labels: :lock: Security

#5485 [2.19.x] DDF-5479 Ensure correct locale is used when calling toLowerCase before comparison
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/transformer/TransformerDescriptorApplication.java
Labels: :lock: Security

#5486 [2.16.x] DDF-5474 Escapes user-input jsonp parameter on GeoCoderEndpoint.getLo…
  catalog/spatial/geocoding/spatial-geocoding-endpoint/pom.xml
  catalog/spatial/geocoding/spatial-geocoding-endpoint/src/main/java/org/codice/ddf/spatial/geocoder/endpoint/GeoCoderEndpoint.java
Labels: :lock: Security

#5487 [2.16.x] DDF-5477 Makes methods that invoke privileged code final. (#5478)
  platform/admin/admin-configuration-configupdater/src/main/java/org/codice/ddf/admin/configuration/ConfigurationUpdater.java
  platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/HttpClientBuilder.java
Labels: :lock: Security

#5488 [2.16.x] DDF-5479 Ensure correct locale is used when calling toLowerCase on tr…
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/transformer/TransformerDescriptorApplication.java
Labels: :lock: Security

#5489 [2.17.x] DDF-5474 Escapes user-input jsonp parameter on GeoCoderEndpoint.getLo…
  catalog/spatial/geocoding/spatial-geocoding-endpoint/pom.xml
  catalog/spatial/geocoding/spatial-geocoding-endpoint/src/main/java/org/codice/ddf/spatial/geocoder/endpoint/GeoCoderEndpoint.java
Labels: :lock: Security

#5490 [2.17.x] DDF-5477 Makes methods that invoke privileged code final. (#5478)
  platform/admin/admin-configuration-configupdater/src/main/java/org/codice/ddf/admin/configuration/ConfigurationUpdater.java
  platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/HttpClientBuilder.java
Labels: :lock: Security

#5491 [2.17.x] DDF-5479 Ensure correct locale is used when calling toLowerCase on tr…
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/transformer/TransformerDescriptorApplication.java
Labels: :lock: Security

#5492 [2.18.x] DDF-5474 Escapes user-input jsonp parameter on GeoCoderEndpoint.getLo…
  catalog/spatial/geocoding/spatial-geocoding-endpoint/pom.xml
  catalog/spatial/geocoding/spatial-geocoding-endpoint/src/main/java/org/codice/ddf/spatial/geocoder/endpoint/GeoCoderEndpoint.java
Labels: :lock: Security

#5493 [2.18.x] DDF-5477 Makes methods that invoke privileged code final. (#5478)
  platform/admin/admin-configuration-configupdater/src/main/java/org/codice/ddf/admin/configuration/ConfigurationUpdater.java
  platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/HttpClientBuilder.java
Labels: :lock: Security

#5494 [2.18.x] DDF-5479 Ensure correct locale is used when calling toLowerCase on tr…
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/transformer/TransformerDescriptorApplication.java
Labels: :lock: Security

#5372 DDF-5371 Adds beta-admin-ui
  ui/packages/admin-core-logviewer/package.json
  ui/packages/admin-core-logviewer/src/main/webapp/js/components/log-panel/log-panel.js
  ui/packages/beta-admin-ui/package.json
  ui/packages/beta-admin-ui/src/main/webapp/components/entry/entry.tsx
  ui/packages/beta-admin-ui/src/main/webapp/index.js
  ui/packages/beta-admin-ui/src/main/webapp/index.spec.js
  ui/packages/beta-admin-ui/tsconfig.json
  ui/packages/catalog-admin-module-sources/package.json
  ui/packages/catalog-admin-module-sources/src/main/webapp/js/HandlebarsHelpers.js
  ui/packages/catalog-admin-module-sources/src/main/webapp/main.js
  ui/packages/ui/src/main/webapp/index.html
  ui/packages/ui/src/main/webapp/js/application.js
  ui/pom.xml
  ui/yarn.lock
  yarn.lock
Labels: ✨New Feature, 👤 UI

#5503 DDF-5502 Upgrading Apache Camel to 2.24.2
  features/camel/src/main/feature/feature.xml
  pom.xml
Labels: ⬆️ Dependency Upgrade

#5462 DDF-5431 Upgrading pac4j to version 3.8.2
  platform/security/handler/security-handler-oidc/pom.xml
  platform/security/handler/security-handler-oidc/src/main/java/org/codice/ddf/security/handler/oidc/OidcHandlerConfigurationImpl.java
  platform/security/security-oidc-realm/src/main/java/org/codice/ddf/security/oidc/realm/OidcTokenValidator.java
  pom.xml
Labels: ⬆️ Dependency Upgrade

#5510 DDF-5504 Upgraded to DDF-Parent 1.0.8 and Dependency-Check 5.2.2
  Jenkinsfile
  pom.xml
Labels: ⬆️ Dependency Upgrade
