Repository codice/ddf, pull requests merged in 2019-03, with the labels that each got.

#4431 DDF-04275 Replace keyczar with tink
  distribution/ddf-common/pom.xml
  distribution/ddf-common/src/main/resources-filtered/etc/custom.properties
  distribution/ddf-common/src/main/resources-filtered/etc/custom.system.properties
  distribution/ddf-common/src/main/resources/security/default.policy
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-encryption-intro.adoc
  distribution/docs/src/main/resources/content/_reference/_dependencyList/ddf-dependency-list.adoc
  distribution/kernel/pom.xml
  platform/osgi/platform-osgi-configadmin/pom.xml
  platform/osgi/platform-osgi-configadmin/src/main/java/org/codice/felix/cm/file/EncryptingPersistenceManager.java
  platform/osgi/platform-osgi-configadmin/src/test/java/org/codice/felix/cm/file/EncryptingPersistenceManagerTest.java
  platform/security/encryption/platform-security-encryption-api/pom.xml
  platform/security/encryption/platform-security-encryption-commands/src/test/java/ddf/security/command/EncryptCommandTest.java
  platform/security/encryption/platform-security-encryption-crypter/pom.xml
  platform/security/encryption/platform-security-encryption-crypter/src/main/java/ddf/security/encryption/crypter/Crypter.java
  platform/security/encryption/platform-security-encryption-crypter/src/test/java/ddf/security/encryption/crypter/CrypterTest.java
  platform/security/encryption/platform-security-encryption-impl/pom.xml
  platform/security/encryption/platform-security-encryption-impl/src/main/java/ddf/security/encryption/impl/EncryptionServiceImpl.java
  platform/security/encryption/platform-security-encryption-impl/src/test/java/ddf/security/encryption/impl/EncryptionServiceImplTest.java
  platform/security/encryption/pom.xml
  platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/IdpLogoutActionProvider.java
  platform/security/idp/security-idp-client/src/test/java/org/codice/ddf/security/idp/client/IdpLogoutActionProviderTest.java
  platform/security/platform-security-core-api/src/main/java/ddf/security/SecurityConstants.java
  pom.xml
Labels: :lock: Security

#4463 [2.13.x]DDF-04462 Fix logout
  platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/IdpLogoutActionProvider.java
  platform/security/idp/security-idp-client/src/test/java/org/codice/ddf/security/idp/client/IdpLogoutActionProviderTest.java
Labels: 🏬 Release Branch, 👞Bug Fix

#4133 DDF-4331 Add dockerd to pipepline
  Jenkinsfile
Labels: 👷‍♀️Build

#4404 DDF-04397 Allow user to specify number or results to export
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java
  catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.xml
  catalog/ui/search-ui-app/src/main/resources/etc/org.codice.ddf.catalog.ui.config
  distribution/docs/src/main/resources/content/_reference/_tables/catalog.ui.config.adoc
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/table-export/table-export.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/table-export/table-export.tsx
Labels: ✨New Feature, 👤 UI

#4443 [2.13.x]DDF-4430 Changing docs to show JDK is not required for installation
  distribution/ddf-common/src/main/resources/bin/ddf
  distribution/ddf-common/src/main/resources/bin/ddf.bat
  distribution/docs/src/main/resources/content/_installing/hardware-reqs.adoc
  distribution/docs/src/main/resources/content/_installing/java-reqs.adoc
  distribution/docs/src/main/resources/content/_quickstart/quickstart-installing.adoc
Labels: :book: Documentation, docs-content, 🏬 Release Branch

#4453 DDF-4445 Add Plugin support for location serialization
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.js
  ui/packages/catalog-ui-search/src/main/webapp/plugins/location-serialization.js
Labels: 🌊Impacts Downstream, 👤 UI

#4457 DDF-04456 Fixing point/rad and excess boolean ANDS
  ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.spec.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js
Labels: 👤 UI

#4183 [2.13.x] DDF-4432 Enforce CRLF for .cmd files
  .gitattributes
  distribution/ddf-common/src/main/resources/etc/certs/CertNew.cmd
Labels: 🏬 Release Branch, 👞Bug Fix, 👷‍♀️Build

#4409 DDF-04408 Adds faceting driven auto-complete to ui
  catalog/ui/catalog-ui-search/pom.xml
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/FacetAttributeAccessPlugin.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/FacetWhitelistConfiguration.java
  catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.facetwhitelist.xml
  catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/config/ConfigurationApplicationTest.java
  catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/forms/SearchFormsLoaderTest.java
  catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/forms/commands/SearchFormsManageCommandTest.java
  catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/FacetAttributePluginTest.java
  ui/packages/catalog-ui-search/src/main/webapp/component/filter-builder/filter-builder.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.collection.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/multivalue/multivalue.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/query/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/query/query.tsx
Labels: 👤 UI

#4406 DDF-04398 Add backend support for CSV export to DDF
  catalog/transformer/catalog-transformer-csv-queryresponse/src/main/java/ddf/catalog/transformer/csv/CsvMetacardTransformer.java
  catalog/transformer/catalog-transformer-csv-queryresponse/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/transformer/catalog-transformer-csv-queryresponse/src/test/java/ddf/catalog/transformer/csv/CsvMetacardTransformerTest.java
Labels: ✨New Feature

#4358 DDF-04357 Migrate metacard-interactions to react
  ui/packages/catalog-ui-search/src/main/webapp/component/component.less
  ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/metacard-interactions/dropdown.metacard-interactions.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/metacard-interactions/dropdown.metacard-interactions.less
  ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/metacard-interactions/dropdown.metacard-interactions.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-interactions/metacard-interactions.less
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-interactions/metacard-interactions.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-title/metacard-title.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-title/metacard-title.less
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-title/metacard-title.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/result-item/result-item.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/inspector/inspector.view.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-interactions/add-to-list-interaction.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-interactions/download-interaction.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-interactions/expand-interaction.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-interactions/export-interaction.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-interactions/hide-interaction.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-interactions/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-interactions/location-interaction.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-interactions/metacard-interactions-dropdown.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/metacard-interactions/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/metacard-interactions/metacard-interactions.tsx
Labels: 👤 UI, 🔨Refactor

#4387 DDF-04383 Prevent users from overriding the workspace sharing settings if another user has made changes
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/sharing/sharing.tsx
Labels: 👤 UI, 📈 Improvement

#4449 DDF-04448 Gazetteer Home button cleanup
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.less
  ui/packages/catalog-ui-search/src/main/webapp/react-component/button/split-button/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/button/split-button/zoomToHome.tsx
Labels: 👤 UI

#4425 DDF-04424 Fixed Denmark geojson (#122)
  distribution/ddf-common/src/main/resources/data/countries.geo.json
Labels: 📈 Improvement

#4468 DDF-4481 Add the IS EMPTY operator in search queries (REDO)
  distribution/docs/src/main/resources/content/_using/using-catalog-search-ui.adoc
  ui/packages/catalog-ui-search/src/main/webapp/component/announcement/announcements.jsx
  ui/packages/catalog-ui-search/src/main/webapp/component/filter-comparator/filter-comparator.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/filter/comparators.tsx
  ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.less
  ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.less
  ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js
  ui/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.js
  ui/packages/catalog-ui-search/src/main/webapp/js/cql.js
Labels: ✨New Feature, 👤 UI

#4461 DDF-04395 Fixes fraction displayed when uploading
  ui/packages/catalog-ui-search/src/main/webapp/component/ingest-details/ingest-details.view.js
Labels: 👞Bug Fix, 👤 UI

#4308 DDF-04303 Updated Intrigue configuration names to be consistent
  catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.email.xml
  catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.facetwhitelist.xml
  catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.query.monitor.impl.xml
  catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.querymonitor.xml
  catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.security.xml
  catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.theme.xml
  catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.transformer.blacklist.xml
  catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.whitelist.xml
  catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.xml
  distribution/docs/src/main/resources/content/_reference/_tables/EmailNotifier.adoc
  distribution/docs/src/main/resources/content/_reference/_tables/WorkspaceQueryService.adoc
  distribution/docs/src/main/resources/content/_reference/_tables/WorkspaceServiceImpl.adoc
  distribution/docs/src/main/resources/content/_reference/_tables/catalog.ui.adoc
  distribution/docs/src/main/resources/content/_reference/_tables/catalog.ui.attribute.aliases.adoc
  distribution/docs/src/main/resources/content/_reference/_tables/catalog.ui.attribute.descriptions.adoc
  distribution/docs/src/main/resources/content/_reference/_tables/catalog.ui.attribute.hidden.adoc
  distribution/docs/src/main/resources/content/_reference/_tables/catalog.ui.theme.adoc
  distribution/docs/src/main/resources/content/_reference/_tables/catalog.ui.whitelist.adoc
  distribution/docs/src/main/resources/content/_reference/_tables/ui.security.adoc
Labels: :book: Documentation, 📈 Improvement, 🔨Refactor

#4292 DDF-04291 Removed org.codice.ddf.ui.searchui.filter.RedirectServlet.config in favor of setting the property default in the class
  catalog/ui/search-ui-app/pom.xml
  catalog/ui/search-ui-app/src/main/resources/features.xml
  catalog/ui/search-ui-app/src/main/resources/org.codice.ddf.ui.searchui.filter.RedirectServlet.config
  catalog/ui/search-ui/search-redirect/pom.xml
  catalog/ui/search-ui/search-redirect/src/main/java/org/codice/ddf/ui/searchui/filter/RedirectConfiguration.java
  catalog/ui/search-ui/search-redirect/src/main/java/org/codice/ddf/ui/searchui/filter/RedirectServlet.java
  catalog/ui/search-ui/search-redirect/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/ui/search-ui/search-redirect/src/main/resources/OSGI-INF/metatype/metatype.xml
  catalog/ui/search-ui/search-redirect/src/test/groovy/org/codice/ddf/ui/searchui/filter/RedirectServletSpec.groovy
  distribution/docs/src/main/resources/content/_reference/_tables/RedirectServlet.adoc
Labels: 📈 Improvement

#4464 DDF-2824 updated documentation library
  Documentation-versions.html
  docs/architecture.html
  docs/architecture.pdf
  docs/developing.html
  docs/developing.pdf
  docs/integrating.html
  docs/integrating.pdf
  docs/introduction.html
  docs/introduction.pdf
  docs/managing.html
  docs/managing.pdf
  docs/metadata.html
  docs/metadata.pdf
  docs/quickstart.html
  docs/quickstart.pdf
  docs/reference.html
  docs/reference.pdf
  docs/using.html
  docs/using.pdf
Labels: :book: Documentation, 📈 Improvement

#4478 DDF-04474 Fixing Location Serialization Failures With Query Preservation & Clientside Filtering
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.spec.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/location/location.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/text-field/text-field.js
Labels: 👞Bug Fix, 👤 UI

#4310 DDF-04299: Refactored 'result-item.view' to allow for lazy thumbnail load
  ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/hover-preview/dropdown.hover-preview.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/hover-preview/dropdown.hover-preview.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/result-item/result-item.view.js
  ui/packages/catalog-ui-search/src/main/webapp/js/Common.js
  ui/packages/catalog-ui-search/src/main/webapp/js/Common.spec.js
Labels: 👤 UI, 📈 Improvement

#4434 DDF-04284 Poll interval configuration for OpensearchSource
  catalog/opensearch/catalog-opensearch-source/src/main/java/org/codice/ddf/opensearch/source/OpenSearchSource.java
  catalog/opensearch/catalog-opensearch-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/opensearch/catalog-opensearch-source/src/main/resources/OSGI-INF/metatype/metatype.xml
  distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSecurity.java
Labels: 📈 Improvement

#4480 DDF-04479 Fix Set Map Home Deferred Announcements
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js
Labels: 👞Bug Fix, 👤 UI

#4429 DDF-04426 Expands external host/port properties
  platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdmin.java
  platform/admin/core/admin-core-impl/src/test/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdminTest.java
  platform/admin/core/admin-core-impl/src/test/resources/custom.system.properties
Labels: 👞Bug Fix

#4490 [2.13.x] DDF-04486 Enforce the WFS sources' configured connect and receive timeouts
  catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/pom.xml
  catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/source/WfsSource.java
  catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/source/WfsSourceTest.java
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/pom.xml
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSourceTest.java
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/pom.xml
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsSource.java
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsSourceTest.java
Labels: 🏬 Release Branch, 👞Bug Fix

#4432 DDF-04426 [2.13.x] Expands external host/port properties
  platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdmin.java
  platform/admin/core/admin-core-impl/src/test/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdminTest.java
  platform/admin/core/admin-core-impl/src/test/resources/custom.system.properties
Labels: 👞Bug Fix

#4417 DDF-04374 updated docs for catalog rest endpoint
  distribution/docs/src/main/resources/content/_integrating/_endpoints/catalog-rest-endpoint.adoc
Labels: :book: Documentation, Integrator Docs Rewrite, docs-content

#4407 [2.13.x] DDF-1366 Updated the CSW Registry Store to not be registered as a FederatedSource service
  catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java
  catalog/spatial/registry/registry-api-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestRegistry.java
Labels: 🏬 Release Branch, 📈 Improvement

#4513 DDF-04486 Enforce the WFS sources' configured connect and receive timeouts
  catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/pom.xml
  catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/source/WfsSource.java
  catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/source/WfsSourceTest.java
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/pom.xml
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSourceTest.java
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/pom.xml
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsSource.java
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsSourceTest.java
Labels: 👞Bug Fix

#4521 DDF-04518 Cleared query attribute value when switching between attributes of different types
  ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js
Labels: 👤 UI

#4495 DDF-4494 Migrate theme-settings to react
  ui/packages/catalog-ui-search/src/main/webapp/component/component.less
  ui/packages/catalog-ui-search/src/main/webapp/component/theme-settings/theme-settings.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/theme-settings/theme-settings.less
  ui/packages/catalog-ui-search/src/main/webapp/component/theme-settings/theme-settings.view.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/theme-settings/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/theme-settings/theme-settings.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/user-settings/user-settings.tsx
Labels: 👤 UI

#4508 DDF-04507 Refactored filter-builder to use backbone model / collection
  catalog/ui/search-ui-app/src/main/resources/etc/org.codice.ddf.catalog.ui.attribute.hidden.config
  ui/packages/catalog-ui-search/src/main/webapp/component/filter-builder/filter-builder.js
  ui/packages/catalog-ui-search/src/main/webapp/component/filter-builder/filter-builder.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/filter-builder/filter-serialization.js
  ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.collection.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.js
  ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/result-filter/result-filter.view.js
Labels: 👤 UI

#4529 DDF-04528 Migrating metacard-overwrite to React
  ui/packages/catalog-ui-search/src/main/webapp/component/component.less
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-overwrite/metacard-overwrite.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-overwrite/metacard-overwrite.less
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-overwrite/metacard-overwrite.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/tabs/metacard/tabs-metacard.js
Labels: 👤 UI

#4502 [2.13.x] DDF-4457 Encrypt file system storage
  catalog/core/catalog-core-directorymonitor/pom.xml
  catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorIT.java
  catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/features/TinkFeatures.java
  catalog/core/catalog-core-localstorageprovider/pom.xml
  catalog/core/catalog-core-localstorageprovider/src/main/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProvider.java
  catalog/core/catalog-core-localstorageprovider/src/test/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProviderTest.java
  catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/DeleteOperations.java
  distribution/ddf-common/src/main/resources-filtered/etc/custom.properties
  distribution/ddf-common/src/main/resources/security/default.policy
  features/security/pom.xml
  features/test-utilities/src/main/feature/feature.xml
  platform/osgi/platform-osgi-configadmin/src/main/java/org/codice/felix/cm/file/EncryptingPersistenceManager.java
  platform/security/encryption/platform-security-encryption-crypter/pom.xml
  platform/security/encryption/platform-security-encryption-crypter/src/main/java/ddf/security/encryption/crypter/Crypter.java
  platform/security/encryption/platform-security-encryption-crypter/src/test/java/ddf/security/encryption/crypter/CrypterTest.java
Labels: :lock: Security, 🌊Impacts Downstream, 🏬 Release Branch, 📈 Improvement

#4421 DDF-4424 Updating the CDM (in-place) to update the observer state only on a successful ingest to the catalog framework
  catalog/catalog-app/src/main/resources/features.xml
  catalog/core/catalog-core-directorymonitor/pom.xml
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AbstractDurableFileConsumer.java
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AsyncFileAlterationListener.java
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AsyncFileAlterationObserver.java
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AsyncFileEntry.java
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileAlterationListener.java
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileSystemFileConsumer.java
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableWebDavFileConsumer.java
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/FileSystemPersistenceProvider.java
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/JsonPersistantStore.java
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ObjectPersistentStore.java
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/synchronizations/CompletionSynchronization.java
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/synchronizations/LoggingSynchronization.java
  catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/AsyncFileAlterationObserverTest.java
Labels: 📈 Improvement

#4504 DDF-3663 adds ability to export list of metacards to a KMZ file
  catalog/rest/catalog-rest-impl/pom.xml
  catalog/spatial/kml/spatial-kml-transformer/pom.xml
  catalog/spatial/kml/spatial-kml-transformer/src/main/java/org/codice/ddf/spatial/kml/actions/KmlActionProvider.java
  catalog/spatial/kml/spatial-kml-transformer/src/main/java/org/codice/ddf/spatial/kml/transformer/KmzTransformer.java
  catalog/spatial/kml/spatial-kml-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/spatial/kml/spatial-kml-transformer/src/test/java/org/codice/ddf/spatial/kml/transformer/KmzTransformerTest.java
  catalog/spatial/kml/spatial-kml-transformer/src/test/resources/multiPlacemark.kml
  distribution/docs/src/main/resources/content/_architectures/_transformers/kml-style-mapper.adoc
  pom.xml
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/results-export/results-export.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/table-export/table-export.tsx
Labels: 👤 UI

#4530 DDF-04374 updated docs for CSW endpoint
  distribution/docs/pom.xml
  distribution/docs/src/main/resources/content/_integrating/_endpoints/csw-endpoint.adoc
Labels: :book: Documentation, Integrator Docs Rewrite

#4516 DDF-04515 Fix Search Form Email Overflow Issue
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.view.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/workspace-item/workspace-item.tsx
Labels: 👤 UI

#4450 DDF-04447 Migrate the user-blacklist component to React
  ui/packages/catalog-ui-search/src/main/webapp/component/blacklist-item/blacklist-item.collection.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/blacklist-item/blacklist-item.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/blacklist-item/blacklist-item.less
  ui/packages/catalog-ui-search/src/main/webapp/component/blacklist-item/blacklist-item.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/component.less
  ui/packages/catalog-ui-search/src/main/webapp/component/user-blacklist/user-blacklist.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/user-blacklist/user-blacklist.less
  ui/packages/catalog-ui-search/src/main/webapp/component/user-blacklist/user-blacklist.view.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/BlacklistItem.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/User.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/blacklist-item/blacklist-item.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/blacklist-item/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/user-blacklist/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/user-blacklist/user-blacklist.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/blacklist-item/blacklist-item.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/blacklist-item/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/user-blacklist/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/user-blacklist/user-blacklist.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/user-settings/user-settings.tsx
Labels: 👤 UI

#4554 DDF-04553 added functionality for multi-zipped exports
  ui/packages/catalog-ui-search/src/main/webapp/component/query-interactions/query-interactions.view.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/results-export/results-export.tsx
Labels: ✨New Feature, 👤 UI

#4558 DDF-4557 Simplify empty queries window
  ui/packages/catalog-ui-search/src/main/webapp/component/query-selector/query-selector.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/query-selector/query-selector.view.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/map-settings/map-settings.tsx
Labels: 👤 UI, 📈 Improvement

#4542 DDF-04374 updated integrator documentation for the OpenSearch endpoint
  distribution/docs/src/main/resources/content/_integrating/_endpoints/opensearch-endpoint.adoc
Labels: :book: Documentation, Integrator Docs Rewrite

#4567 DDF-04566 The local query issued as part of a list search always fails
  ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js
Labels: 👞Bug Fix, 👤 UI

#4520 DDF-04517 Replace jarSigner with native security library for signing and verifying data exports
  catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/DumpCommand.java
  catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ExportCommand.java
  catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ImportCommand.java
  catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java
  catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/util/DigitalSignature.java
  catalog/core/catalog-core-commands/src/test/groovy/org/codice/ddf/commands/catalog/ExportCommandSpec.groovy
  catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/DumpCommandTest.java
  catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/IngestCommandTest.java
  catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/util/DigitalSignatureTest.java
  catalog/core/catalog-core-commands/src/test/resources/archive.zip
  catalog/core/catalog-core-commands/src/test/resources/example.zip
  catalog/core/catalog-core-commands/src/test/resources/keystore.jks
  catalog/transformer/catalog-transformer-zip/src/main/java/org/codice/ddf/catalog/transformer/zip/JarSigner.java
  catalog/transformer/catalog-transformer-zip/src/main/java/org/codice/ddf/catalog/transformer/zip/ZipDecompression.java
  catalog/transformer/catalog-transformer-zip/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/transformer/catalog-transformer-zip/src/test/java/org/codice/ddf/catalog/transformer/zip/JarSignerTest.java
  catalog/transformer/catalog-transformer-zip/src/test/java/org/codice/ddf/catalog/transformer/zip/ZipDecompressionTest.java
  platform/security/common/src/main/java/org/codice/ddf/security/common/Security.java
Labels: :lock: Security

#4503 DDF-04485 Migrate Visualization Selector to React
  ui/packages/catalog-ui-search/src/main/webapp/component/component.less
  ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/visualization-selector/dropdown.visualization-selector.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization-selector/visualization-selector.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization-selector/visualization-selector.less
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization-selector/visualization-selector.view.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/visualization-selector/visualization-selector.js
Labels: 👤 UI

#4571 [2.14.x] Fixes bug where installer would overwrite the solr password
  platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdmin.java
  platform/admin/core/admin-core-impl/src/test/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdminTest.java
  platform/admin/core/admin-core-impl/src/test/resources/custom.system.properties
Labels: 👞Bug Fix

#4484 DDF-04483 - Migrating User-notifications to React
  ui/packages/catalog-ui-search/src/main/webapp/component/component.less
  ui/packages/catalog-ui-search/src/main/webapp/component/user-notifications/user-notifications.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/user-notifications/user-notifications.less
  ui/packages/catalog-ui-search/src/main/webapp/component/user-notifications/user-notifications.view.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/navigation-right/navigation-right.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/user-notifications/user-notifications.js
Labels: 👤 UI

#4500 DDF-04498 migrate metacard-archive to react
  ui/packages/catalog-ui-search/src/main/webapp/component/component.less
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-archive/metacard-archive.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-archive/metacard-archive.less
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-archive/metacard-archive.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-title/metacard-title.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/tabs/metacard/tabs-metacard.js
  ui/packages/catalog-ui-search/src/main/webapp/component/tabs/metacards/tabs-metacards.js
  ui/packages/catalog-ui-search/src/main/webapp/component/tabs/tabs.less
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/loading-companion/loading-companion.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-archive/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-archive/metacard-archive.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/metacard-archive/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/metacard-archive/metacard-archive.tsx
Labels: 👤 UI

#4458 DDF-4461 Migrate Map Components to React - map-info.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/component.less
  ui/packages/catalog-ui-search/src/main/webapp/component/map-info/map-info.less
  ui/packages/catalog-ui-search/src/main/webapp/component/map-info/map-info.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/map-info/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/map-info/map-info.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/map-info/formatting.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/map-info/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/map-info/map-info.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/left-pad/leftpad.spec.js
  ui/packages/catalog-ui-search/tsconfig.json
Labels: 👤 UI, 🔨Refactor

#4577 DDF-4570 Fixes installer overriding solr password
  platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdmin.java
  platform/admin/core/admin-core-impl/src/test/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdminTest.java
  platform/admin/core/admin-core-impl/src/test/resources/custom.system.properties
Labels: 👞Bug Fix

#4578 [2.13.x] DDF-4570 Fixes installer overriding solr password
  platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdmin.java
  platform/admin/core/admin-core-impl/src/test/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdminTest.java
  platform/admin/core/admin-core-impl/src/test/resources/custom.system.properties
Labels: 👞Bug Fix

#4536 DDF-04533 Migrate list-create to React
  ui/packages/catalog-ui-search/src/main/webapp/component/component.less
  ui/packages/catalog-ui-search/src/main/webapp/component/list-create/list-create.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/list-create/list-create.js
  ui/packages/catalog-ui-search/src/main/webapp/component/list-create/list-create.less
  ui/packages/catalog-ui-search/src/main/webapp/component/list-create/list-create.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/list-editor/list-editor.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/list-editor/list-editor.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/list-item/list-item.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/list-select/list-select.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/result-add/result-add.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/workspace-lists/workspace-lists.view.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/list-create/index.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/list-create/list-create.js
Labels: 👤 UI

#4547 DDF-4457 Encrypt file system storage
  catalog/core/catalog-core-directorymonitor/pom.xml
  catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorIT.java
  catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/features/TinkFeatures.java
  catalog/core/catalog-core-localstorageprovider/pom.xml
  catalog/core/catalog-core-localstorageprovider/src/main/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProvider.java
  catalog/core/catalog-core-localstorageprovider/src/test/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProviderTest.java
  catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/DeleteOperations.java
  distribution/ddf-common/src/main/resources-filtered/etc/custom.properties
  distribution/ddf-common/src/main/resources/security/default.policy
  features/security/pom.xml
  features/test-utilities/pom.xml
  features/test-utilities/src/main/feature/feature.xml
  platform/osgi/platform-osgi-configadmin/src/main/java/org/codice/felix/cm/file/EncryptingPersistenceManager.java
  platform/security/encryption/platform-security-encryption-crypter/pom.xml
  platform/security/encryption/platform-security-encryption-crypter/src/main/java/ddf/security/encryption/crypter/Crypter.java
  platform/security/encryption/platform-security-encryption-crypter/src/test/java/ddf/security/encryption/crypter/CrypterTest.java
Labels: :lock: Security

#4560 DDF-04559 Defaulting time to 00:00:00 when changing date in date picker
  ui/packages/catalog-ui-search/src/main/webapp/component/input/date/input-date.view.js
Labels: 👤 UI

#4544 DDF-04543 Upgrade tika bundle version
  pom.xml
Labels: ⬆️ Dependency Upgrade

#4455 DDF-04437 DDF-04454 Migrate metacard-actions / map-actions to React
  ui/packages/catalog-ui-search/src/main/webapp/component/component.less
  ui/packages/catalog-ui-search/src/main/webapp/component/map-actions/map-actions.less
  ui/packages/catalog-ui-search/src/main/webapp/component/map-actions/map-actions.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-actions/metacard-actions.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-actions/metacard-actions.less
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-actions/metacard-actions.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/tabs/metacard/tabs-metacard.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/map-actions/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/map-actions/map-actions.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-actions/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-actions/metacard-actions.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/map-actions/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/map-actions/map-actions.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/metacard-actions/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/metacard-actions/metacard-actions.tsx
Labels: 👤 UI, 🔨Refactor

#4523 DDF-04522 migrate metacard-quality to react
  ui/packages/catalog-ui-search/src/main/webapp/component/component.less
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-quality/metacard-quality.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-quality/metacard-quality.less
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-quality/metacard-quality.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/tabs/metacard/tabs-metacard.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-quality/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-quality/metacard-quality.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/metacard-quality/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/metacard-quality/metacard-quality.tsx
Labels: 👤 UI, 🔨Refactor

#4497 DDF-04496 Migrate metacard-history to React
  ui/packages/catalog-ui-search/src/main/webapp/component/component.less
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-history/metacard-history.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-history/metacard-history.less
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-history/metacard-history.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/tabs/metacard/tabs-metacard.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-history/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-history/metacard-history.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/metacard-history/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/metacard-history/metacard-history.tsx
Labels: 👤 UI

#4549 DDF-0000 Make pressing enter in the login password field submit a sig…
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/user/user.tsx
Labels: 👤 UI

#4505 DDF-04470 Migrating map-context-menu.view.js to React.
  ui/packages/catalog-ui-search/src/main/webapp/component/map-context-menu/map-context-menu.less
  ui/packages/catalog-ui-search/src/main/webapp/component/map-context-menu/map-context-menu.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/tabs/metacard/tabs-metacard.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/histogram/histogram.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/histogram/histogram.less
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/histogram/histogram.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/inspector/inspector.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/inspector/inspector.less
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/inspector/inspector.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.model.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/histogram/index.spec.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/histogram/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/menu/menu.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/copy-coordinates/copy-coordinates.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/map-context-menu/index.tsx
Labels: 👤 UI

#4605 DDF-4604 Added right border to result items
  ui/packages/catalog-ui-search/src/main/webapp/styles/components/list.less
Labels: 👤 UI

#4599 DDF-4598 Add onClick support to card.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/card/card.tsx
Labels: 👤 UI
