Repository codice/ddf, pull requests merged in 2019-07, with the labels that each got.

#5039 DDF-5038 Correct the Solr documentation
  distribution/docs/src/main/resources/content/_managing/_configuring/hardening-solr.adoc
  distribution/docs/src/main/resources/content/_managing/_configuring/solr-admin-ui.adoc
Labels: :book: Documentation

#5030 DDF-5022 Fix dropdown left/right calculation
  ui/packages/catalog-ui-search/src/main/webapp/behaviors/dropdown.behavior.utility.js
Labels: 👤 UI

#5029 DDF-5028 Add no-cache default to fetch
  ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/fetch/fetch.tsx
Labels: 👤 UI

#5032 DDF-5007 Add flexbox to get rid of empty space
  ui/packages/catalog-ui-search/src/main/webapp/component/content/content.view.js
Labels: 👤 UI

#4965 DDF-4952 Improve Search UI
  ui/packages/catalog-ui-search/src/main/webapp/dev/component/input-guide/input-guide.view.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/input-wrappers/autocomplete/autocomplete.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/input-wrappers/base/base.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/location/keyword.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/save-button/save-button.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/workspace-menu/workspace-menu.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/workspace-title/workspace-title.tsx
Labels: 👤 UI

#5027 DDF-05019 Updated theme font sizes
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/theme-container/theme-container.tsx
  ui/packages/catalog-ui-search/src/main/webapp/styles/vars.less
Labels: 👤 UI

#5073 DDF-5071 Remove old css
  ui/packages/catalog-ui-search/src/main/webapp/css/searchPage.css
Labels: 👞Bug Fix, 👤 UI

#5005 DDF-5004 Added extensibility to filters to accept a subset of attributes
  ui/packages/catalog-ui-search/src/main/webapp/component/filter-builder/filter-builder.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.collection.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-editor/query-editor.view.js
Labels: 👤 UI

#4979 DDF-04955 Implements initial API driven e2e testing
  ui/README.md
  ui/package.json
  ui/packages/catalog-admin-module-layout/package.json
  ui/packages/catalog-admin-module-maplayers/package.json
  ui/packages/catalog-ui-search-e2e/README.md
  ui/packages/catalog-ui-search-e2e/flow.svg
  ui/packages/catalog-ui-search-e2e/package.json
  ui/packages/catalog-ui-search-e2e/src/main/webapp/index.html
  ui/packages/catalog-ui-search-e2e/src/main/webapp/index.js
  ui/packages/catalog-ui-search-e2e/src/main/webapp/intrigue-basic-query.json
  ui/packages/catalog-ui-search-e2e/src/main/webapp/intrigue.spec.js
  ui/packages/catalog-ui-search-e2e/wait-for-intrigue.js
  ui/packages/catalog-ui-search/package.json
  ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js
  ui/packages/catalog-ui-search/src/main/webapp/extension-points/navigator/navigator.tsx
  ui/packages/catalog-ui-search/src/main/webapp/js/ApplicationStart.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/dropdown/dropdown.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/navigation-left/navigation-left.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/workspace-interactions/workspace-interactions.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/workspace-item/workspace-item.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/workspace-menu/workspace-menu.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/workspaces-items/workspaces-items.tsx
  ui/packages/imperio/driver.js
  ui/packages/imperio/index.js
  ui/packages/imperio/monitor.js
  ui/packages/imperio/package.json
  ui/pom.xml
  ui/yarn.lock
Labels: 👀 Verified, 👤 UI

#5075 [2.16.x] DDF-5071 Remove old css
  ui/packages/catalog-ui-search/src/main/webapp/css/searchPage.css
Labels: 👤 UI

#5074 DDF-2824 added conditional to docs templates
  distribution/docs/src/main/resources/templates/architectures.ftl
  distribution/docs/src/main/resources/templates/developing.ftl
  distribution/docs/src/main/resources/templates/documentation.ftl
  distribution/docs/src/main/resources/templates/integrating.ftl
  distribution/docs/src/main/resources/templates/managing.ftl
  distribution/docs/src/main/resources/templates/metadata.ftl
  distribution/docs/src/main/resources/templates/overview.ftl
  distribution/docs/src/main/resources/templates/quickstart.ftl
  distribution/docs/src/main/resources/templates/reference.ftl
  distribution/docs/src/main/resources/templates/using.ftl
Labels: :book: Documentation, docs-automation, 👞Bug Fix, 👷‍♀️Build

#5087 DDF-04955 Adds imperio to exported packages for downstream projects
  ui/packages.xml
Labels: 👤 UI

#5060 DDF-05058 Refactors navigation-right to be extensible via extension points
  ui/packages/catalog-ui-search/src/main/webapp/extension-points/extension-points.tsx
  ui/packages/catalog-ui-search/src/main/webapp/extension-points/navigation-right/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/extension-points/navigation-right/navigation-right.tsx
  ui/packages/catalog-ui-search/src/main/webapp/js/Entry.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/navigation-right/buttons.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/navigation-right/navigation-right.tsx
Labels: 👤 UI

#5070 DDF-05055 Fix value retention across filter comparators
  ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js
Labels: 👤 UI

#5078 DDF-5067 React upgrade types
  ui/packages/catalog-ui-search/package.json
  ui/packages/catalog-ui-search/src/main/webapp/react-component/menu/menu.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/button-behavior/button-behavior.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/card/card.tsx
  ui/packages/ui/package.json
  ui/yarn.lock
Labels: 👤 UI

#5082 DDF-5031 reordered user guide sections
  distribution/docs/src/main/resources/content/_using/lists.adoc
  distribution/docs/src/main/resources/content/_using/notifications.adoc
  distribution/docs/src/main/resources/content/_using/results-forms.adoc
  distribution/docs/src/main/resources/content/_using/search-forms.adoc
  distribution/docs/src/main/resources/content/_using/search.adoc
  distribution/docs/src/main/resources/content/_using/ui-settings.adoc
  distribution/docs/src/main/resources/content/_using/ui-uploading.adoc
  distribution/docs/src/main/resources/content/_using/using-intrigue-intro.adoc
  distribution/docs/src/main/resources/content/_using/using-intro.adoc
  distribution/docs/src/main/resources/content/_using/using-landing-page.adoc
  distribution/docs/src/main/resources/content/_using/using-simple-search-ui.adoc
  distribution/docs/src/main/resources/content/_using/viewing-sources.adoc
  distribution/docs/src/main/resources/content/_using/workspaces.adoc
  distribution/docs/src/main/resources/templates/build/using.ftl
  distribution/docs/src/main/resources/templates/using.ftl
Labels: :book: Documentation, docs-automation, 📈 Improvement

#5121 DDF-04955 Update how imperio finds dom nodes to fix issues with functional components
  ui/packages/imperio/driver.js
Labels: 👤 UI

#5114 DDF-05113 Bugfix Clearing User's Default Search Form
  ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js
Labels: 👤 UI

#5106 DDF-5079 Filter attributes in views instead of query
  ui/packages/catalog-ui-search/src/main/webapp/component/table/results/table-results.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/row.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/table-rearrange.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/table-visibility.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/table-viz.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/tbody.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/thead.view.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResponse.js
Labels: 👤 UI

#5103 DDF-5102 Allow more extension of user-settings.
  ui/packages/catalog-ui-search/src/main/webapp/plugins/user-settings.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/user-settings/extensions.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/user-settings/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/user-settings/user-settings.tsx
Labels: 👤 UI

#5146 DDF-04759 updated project site for 2.13.10 release
  Documentation-versions.html
  index.html
Labels: :book: Documentation, docs-content
