Repository codice/ddf, pull requests merged in 2019-04, with the labels that each got.

#4525 DDF-04524 Enabling Warning Message on Export Results (All)
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/input-wrappers/number/number.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/table-export/table-export.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/table-export/table-export.tsx
Labels: 👤 UI

#4575 DDF-4552 Migrate search-settings to React
  ui/packages/catalog-ui-search/src/main/webapp/component/component.less
  ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/search-settings/dropdown.search-settings.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-settings/search-settings.less
  ui/packages/catalog-ui-search/src/main/webapp/component/search-settings/search-settings.view.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/about/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/search-settings/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/search-settings/search-settings.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/user-settings/user-settings.tsx
Labels: 👤 UI, 🔨Refactor

#4596 DDF-4581 Fix Between Time Filter
  ui/packages/catalog-ui-search/src/main/webapp/component/between-time/between-time.view.js
Labels: 👞Bug Fix, 👤 UI

#4595 DDF-4594 Added ability to perform an action on multiple selected items
  ui/packages/catalog-ui-search/src/main/webapp/component/component.less
  ui/packages/catalog-ui-search/src/main/webapp/component/content/content.less
  ui/packages/catalog-ui-search/src/main/webapp/component/content/content.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/result-item/result-item.view.js
  ui/packages/catalog-ui-search/src/main/webapp/plugins/multi-select-actions.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/multi-select-actions/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/multi-select-actions/multi-select-actions.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/results-export/results-export.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/multi-select-actions/index.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/multi-select-actions/multi-select-actions.tsx
Labels: ✨New Feature, 👤 UI

#4537 DDF-04321 Fix downstream CDM itest performance/timeout issues
  catalog/catalog-app/src/main/resources/features.xml
  catalog/core/catalog-core-directorymonitor/pom.xml
  catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorIT.java
  catalog/transformer/catalog-transformer-bootflag/pom.xml
  catalog/transformer/catalog-transformer-bootflag/src/main/java/org/codice/ddf/catalog/transformer/bootflag/InputTransformerBootServiceFlag.java
  catalog/transformer/catalog-transformer-bootflag/src/test/java/org/codice/ddf/catalog/transformer/bootflag/InputTransformerBootServiceFlagTest.java
  distribution/ddf-common/src/main/resources/etc/transformers/README.md
  distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
  distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/ServiceManagerImpl.java
Labels: :microscope: Test Improvements

#4600 DDF-4597 Added backend capability to re-query off spellcheck suggestions
  catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java
  catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrMetacardClientImplTest.java
Labels: ✨New Feature

#4493 Update the paging to be entirely server side
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java
  catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.xml
  catalog/ui/search-ui-app/src/main/resources/etc/org.codice.ddf.catalog.ui.config
  distribution/docs/src/main/resources/content/_reference/_tables/catalog.ui.adoc
  ui/packages/catalog-admin-module-layout/src/main/webapp/default-layout/test-data/config.json
  ui/packages/catalog-ui-search/.stylelintrc
  ui/packages/catalog-ui-search/package.json
  ui/packages/catalog-ui-search/src/main/webapp/behaviors/selection.behavior.js
  ui/packages/catalog-ui-search/src/main/webapp/component/alert/alert.js
  ui/packages/catalog-ui-search/src/main/webapp/component/association/association.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/component.less
  ui/packages/catalog-ui-search/src/main/webapp/component/content/content.js
  ui/packages/catalog-ui-search/src/main/webapp/component/map-context-menu/map-context-menu.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard/metacard.js
  ui/packages/catalog-ui-search/src/main/webapp/component/paging/paging.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/paging/paging.less
  ui/packages/catalog-ui-search/src/main/webapp/component/paging/paging.tsx
  ui/packages/catalog-ui-search/src/main/webapp/component/paging/paging.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-feed/query-feed.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-feedback/query-feedback.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/result-group/result-group.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/result-group/result-group.less
  ui/packages/catalog-ui-search/src/main/webapp/component/result-group/result-group.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/result-indicator/result-indicator.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/result-indicator/result-indicator.less
  ui/packages/catalog-ui-search/src/main/webapp/component/result-indicator/result-indicator.tsx
  ui/packages/catalog-ui-search/src/main/webapp/component/result-indicator/result-indicator.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/result-item/result-item.collection.less
  ui/packages/catalog-ui-search/src/main/webapp/component/result-item/result-item.collection.tsx
  ui/packages/catalog-ui-search/src/main/webapp/component/result-item/result-item.collection.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.less
  ui/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/selection-interface/selection-interface.model.js
  ui/packages/catalog-ui-search/src/main/webapp/component/tabs/workspace-content/tabs-workspace-content.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/upload/upload.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/histogram/histogram.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResponse.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResult.collection.js
  ui/packages/catalog-ui-search/src/main/webapp/js/model/ResultSort.js
  ui/packages/catalog-ui-search/src/main/webapp/js/properties.js
  ui/packages/catalog-ui-search/src/main/webapp/js/store.js
  ui/yarn.lock
Labels: 👤 UI, 📈 Improvement

#4633 [hotfix] DDF-4457-hotfix Fixes file system encryption issues introduced by #4502 (#4633)
  catalog/core/catalog-core-localstorageprovider/src/main/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProvider.java
  platform/security/encryption/platform-security-encryption-crypter/src/main/java/ddf/security/encryption/crypter/Crypter.java
Labels: 🔥HotFix

#4564 [2.13.x]DDF-4548 Update docs for enforced validator plugin
  distribution/docs/src/main/resources/content/_running/editing-attributes.adoc
  distribution/docs/src/main/resources/content/_running/injecting-attributes.adoc
  distribution/docs/src/main/resources/content/_running/overriding-attributes.adoc
  distribution/docs/src/main/resources/content/_running/validator-plugins.adoc
  distribution/docs/src/main/resources/content/_running/viewing-invalid.adoc
Labels: :book: Documentation

#4624 DDF-4623 Preventing workspaces from being created from unparsable queries
  ui/packages/catalog-ui-search/src/main/webapp/js/model/Workspace.collection.js
Labels: 👤 UI

#4611 DDF-4610 Add checkboxes to result-item and table view to simplify multi-select
  ui/packages/catalog-ui-search/src/main/webapp/behaviors/selection.behavior.js
  ui/packages/catalog-ui-search/src/main/webapp/component/result-item/result-item.less
  ui/packages/catalog-ui-search/src/main/webapp/component/result-item/result-item.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.less
  ui/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/selection-checkbox/selection-checkbox.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/row.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/row.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/thead.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/thead.less
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/thead.view.js
Labels: ✨New Feature, 👤 UI

#4653 DDF-04647 Fix bug preventing users from changing search forms
  ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form-list/search-form-list.view.js
Labels: 👞Bug Fix, 👤 UI

#4685 DDF-4683 Remove 'Anyway' from warning module in UI Lite
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/low-bandwidth-map/low-bandwidth-map.hbs
Labels: 👤 UI

#4665 DDF-04657 Improve search form selection UX
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form-list/search-form-list.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-interactions/search-interactions.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/search-interactions/search-interactions.less
Labels: 👤 UI, 📈 Improvement

#4681 DDF-4676 Adding ID to sources endpoint for actions and updated source action provider
  catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/rest/catalog-rest-impl/src/main/java/org/codice/ddf/rest/impl/CatalogServiceImpl.java
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/source-item/source-item.tsx
Labels: 👤 UI

#4695 DDF-04481 Removed CAS protocol support through filters
  README.md
  distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-token-service.adoc
  distribution/docs/src/main/resources/content/_managing/_configuring/configuring-cas.adoc
  distribution/docs/src/main/resources/content/_managing/_configuring/feature-commands.adoc
  distribution/docs/src/main/resources/content/_managing/_configuring/remove-default-users-cont.adoc
  distribution/docs/src/main/resources/content/_managing/_configuring/remove-default-users.adoc
  distribution/docs/src/main/resources/content/_managing/_configuring/securing-admin-console.adoc
  distribution/docs/src/main/resources/content/_managing/_configuring/updating-system-users.adoc
  distribution/docs/src/main/resources/content/_managing/_configuring/web-context-policy-manager.adoc
  distribution/docs/src/main/resources/content/_managing/_securing/disallowing-login-wo-certs.adoc
  distribution/docs/src/main/resources/content/_reference/_appReferences/mg-security.adoc
  distribution/docs/src/main/resources/content/_reference/_dependencyList/ddf-dependency-list.adoc
  distribution/docs/src/main/resources/images/cas-integration.png
  distribution/sdk/ddf-sso-query-widget/pom.xml
  distribution/sdk/ddf-sso-query-widget/src/main/java/org/codice/ddf/ui/Query.java
  distribution/sdk/ddf-sso-query-widget/src/main/java/org/codice/ddf/ui/QueryForm.java
  distribution/sdk/ddf-sso-query-widget/src/main/resources/OSGI-INF/blueprint/casfilters.xml
  distribution/sdk/ddf-sso-query-widget/src/main/resources/OSGI-INF/blueprint/widget.xml
  distribution/sdk/ddf-sso-widget/pom.xml
  distribution/sdk/ddf-sso-widget/src/main/java/org/codice/ddf/ui/ExampleSSOWidget.java
  distribution/sdk/ddf-sso-widget/src/main/resources/OSGI-INF/blueprint/casfilters.xml
  distribution/sdk/ddf-sso-widget/src/main/resources/OSGI-INF/blueprint/widget.xml
  distribution/sdk/pom.xml
  features/security/pom.xml
  features/security/src/main/feature/feature.xml
  platform/security/cas/pom.xml
  platform/security/cas/security-cas-client/pom.xml
  platform/security/cas/security-cas-client/src/main/java/org/codice/ddf/security/handler/cas/CASAuthenticationToken.java
  platform/security/cas/security-cas-client/src/main/java/org/codice/ddf/security/handler/cas/CasHandler.java
  platform/security/cas/security-cas-client/src/main/java/org/codice/ddf/security/handler/cas/CasLogoutAction.java
  platform/security/cas/security-cas-client/src/main/java/org/codice/ddf/security/handler/cas/CasLogoutService.java
  platform/security/cas/security-cas-client/src/main/java/org/codice/ddf/security/handler/cas/CasProxyTicketValidator.java
  platform/security/cas/security-cas-client/src/main/java/org/codice/ddf/security/handler/cas/filter/FilteredRequest.java
  platform/security/cas/security-cas-client/src/main/java/org/codice/ddf/security/handler/cas/filter/ProxyFilter.java
  platform/security/cas/security-cas-client/src/main/java/org/codice/ddf/security/handler/cas/filter/ProxyFilterChain.java
  platform/security/cas/security-cas-client/src/main/resources/OSGI-INF/blueprint/casfilters.xml
  platform/security/cas/security-cas-client/src/main/resources/OSGI-INF/metatype/metatype.xml
  platform/security/cas/security-cas-client/src/test/java/org/codice/ddf/security/handler/cas/CasHandlerTest.java
  platform/security/cas/security-cas-client/src/test/java/org/codice/ddf/security/handler/cas/CasLogoutServiceTest.java
  platform/security/cas/security-cas-client/src/test/java/org/codice/ddf/security/handler/cas/FilteredRequestTest.java
  platform/security/cas/security-cas-client/src/test/resources/logback-test.xml
  platform/security/cas/security-cas-impl/pom.xml
  platform/security/cas/security-cas-impl/src/main/java/ddf/security/service/impl/cas/CASTokenRequestHandler.java
  platform/security/cas/security-cas-impl/src/main/java/ddf/security/service/impl/cas/CasAuthenticationToken.java
  platform/security/cas/security-cas-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  platform/security/cas/security-cas-impl/src/test/java/ddf/security/service/impl/cas/CASAuthenticationTokenTest.java
  platform/security/cas/security-cas-impl/src/test/java/ddf/security/service/impl/cas/CASTokenRequestHandlerTest.java
  platform/security/cas/security-cas-tokenvalidator/pom.xml
  platform/security/cas/security-cas-tokenvalidator/src/main/java/ddf/security/cas/WebSSOTokenValidator.java
  platform/security/cas/security-cas-tokenvalidator/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  platform/security/cas/security-cas-tokenvalidator/src/main/resources/OSGI-INF/metatype/metatype.xml
  platform/security/pom.xml
  platform/security/sts/pom.xml
  platform/security/sts/security-sts-casclaimshandler/pom.xml
  platform/security/sts/security-sts-casclaimshandler/src/main/java/org/codice/ddf/security/claims/cas/CasClaimsHandler.java
  platform/security/sts/security-sts-casclaimshandler/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  platform/security/sts/security-sts-casclaimshandler/src/main/resources/OSGI-INF/metatype/metatype.xml
  platform/security/sts/security-sts-casclaimshandler/src/test/java/org/codice/ddf/security/claims/cas/CasClaimsHandlerTest.java
  platform/security/sts/security-sts-server/pom.xml
  pom.xml
Labels: :lock: Security

#4696 DDF-04702 Resolve 'createdBy is not defined' console error that occurs…
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.view.js
Labels: 👞Bug Fix, 👤 UI

#4626 DDF-4625 Search From Location to Persist Filters
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-interactions/location-interaction.tsx
Labels: 👤 UI

#4708 DDF-04706 Adding mapLoaded event trigger.
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js
Labels: 👤 UI

#4663 DDF-4570 Persist updated Solr password
  catalog/core/catalog-core-standardframework/pom.xml
  catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/fedstrategy.xml
  catalog/solr/catalog-solr-provider/pom.xml
  catalog/solr/catalog-solr-provider/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  features/admin/src/main/feature/feature.xml
  features/solr/pom.xml
  platform/admin/core/admin-core-impl/pom.xml
  platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdmin.java
  platform/admin/core/admin-core-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  platform/persistence/platform-persistence-core-impl/pom.xml
  platform/persistence/platform-persistence-core-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  platform/solr/solr-factory/pom.xml
  platform/solr/solr-factory/src/main/java/org/codice/solr/factory/impl/HttpSolrClientFactory.java
  platform/solr/solr-factory/src/test/groovy/org/codice/solr/factory/impl/HttpSolrClientFactorySpec.groovy
  platform/solr/solr-password/pom.xml
  platform/solr/solr-password/src/main/java/ddf/platform/solr/security/SolrPasswordUpdate.java
  platform/solr/solr-password/src/main/java/ddf/platform/solr/security/SolrPasswordUpdateImpl.java
  platform/solr/solr-password/src/test/groovy/SolrPasswordUpdateSpec.groovy
Labels: 📈 Improvement

#4697 DDF-4469 Address react workspace unique key js warnings in console
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/workspaces-items/workspaces-items.tsx
Labels: 👞Bug Fix, 👤 UI

#4721 DDF-4716 Fix WFS 1.1.0 source's metatype.xml
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/pom.xml
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/resources/OSGI-INF/metatype/metatype.xml
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSourceTest.java
  catalog/spatial/wfs/spatial-wfs-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/common/AbstractWfsSource.java
Labels: 👞Bug Fix

#4723 [2.13.X] DDF-4722 removed experimental label in docs
  catalog/spatial/registry/registry-api/src/main/java/org/codice/ddf/registry/api/internal/RegistryStore.java
  distribution/docs/src/main/resources/content/_data/json-definition-intro.adoc
  distribution/docs/src/main/resources/content/_sources/registry-store.adoc
Labels: :book: Documentation, docs-content, 👞Bug Fix

#4690 DDF-4689 Add backend support for sorting searches
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/QueryMetacardApplication.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/query/data/metacard/QueryMetacardTypeImpl.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/transformer/impl/AssociatedQueryMetacardsHandler.java
  distribution/docs/src/main/resources/content/_integrating/_endpoints/query-endpoints.adoc
Labels: ✨New Feature

#4693 DDF-04692 Inspector view now exports multiple results
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-interactions/export-interaction.tsx
Labels: 👞Bug Fix

#4744 DDF-2824 removed incorrectly encoded characters from documentation.
  distribution/docs/src/main/resources/content/_tables/OpenSearchSource.adoc
  distribution/docs/src/main/resources/content/_transformers/kml-metacard-xformer.adoc
  distribution/docs/src/main/resources/content/_transformers/kml-queryresp-xformer.adoc
  distribution/docs/src/main/resources/content/_transformers/kml-style-mapper.adoc
Labels: :book: Documentation, 🌊Impacts Downstream, 👞Bug Fix, 👷‍♀️Build

#4760 DDF-4759 update product website for 2.13.9 release
  Documentation-versions.html
  index.html
Labels: :book: Documentation, 🌊Impacts Downstream, 🏬 Release Branch

#4753 [2.14.x] DDF-2824 removed incorrectly encoded characters from documentation.
  distribution/docs/src/main/resources/content/_architectures/_transformers/kml-metacard-xformer.adoc
  distribution/docs/src/main/resources/content/_architectures/_transformers/kml-queryresp-xformer.adoc
  distribution/docs/src/main/resources/content/_architectures/_transformers/kml-style-mapper.adoc
  distribution/docs/src/main/resources/content/_reference/_tables/OpenSearchSource.adoc
Labels: :book: Documentation, 🌊Impacts Downstream, 🏬 Release Branch, 👞Bug Fix, 👷‍♀️Build

#4754 DDF-2824 removed incorrectly encoded characters from documentation.
  distribution/docs/src/main/resources/content/_architectures/_transformers/kml-metacard-xformer.adoc
  distribution/docs/src/main/resources/content/_architectures/_transformers/kml-queryresp-xformer.adoc
  distribution/docs/src/main/resources/content/_architectures/_transformers/kml-style-mapper.adoc
  distribution/docs/src/main/resources/content/_reference/_tables/OpenSearchSource.adoc
Labels: :book: Documentation, 🌊Impacts Downstream, 👞Bug Fix, 👷‍♀️Build

#4616 DDF-04614 Fixing subscription removal
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java
  ui/packages/catalog-ui-search/src/main/webapp/react-component/container/sharing/sharing.tsx
Labels: 👤 UI

#4707 [2.13.x] DDF-4703 updated docs module to add version checking
  distribution/docs/pom.xml
  distribution/docs/src/main/resources/templates/architectures.ftl
  distribution/docs/src/main/resources/templates/build/integrating.ftl
  distribution/docs/src/main/resources/templates/developing.ftl
  distribution/docs/src/main/resources/templates/documentation.ftl
  distribution/docs/src/main/resources/templates/integrating.ftl
  distribution/docs/src/main/resources/templates/managing.ftl
  distribution/docs/src/main/resources/templates/metadata.ftl
  distribution/docs/src/main/resources/templates/overview.ftl
  distribution/docs/src/main/resources/templates/quickstart.ftl
  distribution/docs/src/main/resources/templates/reference.ftl
  distribution/docs/src/main/resources/templates/using.ftl
Labels: :book: Documentation, 👞Bug Fix, 👷‍♀️Build

#4712 [2.14.x] DDF-4703 updated docs module to add version checking
  distribution/docs/pom.xml
  distribution/docs/src/main/resources/templates/architectures.ftl
  distribution/docs/src/main/resources/templates/build/integrating.ftl
  distribution/docs/src/main/resources/templates/developing.ftl
  distribution/docs/src/main/resources/templates/documentation.ftl
  distribution/docs/src/main/resources/templates/integrating.ftl
  distribution/docs/src/main/resources/templates/managing.ftl
  distribution/docs/src/main/resources/templates/metadata.ftl
  distribution/docs/src/main/resources/templates/overview.ftl
  distribution/docs/src/main/resources/templates/quickstart.ftl
  distribution/docs/src/main/resources/templates/reference.ftl
  distribution/docs/src/main/resources/templates/using.ftl
Labels: :book: Documentation, 🌊Impacts Downstream, 👞Bug Fix, 👷‍♀️Build

#4713 DDF-4703 updated docs module to add version checking
  distribution/docs/pom.xml
  distribution/docs/src/main/resources/templates/architectures.ftl
  distribution/docs/src/main/resources/templates/build/integrating.ftl
  distribution/docs/src/main/resources/templates/developing.ftl
  distribution/docs/src/main/resources/templates/documentation.ftl
  distribution/docs/src/main/resources/templates/integrating.ftl
  distribution/docs/src/main/resources/templates/managing.ftl
  distribution/docs/src/main/resources/templates/metadata.ftl
  distribution/docs/src/main/resources/templates/overview.ftl
  distribution/docs/src/main/resources/templates/quickstart.ftl
  distribution/docs/src/main/resources/templates/reference.ftl
  distribution/docs/src/main/resources/templates/using.ftl
Labels: :book: Documentation, 👞Bug Fix, 👷‍♀️Build

#4643 DDF-4642 Update FeatureMetacardType to handle simpleTypes and simpleContent to arbitrary depths
  catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-common/src/test/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/common/FeatureMetacardTypeTest.java
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-common/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/common/FeatureMetacardTypeTest.java
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-common/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/common/FeatureMetacardTypeTest.java
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-converter/pom.xml
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-converter/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/converter/impl/GenericFeatureConverterTest.java
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-converter/src/test/resources/states.xsd
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-converter/src/test/resources/video_data_set.xsd
  catalog/spatial/wfs/spatial-wfs-common/pom.xml
  catalog/spatial/wfs/spatial-wfs-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/common/FeatureMetacardType.java
  catalog/spatial/wfs/spatial-wfs-common/src/test/java/org/codice/ddf/spatial/ogc/wfs/catalog/common/FeatureMetacardTypeTest.java
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/dateAndDateTimeProperties.xsd
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/elementOfFeatureTypeIsComplexTypeSimpleContentExtensionAndBaseIsBaseType.xsd
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/elementOfFeatureTypeIsComplexTypeSimpleContentExtensionAndBaseIsSimpleType.xsd
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/elementOfFeatureTypeIsComplexTypeSimpleContentRestrictionAndBaseIsBaseType.xsd
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/elementOfFeatureTypeIsComplexTypeSimpleContentRestrictionAndBaseIsSimpleType.xsd
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/elementOfFeatureTypeIsSimpleTypeListAndBaseIsBaseType.xsd
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/elementOfFeatureTypeIsSimpleTypeListAndBaseIsSimpleType.xsd
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/elementOfFeatureTypeIsSimpleTypeRestrictionAndBaseIsBaseType.xsd
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/elementOfFeatureTypeIsSimpleTypeRestrictionAndBaseIsSimpleType.xsd
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/elementTypeOfFeatureTypeIsComplexType.xsd
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/elementTypeOfFeatureTypeIsSimpleType.xsd
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/multipleGmlProperties.xsd
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/multipleIntegerProperties.xsd
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/multipleStringProperties.xsd
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/singleBooleanProperty.xsd
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/singleDoubleProperty.xsd
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/singleFloatProperty.xsd
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/singleGmlGeospatialProperty.xsd
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/singleGmlTemporalProperty.xsd
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/singleLongProperty.xsd
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/singleShortProperty.xsd
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/singleStringProperty.xsd
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/stringAndGmlProperties.xsd
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/stringAndGmlPropertiesComplexContent.xsd
Labels: 📈 Improvement

#4403 DDF-04401 Updated RTF transformer to remove `ext.` prefix
  catalog/transformer/catalog-transformer-rtf/src/main/java/ddf/catalog/transformer/output/rtf/RtfTemplate.java
  catalog/transformer/catalog-transformer-rtf/src/main/java/ddf/catalog/transformer/output/rtf/model/ExportCategory.java
  catalog/transformer/catalog-transformer-rtf/src/test/java/ddf/catalog/transformer/output/rtf/BaseTestConfiguration.java
  catalog/transformer/catalog-transformer-rtf/src/test/java/ddf/catalog/transformer/output/rtf/RtfQueryResponseAndMetacardTransformerTest.java
  catalog/transformer/catalog-transformer-rtf/src/test/java/ddf/catalog/transformer/output/rtf/RtfTemplateTest.java
  catalog/transformer/catalog-transformer-rtf/src/test/resources/reference-metacard-with-empty-thumbnail.rtf
  catalog/transformer/catalog-transformer-rtf/src/test/resources/reference-metacard.rtf
  catalog/transformer/catalog-transformer-rtf/src/test/resources/reference-source-response.rtf
Labels: 📈 Improvement
