Repository codice/ddf, pull requests merged in 2019-08, with the labels that each got.

#5118 DDF-5117 Made sizing and spacing of filters and query settings dropdown menus consistent
  ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/query-src/dropdown.query-src.less
  ui/packages/catalog-ui-search/src/main/webapp/component/filter-builder/filter-builder.less
  ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.less
  ui/packages/catalog-ui-search/src/main/webapp/component/input/date/input-date.less
  ui/packages/catalog-ui-search/src/main/webapp/component/input/input.less
  ui/packages/catalog-ui-search/src/main/webapp/component/property/property.less
  ui/packages/catalog-ui-search/src/main/webapp/component/sort-item/sort-item.less
  ui/packages/catalog-ui-search/src/main/webapp/component/sort/sort.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/sort/sort.less
  ui/packages/catalog-ui-search/src/main/webapp/react-component/location/location.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/location/location.less
  ui/packages/catalog-ui-search/src/main/webapp/styles/components/global-bracket.less
Labels: 👤 UI

#5098 [minor] turn off license header check on format
  ui/package.json
Labels: 👤 UI

#5172 DDF-5156 Pushes minor updates to types to help downstream
  ui/lerna.json
  ui/package.json
  ui/packages/catalog-ui-search-e2e/package.json
  ui/packages/catalog-ui-search/package.json
  ui/packages/catalog-ui-search/typings/styled-components/index.d.tsx
  ui/packages/imperio/driver.js
  ui/packages/imperio/index.js
  ui/packages/imperio/monitor.js
  ui/packages/imperio/package.json
  ui/pom.xml
  ui/yarn.lock
Labels: 👤 UI

#5185 DDF-5184 Moves imperio from dev to normal dependency
  ui/packages/catalog-ui-search/package.json
Labels: 👀 Verified

#5110 DDF-05019 Balance UI font sizes
  ui/packages/catalog-ui-search/src/main/webapp/component/golden-layout/golden-layout.less
  ui/packages/catalog-ui-search/src/main/webapp/component/upload-menu/upload-menu.less
  ui/packages/catalog-ui-search/src/main/webapp/component/workspaces-menu/workspaces-menu.less
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/button/button.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/navigation-right/navigation-right.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/navigation/navigation.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/workspace-title/workspace-title.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/workspaces-items/workspaces-items.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/workspaces-templates/workspaces-templates.tsx
  ui/packages/catalog-ui-search/src/main/webapp/styles/components/buttons.less
Labels: 👤 UI

#5189 DDF-5165 Fix a bug causing query metacards to have the wrong tag
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/query/data/metacard/QueryMetacardImpl.java
  catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/transformer/impl/AssociatedQueryMetacardsHandler.java
  catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/metacard/workspace/transformer/impl/AssociatedQueryMetacardsHandlerTest.java
Labels: 👞Bug Fix

#4466 DDF-04465 Updated preferences to a deepCopy for comparison to lastSaved
  ui/packages/catalog-ui-search/src/main/webapp/js/model/User.js
Labels: 👞Bug Fix, 👤 UI

#5091 DDF-05061 Refactor WFS sources to not use dynamically-generated attributes
  catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-converter/src/test/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/converter/impl/GenericFeatureConverterTest.java
  catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/source/WfsFilterDelegate.java
  catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/source/WfsSource.java
  catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/source/WfsFilterDelegateTest.java
  catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/source/WfsSourceTest.java
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-converter/pom.xml
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-converter/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/converter/impl/GenericFeatureConverterWfs11Test.java
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-converter/src/test/resources/basic-metacard-attributes.xml
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/pom.xml
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegate.java
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegateTest.java
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSourceTest.java
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-converter/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/converter/impl/GenericFeatureConverterTest.java
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsFilterDelegate.java
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsSource.java
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsFilterDelegateTest.java
  catalog/spatial/wfs/spatial-wfs-common/pom.xml
  catalog/spatial/wfs/spatial-wfs-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/common/FeatureAttributeDescriptor.java
  catalog/spatial/wfs/spatial-wfs-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/common/FeatureMetacardType.java
  catalog/spatial/wfs/spatial-wfs-common/src/test/java/org/codice/ddf/spatial/ogc/wfs/catalog/common/FeatureMetacardTypeTest.java
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/elementOfFeatureTypeIsSimpleTypeListAndBaseIsInlineSimpleType.xsd
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/elementOfFeatureTypeIsSimpleTypeRestrictionAndBaseIsInlineSimpleType.xsd
  catalog/spatial/wfs/spatial-wfs-common/src/test/resources/simpleType.xsd
  catalog/spatial/wfs/spatial-wfs-converter/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/converter/impl/AbstractFeatureConverter.java
  catalog/spatial/wfs/spatial-wfs-featuretransformer-xstream/src/test/java/org/codice/ddf/spatial/ogc/wfs/transformer/xstream/XStreamWfs11FeatureTransformerTest.java
  distribution/docs/src/main/resources/content/_managing/_configuring/_sources/wfs-20-source.adoc
Labels: 🔨Refactor

#5127 DDF-04746 [minor] address yarn warning
  ui/packages/catalog-ui-search-e2e/package.json
Labels: 👤 UI

#5149 DDF-05147: Fixed null date handling in `DateLongFormatTypeAdapter`
  libs/gson-support/pom.xml
  libs/gson-support/src/main/java/org/codice/gsonsupport/GsonTypeAdapters.java
  libs/gson-support/src/test/java/org/codice/gsonsupport/GsonTypeAdaptersTest.java
Labels: 👞Bug Fix

#5240 [2.16.x] DDF-5236 Improve Upgrade Documentation
  distribution/docs/src/main/resources/content/_managing/_configuring/reusing-configurations.adoc
Labels: :book: Documentation, docs-content, 🏬 Release Branch, 📈 Improvement

#5233 DDF-5162 Update plugin imports to proper path
  ui/packages/catalog-ui-search/src/main/webapp/extension-points/metacard-interactions/metacard-interactions.tsx
  ui/packages/catalog-ui-search/src/main/webapp/extension-points/navigation-right/navigation-right.tsx
  ui/packages/catalog-ui-search/src/main/webapp/plugins/metacard-interactions.tsx
Labels: 👤 UI

#5246 DDF-04746 Revert ace to a previous version to fix ui dev build
  ui/package.json
  ui/yarn.lock
Labels: 👤 UI

#5229 DDF-5228 Updates usage of extension providers so they're always applied correctly
  ui/packages/catalog-ui-search/src/main/webapp/js/extensions/marionette.ItemView.attachElContent.js
  ui/packages/catalog-ui-search/src/main/webapp/react-component/backbone-container/backbone-container.tsx
  ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/dropdown/dropdown.tsx
Labels: 👤 UI, 📈 Improvement

#5093 DDF-05092 Always set the WFS 1.1 generic feature converter coordinate order
  catalog/spatial/wfs/spatial-wfs-featuretransformer-xstream/pom.xml
  catalog/spatial/wfs/spatial-wfs-featuretransformer-xstream/src/main/java/org/codice/ddf/spatial/ogc/wfs/transformer/xstream/XStreamWfs11FeatureTransformer.java
  catalog/spatial/wfs/spatial-wfs-featuretransformer-xstream/src/test/java/org/codice/ddf/spatial/ogc/wfs/transformer/xstream/XStreamWfs11FeatureTransformerTest.java
  catalog/spatial/wfs/spatial-wfs-featuretransformer-xstream/src/test/resources/Neverland_FeatureType.xsd
Labels: 👞Bug Fix

#5247 DDF-5215 Upgrade Solr to 7.7.2
  distribution/docker/solr/src/main/docker/Dockerfile
  distribution/docs/src/main/resources/content/_managing/_configuring/_sources/solr-catalog-provider.adoc
  distribution/solr-distro/assembly.xml
  distribution/solr-distro/pom.xml
  platform/solr/solr-dependencies/pom.xml
  platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/ConfigurationFileProxy.java
  platform/solr/solr-schema/src/main/resources/solr/conf/schema.xml
  platform/solr/solr-schema/src/main/resources/solr/conf/solrconfig-inmemory.xml
  platform/solr/solr-schema/src/main/resources/solr/conf/solrconfig.xml
  pom.xml
Labels: ⬆️ Dependency Upgrade
