Repository codice/ddf, pull requests merged in 2020-09, with the labels that each got.

#6251 Log unhandled exceptions during federation strategy future execution
  catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/operation/impl/QueryImpl.java
  catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/operation/impl/QueryResponseImpl.java
  catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/federation/impl/SortedFederationStrategy.java
  catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/CreateOperations.java
  catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/DeleteOperations.java
  catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java
  catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java
  catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/federation/impl/SortedFederationStrategyTest.java
  catalog/opensearch/catalog-opensearch-source/src/test/groovy/org/codice/ddf/opensearch/source/OpenSearchSourceSpec.groovy
Labels: 👀 Verified

#6285 [2.25.x] DDF-6284 Address "Not enough arguments" SonarQube findings
  catalog/admin/catalog-admin-poller-service/src/main/java/org/codice/ddf/catalog/admin/poller/AdminPollerServiceBean.java
  catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/synchronizations/CompletionSynchronization.java
  catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/GetRecordsRequest.java
  catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java
  catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/CswSubscriptionConfigFactory.java
  catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java
  catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/CswAbstractFilterDelegate.java
  catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/CswResponseExceptionMapper.java
  catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswUnmarshallHelper.java
  catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/XStreamAttributeCopier.java
  catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/transformer/CswQueryResponseTransformer.java
  catalog/spatial/kml/spatial-kml-util/src/main/java/org/codice/ddf/spatial/kml/converter/KmlToMetacard.java
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-converter/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/converter/impl/GenericFeatureConverterWfs11.java
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-converter/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/converter/impl/GenericFeatureConverterWfs20.java
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsResponseExceptionMapper.java
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/reader/FeatureCollectionMessageBodyReaderWfs20.java
  catalog/spatial/wfs/spatial-wfs-converter/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/converter/impl/GenericFeatureConverter.java
  platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/AdminConsoleService.java
  platform/osgi/platform-osgi-configadmin/src/main/java/org/codice/felix/cm/file/ConfigurationContextImpl.java
  platform/security/certificate/security-crl-generator/src/main/java/org/codice/ddf/security/crl/generator/CrlGenerator.java
  platform/security/filter/security-filter-authorization/src/main/java/org/codice/ddf/security/filter/authorization/AuthorizationFilter.java
  platform/security/filter/security-filter-csrf/src/main/java/org/codice/ddf/security/filter/csrf/CsrfFilter.java
  platform/security/handler/security-handler-basic/src/main/java/org/codice/ddf/security/handler/basic/BasicAuthenticationHandler.java
  platform/security/handler/security-handler-saml/src/main/java/org/codice/ddf/security/idp/client/IdpHandler.java
Labels: 📈 Improvement

#6287 [2.25.x] DDF-6286 Address "Utility classes should not have public constructors" SonarQube code smells
  catalog/confluence/catalog-confluence-common/src/main/java/org/codice/ddf/confluence/common/Confluence.java
  catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/Requests.java
  catalog/core/catalog-core-api/src/main/java/ddf/catalog/Constants.java
  catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/validation/ValidateExecutor.java
  catalog/core/catalog-core-commons/src/main/java/ddf/util/InetAddressUtil.java
  catalog/core/catalog-core-commons/src/main/java/ddf/util/XPathCache.java
  catalog/core/catalog-core-impl/filter-proxy/src/main/java/ddf/catalog/filter/proxy/adapter/PeriodParser.java
  catalog/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/criteria/contenttype/ContentTypeEvaluator.java
  catalog/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/criteria/contextual/XPathEvaluator.java
  catalog/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/criteria/entry/EntryEvaluator.java
  catalog/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/criteria/geospatial/GeospatialEvaluator.java
  catalog/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/criteria/temporal/TemporalEvaluator.java
  catalog/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/internal/PubSubConstants.java
  catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/GmdConstants.java
  catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswMarshallHelper.java
  catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswUnmarshallHelper.java
  catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/XStreamAttributeCopier.java
  catalog/spatial/geocoding/spatial-geocoding-geocoder/src/main/java/org/codice/ddf/spatial/geocoder/impl/JsonpValidator.java
  catalog/spatial/kml/spatial-kml-util/src/main/java/org/codice/ddf/spatial/kml/converter/MetacardToKml.java
  catalog/spatial/kml/spatial-kml-util/src/main/java/org/codice/ddf/spatial/kml/util/KmlTransformations.java
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/common/Wfs20JTStoGML321Converter.java
  catalog/spatial/wfs/spatial-wfs-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/common/WfsQnameBuilder.java
  catalog/spatial/wfs/spatial-wfs-featuretransformer/src/main/java/org/codice/ddf/spatial/ogc/wfs/featuretransformer/impl/WfsRouteBuilder.java
  catalog/transformer/catalog-transformer-common/src/main/java/ddf/catalog/transformer/common/tika/MetacardCreator.java
  catalog/transformer/catalog-transformer-csv-common/src/main/java/ddf/catalog/transformer/csv/common/CsvTransformer.java
  catalog/transformer/catalog-transformer-overlay/src/main/java/ddf/catalog/transformer/GeometryUtils.java
  distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/XmlDocument.java
  distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/XmlSearch.java
  distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/csw/CswTestCommons.java
  distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/opensearch/OpenSearchFeature.java
  distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/opensearch/OpenSearchTestCommons.java
  distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/restito/ChunkedContent.java
  libs/geospatial/src/main/java/org/codice/ddf/libs/geo/util/GeospatialUtil.java
  libs/test-common/src/main/java/org/codice/ddf/test/common/options/FeatureOptions.java
  libs/test-common/src/main/java/org/codice/ddf/test/common/options/TestResourcesOptions.java
  platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateCommand.java
  platform/security/claims/security-claims-ldap/src/main/java/ddf/security/sts/claimsHandler/BindMethodChooser.java
  platform/security/pep/security-pep-interceptor/src/main/java/ddf/security/pep/interceptor/SecurityAssertionStore.java
  platform/util/platform-util/src/main/java/org/codice/ddf/platform/util/DateUtils.java
  platform/util/platform-util/src/main/java/org/codice/ddf/platform/util/RandomNumberGenerator.java
Labels: 📈 Improvement

#6294 DDF-6284 Address "Not enough arguments" SonarQube findings
  catalog/admin/catalog-admin-poller-service/src/main/java/org/codice/ddf/catalog/admin/poller/AdminPollerServiceBean.java
  catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java
  catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/synchronizations/CompletionSynchronization.java
  catalog/core/catalog-core-standardframework/src/main/java/org/codice/ddf/catalog/sourcepoller/SourcePollerRunner.java
  catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/GetRecordsRequest.java
  catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java
  catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/CswSubscriptionConfigFactory.java
  catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java
  catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/CswAbstractFilterDelegate.java
  catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/CswResponseExceptionMapper.java
  catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswUnmarshallHelper.java
  catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/XStreamAttributeCopier.java
  catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/transformer/CswQueryResponseTransformer.java
  catalog/spatial/kml/spatial-kml-util/src/main/java/org/codice/ddf/spatial/kml/converter/KmlToMetacard.java
  catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-converter/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/converter/impl/GenericFeatureConverterWfs11.java
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-converter/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/converter/impl/GenericFeatureConverterWfs20.java
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsResponseExceptionMapper.java
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/reader/FeatureCollectionMessageBodyReaderWfs20.java
  catalog/spatial/wfs/spatial-wfs-converter/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/converter/impl/GenericFeatureConverter.java
  distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/ServiceManagerImpl.java
  platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/AdminConsoleService.java
  platform/osgi/platform-osgi-configadmin/src/main/java/org/codice/felix/cm/file/ConfigurationContextImpl.java
  platform/security/certificate/security-crl-generator/src/main/java/org/codice/ddf/security/crl/generator/CrlGenerator.java
  platform/security/filter/security-filter-authorization/src/main/java/org/codice/ddf/security/filter/authorization/AuthorizationFilter.java
  platform/security/filter/security-filter-csrf/src/main/java/org/codice/ddf/security/filter/csrf/CsrfFilter.java
  platform/security/handler/security-handler-basic/src/main/java/org/codice/ddf/security/handler/basic/BasicAuthenticationHandler.java
  platform/security/handler/security-handler-saml/src/main/java/org/codice/ddf/security/idp/client/IdpHandler.java
Labels: 📈 Improvement

#6293 DDF-6286 Address "Utility classes should not have public constructors" SonarQube code smells
  catalog/confluence/catalog-confluence-common/src/main/java/org/codice/ddf/confluence/common/Confluence.java
  catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/Requests.java
  catalog/core/catalog-core-api/src/main/java/ddf/catalog/Constants.java
  catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/validation/ValidateExecutor.java
  catalog/core/catalog-core-commons/src/main/java/ddf/util/InetAddressUtil.java
  catalog/core/catalog-core-commons/src/main/java/ddf/util/XPathCache.java
  catalog/core/catalog-core-impl/filter-proxy/src/main/java/ddf/catalog/filter/proxy/adapter/PeriodParser.java
  catalog/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/criteria/contenttype/ContentTypeEvaluator.java
  catalog/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/criteria/contextual/XPathEvaluator.java
  catalog/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/criteria/entry/EntryEvaluator.java
  catalog/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/criteria/geospatial/GeospatialEvaluator.java
  catalog/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/criteria/temporal/TemporalEvaluator.java
  catalog/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/internal/PubSubConstants.java
  catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/GmdConstants.java
  catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswMarshallHelper.java
  catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswUnmarshallHelper.java
  catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/XStreamAttributeCopier.java
  catalog/spatial/geocoding/spatial-geocoding-geocoder/src/main/java/org/codice/ddf/spatial/geocoder/impl/JsonpValidator.java
  catalog/spatial/kml/spatial-kml-util/src/main/java/org/codice/ddf/spatial/kml/converter/MetacardToKml.java
  catalog/spatial/kml/spatial-kml-util/src/main/java/org/codice/ddf/spatial/kml/util/KmlTransformations.java
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/common/Wfs20JTStoGML321Converter.java
  catalog/spatial/wfs/spatial-wfs-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/common/WfsQnameBuilder.java
  catalog/spatial/wfs/spatial-wfs-featuretransformer/src/main/java/org/codice/ddf/spatial/ogc/wfs/featuretransformer/impl/WfsRouteBuilder.java
  catalog/transformer/catalog-transformer-common/src/main/java/ddf/catalog/transformer/common/tika/MetacardCreator.java
  catalog/transformer/catalog-transformer-csv-common/src/main/java/ddf/catalog/transformer/csv/common/CsvTransformer.java
  catalog/transformer/catalog-transformer-overlay/src/main/java/ddf/catalog/transformer/GeometryUtils.java
  distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/XmlDocument.java
  distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/XmlSearch.java
  distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/csw/CswTestCommons.java
  distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/opensearch/OpenSearchFeature.java
  distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/opensearch/OpenSearchTestCommons.java
  distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/restito/ChunkedContent.java
  libs/geospatial/src/main/java/org/codice/ddf/libs/geo/util/GeospatialUtil.java
  libs/test-common/src/main/java/org/codice/ddf/test/common/options/FeatureOptions.java
  libs/test-common/src/main/java/org/codice/ddf/test/common/options/TestResourcesOptions.java
  platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateCommand.java
  platform/security/claims/security-claims-ldap/src/main/java/ddf/security/sts/claimsHandler/BindMethodChooser.java
  platform/security/pep/security-pep-interceptor/src/main/java/ddf/security/pep/interceptor/SecurityAssertionStore.java
  platform/util/platform-util/src/main/java/org/codice/ddf/platform/util/DateUtils.java
  platform/util/platform-util/src/main/java/org/codice/ddf/platform/util/RandomNumberGenerator.java
Labels: 📈 Improvement

#6303 DDF-6302 Address "Constant names should comply with a naming convention" SonarQube code smells
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/common/Wfs20Constants.java
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsFilterDelegate.java
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsFilterDelegateTest.java
  libs/klv/src/main/java/org/codice/ddf/libs/klv/data/Klv.java
  libs/klv/src/test/java/org/codice/ddf/libs/klv/KlvContextTest.java
  libs/klv/src/test/java/org/codice/ddf/libs/klv/KlvDecoderTest.java
  libs/klv/src/test/java/org/codice/ddf/libs/klv/KlvEncodingDetectedStringTest.java
Labels: 📈 Improvement

#6297 DDF-6295 Address "Child class fields should not shadow parent class fields" SonarQube code smell
  catalog/solr/catalog-solr-commands/src/main/java/org/codice/ddf/commands/solr/SolrCommands.java
Labels: 📈 Improvement

#6296 [2.25.x] DDF-6295 Address "Child class fields should not shadow parent class fields" SonarQube code smell
  catalog/solr/catalog-solr-commands/src/main/java/org/codice/ddf/commands/solr/SolrCommands.java
Labels: 📈 Improvement

#6317 [2.25.x] DDF-6316 Address "Servlets should not have mutable instance fields" SonarQube bugs
  platform/security/servlet/security-servlet-logout/pom.xml
  platform/security/servlet/security-servlet-logout/src/main/java/org/codice/ddf/security/servlet/logout/LocalLogoutServlet.java
  platform/security/servlet/security-servlet-logout/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  platform/security/servlet/security-servlet-logout/src/test/java/org/codice/ddf/security/servlet/logout/LogoutServletTest.java
  platform/security/servlet/security-servlet-whoami/pom.xml
  platform/security/servlet/security-servlet-whoami/src/main/java/org/codice/ddf/security/servlet/whoami/WhoAmIServlet.java
  platform/security/servlet/security-servlet-whoami/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  platform/security/servlet/security-servlet-whoami/src/test/groovy/org/codice/ddf/security/servlet/whoami/WhoAmIServletSpec.groovy
Labels: 📈 Improvement

#6318 DDF-6316 Address "Servlets should not have mutable instance fields" SonarQube bugs
  platform/security/servlet/security-servlet-logout/pom.xml
  platform/security/servlet/security-servlet-logout/src/main/java/org/codice/ddf/security/servlet/logout/LocalLogoutServlet.java
  platform/security/servlet/security-servlet-logout/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  platform/security/servlet/security-servlet-logout/src/test/java/org/codice/ddf/security/servlet/logout/LogoutServletTest.java
  platform/security/servlet/security-servlet-whoami/pom.xml
  platform/security/servlet/security-servlet-whoami/src/main/java/org/codice/ddf/security/servlet/whoami/WhoAmIServlet.java
  platform/security/servlet/security-servlet-whoami/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  platform/security/servlet/security-servlet-whoami/src/test/groovy/org/codice/ddf/security/servlet/whoami/WhoAmIServletSpec.groovy
Labels: 📈 Improvement

#6304 [2.25.x] DDF-6302 Address "Constant names should comply with a naming convention" SonarQube code smells
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/common/Wfs20Constants.java
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsFilterDelegate.java
  catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsFilterDelegateTest.java
  libs/klv/src/main/java/org/codice/ddf/libs/klv/data/Klv.java
  libs/klv/src/test/java/org/codice/ddf/libs/klv/KlvContextTest.java
  libs/klv/src/test/java/org/codice/ddf/libs/klv/KlvDecoderTest.java
  libs/klv/src/test/java/org/codice/ddf/libs/klv/KlvEncodingDetectedStringTest.java
Labels: 📈 Improvement

#6314 [2.25.x] DDF-6313 Address SonarQube findings in LogoutRequestService
  platform/security/handler/security-handler-saml/pom.xml
  platform/security/handler/security-handler-saml/src/main/java/org/codice/ddf/security/idp/client/LogoutRequestService.java
  platform/security/handler/security-handler-saml/src/test/java/org/codice/ddf/security/idp/client/LogoutRequestServiceTest.java
Labels: 📈 Improvement

#6324 DDF-6313 Address SonarQube findings in LogoutRequestService
  platform/security/handler/security-handler-saml/pom.xml
  platform/security/handler/security-handler-saml/src/main/java/org/codice/ddf/security/idp/client/LogoutRequestService.java
  platform/security/handler/security-handler-saml/src/test/java/org/codice/ddf/security/idp/client/LogoutRequestServiceTest.java
Labels: 📈 Improvement

#6201 Makes solr config auto include required files if not specified
  platform/solr/solr-factory-impl/pom.xml
  platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/Configsets.java
  platform/solr/solr-factory-impl/src/test/java/org/codice/solr/factory/impl/ConfigsetsTest.java
Labels: 📈 Improvement

#6333 [2.19.x] DDF-6332: Added CSS to fix 2D zoom overlay bleed
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/openlayers.less
Labels: 👞Bug Fix

#6343 Remove some unnecessary code that was missed when the FTP endpoint was removed
  catalog/pom.xml
  distribution/ddf-common/src/main/resources/security/default.policy
  libs/test-common/src/main/java/org/codice/ddf/test/common/options/PortOptions.java
  libs/test-common/src/main/java/org/codice/ddf/test/common/options/SystemProperties.java
  pom.xml
Labels: 📈 Improvement

#6344 Update the contentDirectoryMonitor appender configuration in org.ops4j.pax.logging.cfg to match the configuration in log4j2.xml
  distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.logging.cfg
Labels: 📈 Improvement
