Repository codice/ddf, pull requests merged in 2020-07, with the labels that each got.

#6175 DDF-2824 fixed header in queries endpoint docs
  distribution/docs/src/main/resources/content/_integrating/_endpoints/query-endpoints.adoc
Labels: :book: Documentation, docs-content, 👞Bug Fix

#6178 DDF-6177 adding ID of Metacard Validators to docs
  distribution/docs/src/main/resources/content/_managing/_running/validator-plugins.adoc
Labels: :book: Documentation, docs-content, 👞Bug Fix

#6176 [2.19.x] DDF-UI-276 fix error when deleting a default search form
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form-interactions/search-form-interactions.view.js
Labels: 👞Bug Fix, 👤 UI

#6189 Decouple injected servlet filters from security policy of endpoints
  distribution/ddf-common/src/main/resources/security/default.policy
  platform/platform-paxweb-jettyconfig/src/main/java/org/codice/ddf/pax/web/jetty/DoPrivilegedFilter.java
  platform/platform-paxweb-jettyconfig/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  platform/platform-paxweb-jettyconfig/src/test/java/org/codice/ddf/pax/web/jetty/DoPrivilegedFilterTest.java
Labels: :lock: Security, 👞Bug Fix

#6163 [2.19.x] DDF-UI-262 Workspace loosing tools when Theme Zoom Percentage greater than 100%
  ui/packages/catalog-ui-search/src/main/webapp/component/golden-layout/golden-layout.less
  ui/packages/catalog-ui-search/src/main/webapp/component/golden-layout/golden-layout.view.js
Labels: 👞Bug Fix, 👤 UI

#6171 [2.19.x] DDF-UI-269 G-8544 Update map for USNG shortest distance while drawing
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js
Labels: 👞Bug Fix, 👤 UI

#6174 [2.19.x] DDF-UI-273 Theme Zoom Percentage Formatting Issues
  ui/packages/catalog-ui-search/src/main/webapp/component/lightbox/result/lightbox.result.less
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/tabs/tabs.less
Labels: 👞Bug Fix, 👤 UI

#6188 [2.19.x] G-8304 Fix intermediate result form dropdown state
  ui/packages/catalog-ui-search/src/main/webapp/component/query-editor/query-editor.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.view.js
Labels: 👞Bug Fix, 👤 UI

#6184 [2.19.x] DDF-6183 G-2068 Allow search forms to fully leverage boolean logic
  ui/packages/catalog-ui-search/src/main/webapp/component/filter-builder/filter-builder.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js
Labels: 👤 UI, 📈 Improvement

#6198 Removes empty files
  platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigratable.java
  platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigratableTest.java
  platform/notifications/core/platform-core-notifications/pom.xml
Labels: 📈 Improvement
