Repository codice/ddf, pull requests merged in 2020-03, with the labels that each got.

#5873 [2.20.x] DDF-5513 Fix anyGeo bounding box not updating correctly (#5533)
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.js
  ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.spec.js
Labels: 👞Bug Fix, 👤 UI

#5878 [2.20.x] DDF-5877 Make geo attributes indexed in solr
  platform/solr/solr-schema/src/main/resources/solr/conf/schema.xml
Labels: 👀 Verified

#5882 [2.20.x] Use SelectionInterface in metacardOverwrite
  ui/packages/catalog-ui-search/src/main/webapp/component/metacard-overwrite/metacard-overwrite.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/tabs/metacard/tabs-metacard.js
Labels: 👤 UI

#5913 DDF-2824 removed diagrams from plugin docs
  distribution/docs/src/main/resources/content/_architectures/_plugins/post-ingest-intro.adoc
  distribution/docs/src/main/resources/content/_architectures/_plugins/pre-ingest-intro.adoc
Labels: :book: Documentation, docs-content

#5886 [2.20.x] DDF-5888 Checkbox performance improvements
  ui/packages/catalog-ui-search/src/main/webapp/component/result-item/result-item.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/selection-checkbox/item-checkbox-all.tsx
  ui/packages/catalog-ui-search/src/main/webapp/component/selection-checkbox/item-checkbox.tsx
  ui/packages/catalog-ui-search/src/main/webapp/component/selection-checkbox/selection-checkbox.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/selection-checkbox/useBackbone.hook.tsx
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/row.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/row.view.js
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/thead.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/thead.view.js
Labels: 📈 Improvement

#5899 [2.20.x] DDF-5538 - Add InjectedAttributes to DynamicSchemaResolver field cache
  catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java
  catalog/solr/catalog-solr-provider/pom.xml
  catalog/solr/catalog-solr-provider/src/main/java/ddf/catalog/solr/provider/InjectedAttributeListener.java
  catalog/solr/catalog-solr-provider/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Labels: 👀 Verified

#5910 [2.20.x] DDF-5909 Clear geo search drawing correctly when using query-basic form
  ui/packages/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.view.js
Labels: 👀 Verified, 👤 UI

#5930 DDF-5927 Update ace version to b8a981b
  ui/package.json
  ui/yarn.lock
Labels: ⬆️ Dependency Upgrade
