Repository codice/ddf, pull requests merged in 2020-08, with the labels that each got.

#6207 DDF-6206
  distribution/docs/src/main/resources/content/_quickstart/quickstart-installing.adoc
  distribution/docs/src/main/resources/content/_quickstart/quickstart-intro.adoc
Labels: :book: Documentation, docs-content

#6162 [2.19.x] DDF-UI-261 Add control to add a new visual tab from the tabs similar to a browser
  ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/visualization-selector/dropdown.visualization-selector.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/golden-layout/golden-layout.hbs
  ui/packages/catalog-ui-search/src/main/webapp/component/golden-layout/golden-layout.less
  ui/packages/catalog-ui-search/src/main/webapp/component/golden-layout/golden-layout.view.js
Labels: ✨New Feature, 👤 UI

#6214 DDF-2749 removed references to intrigue from docs
  distribution/docs/src/main/resources/content/_introduction/_coreConcepts/high-availability-supported-capabilities.adoc
  distribution/docs/src/main/resources/content/_managing/_datamanagement/attributes-added-by-input-transformers.adoc
  distribution/docs/src/main/resources/content/_reference/_appReferences/mg-spatial.adoc
Labels: :book: Documentation, docs-automation

#6230 [2.25.x] DDF-6229 Remove clearCache in itests
  distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/SystemStateManager.java
Labels: 📈 Improvement

#6228 [2.25.x] DDF-6227 Update OidcHandlerConfiguration initialization failure logs from WARN to DEBUG
  platform/security/handler/security-handler-oidc/src/main/java/org/codice/ddf/security/handler/oidc/OidcHandlerConfigurationImpl.java
Labels: 📈 Improvement

#6153 DDF-6152 Added standalone solr gazetteer
  catalog/solr/catalog-solr-app/pom.xml
  catalog/solr/catalog-solr-app/src/main/resources/features.xml
  catalog/solr/catalog-solr-offline-gazetteer/pom.xml
  catalog/solr/catalog-solr-offline-gazetteer/src/main/java/ddf/catalog/solr/offlinegazetteer/BuildGazetteerSuggesterIndexCommand.java
  catalog/solr/catalog-solr-offline-gazetteer/src/main/java/ddf/catalog/solr/offlinegazetteer/CatalogGazetteerForwardingPlugin.java
  catalog/solr/catalog-solr-offline-gazetteer/src/main/java/ddf/catalog/solr/offlinegazetteer/GazetteerConstants.java
  catalog/solr/catalog-solr-offline-gazetteer/src/main/java/ddf/catalog/solr/offlinegazetteer/GazetteerQueryOfflineSolr.java
  catalog/solr/catalog-solr-offline-gazetteer/src/main/java/ddf/catalog/solr/offlinegazetteer/RemoveAllOfflineSolrGazetteerCommand.java
  catalog/solr/catalog-solr-offline-gazetteer/src/main/java/ddf/catalog/solr/offlinegazetteer/SyncCatalogCommand.java
  catalog/solr/catalog-solr-offline-gazetteer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/solr/catalog-solr-offline-gazetteer/src/test/groovy/ddf/catalog/solr/offlinegazetteer/CatalogGazetteerForwardingPluginSpec.groovy
  catalog/solr/catalog-solr-offline-gazetteer/src/test/groovy/ddf/catalog/solr/offlinegazetteer/GazetteerQueryOfflineSolrSpec.groovy
  catalog/solr/catalog-solr-offline-gazetteer/src/test/groovy/ddf/catalog/solr/offlinegazetteer/RemoveAllOfflineSolrGazetteerCommandSpec.groovy
  catalog/solr/catalog-solr-offline-gazetteer/src/test/groovy/ddf/catalog/solr/offlinegazetteer/SyncCatalogCommandSpec.groovy
  catalog/solr/pom.xml
  catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntry.java
  catalog/spatial/geocoding/spatial-geocoding-offline-index/pom.xml
  catalog/spatial/spatial-app/src/main/resources/features.xml
  distribution/docs/src/main/resources/content/_reference/_appReferences/mg-spatial.adoc
  platform/solr/solr-schema/src/main/resources/solr/conf/solrconfig.xml
Labels: ✨New Feature

#6205 [2.19.x] DDF-6204: Enum forced re-render is now selective
  ui/packages/catalog-ui-search/src/main/webapp/react-component/enum/enum.tsx
Labels: 👞Bug Fix

#6243 DDF-6229 Remove clearCache in itests
  distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/SystemStateManager.java
Labels: 📈 Improvement

#6244 DDF-6227 Update OidcHandlerConfiguration initialization failure logs from WARN to DEBUG
  platform/security/handler/security-handler-oidc/src/main/java/org/codice/ddf/security/handler/oidc/OidcHandlerConfigurationImpl.java
Labels: 📈 Improvement

#6246 [2.25.x] DDF-6245 Remove catalog-ui features from etc/application-definitions/search-ui.json and update the default search redirect to /search/simple
  catalog/ui/search-ui/search-redirect/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/ui/search-ui/search-redirect/src/main/resources/OSGI-INF/metatype/metatype.xml
  catalog/ui/search-ui/search-redirect/src/test/groovy/org/codice/ddf/ui/searchui/filter/RedirectServletSpec.groovy
  distribution/ddf-common/src/main/resources-filtered/etc/application-definitions/search-ui.json
  distribution/docs/src/main/resources/content/_reference/_tables/RedirectServlet.adoc
Labels: 📈 Improvement

#6247 DDF-6245 Remove catalog-ui features from etc/application-definitions/search-ui.json and update the default search redirect to /search/simple
  catalog/ui/search-ui/search-redirect/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  catalog/ui/search-ui/search-redirect/src/main/resources/OSGI-INF/metatype/metatype.xml
  catalog/ui/search-ui/search-redirect/src/test/groovy/org/codice/ddf/ui/searchui/filter/RedirectServletSpec.groovy
  distribution/ddf-common/src/main/resources-filtered/etc/application-definitions/search-ui.json
  distribution/docs/src/main/resources/content/_reference/_tables/RedirectServlet.adoc
Labels: 🌊Impacts Downstream, 📈 Improvement
